/**
 * Root layout.
 *
 * Boot sequence (Plan 43-04):
 *   1. Keep splash visible (preventAutoHideAsync).
 *   2. Read current Supabase session via getCurrentSession().
 *   3. router.replace to /(tabs)/inbox if signed in, else /(auth)/login.
 *   4. Hide splash.
 *
 * Also subscribes to onAuthStateChange so a signOut() anywhere in the app
 * auto-routes back to /(auth)/login.
 */

import { Stack, useRouter, type Href } from 'expo-router';
import * as SplashScreen from 'expo-splash-screen';
import { StatusBar } from 'expo-status-bar';
import { useEffect } from 'react';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import 'react-native-reanimated';
import { I18nextProvider } from 'react-i18next';
import { i18n } from '@/lib/i18n';
import { getCurrentSession, onAuthStateChange } from '@/lib/session';
import { ThemeProvider } from '@/lib/theme';

// Keep the splash screen visible until we know the auth state.
void SplashScreen.preventAutoHideAsync();

export default function RootLayout() {
  const router = useRouter();

  useEffect(() => {
    let mounted = true;

    (async () => {
      const session = await getCurrentSession();
      if (!mounted) return;
      // Route typings are generated by expo-router's dev server on first
      // metro scan. Until metro runs, the generated types don't know about
      // our route groups, so we cast to Href to satisfy tsc. Runtime paths
      // are correct.
      if (session) {
        router.replace('/(tabs)/inbox' as Href);
      } else {
        router.replace('/(auth)/login' as Href);
      }
      await SplashScreen.hideAsync();
    })();

    const unsubscribe = onAuthStateChange((session) => {
      if (!session) {
        router.replace('/(auth)/login' as Href);
      }
    });

    return () => {
      mounted = false;
      unsubscribe();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <ThemeProvider>
        <I18nextProvider i18n={i18n}>
          <Stack screenOptions={{ headerShown: false }}>
            <Stack.Screen name="(auth)" />
            <Stack.Screen name="(tabs)" />
            <Stack.Screen name="+not-found" />
          </Stack>
          <StatusBar style="auto" />
        </I18nextProvider>
      </ThemeProvider>
    </GestureHandlerRootView>
  );
}
