/**
 * No-Repetition System — Shared Types
 * Phase 34: No-Repetition System - Plan 01, Task 2
 *
 * Types used across the 3-level no-repetition filter:
 * Level 1: Exact ID match (already sent template)
 * Level 2: Minifrase semantic comparison (Haiku)
 * Level 3: Full content similarity (Haiku)
 */

import type { PrioritizedTemplate } from './block-composer'

// ---------------------------------------------------------------------------
// Outbound Registry
// ---------------------------------------------------------------------------

/** A single outbound message entry in the conversation registry */
export interface OutboundEntry {
  tipo: 'plantilla' | 'humano' | 'ia'
  /** Template ID for plantilla, null for human/AI messages */
  id: string | null
  /** Minifrase — short thematic descriptor (from DB or generated by Haiku) */
  tema: string
  /** Full message content — only populated for human/AI entries (Level 3 checks) */
  fullContent?: string
}

// ---------------------------------------------------------------------------
// Level 2: Haiku minifrase comparison
// ---------------------------------------------------------------------------

/** Level 2 Haiku decision for minifrase comparison */
export type NoRepLevel2Decision = 'ENVIAR' | 'NO_ENVIAR' | 'PARCIAL'

// ---------------------------------------------------------------------------
// Filter results
// ---------------------------------------------------------------------------

/** Result of filtering a single template through the 3-level system */
export interface FilteredTemplateEntry {
  template: PrioritizedTemplate
  /** Which level blocked this template (1=exact ID, 2=minifrase, 3=full content) */
  level: 1 | 2 | 3
  /** Human-readable reason for filtering */
  reason: string
}

/** Result of the full no-repetition filter on a block */
export interface NoRepFilterResult {
  /** Templates that passed all checks — send these */
  surviving: PrioritizedTemplate[]
  /** Templates blocked by no-repetition — do NOT send */
  filtered: FilteredTemplateEntry[]
}
