-- ============================================================================
-- DANE Municipalities Reference Table
-- Complete Colombian DIVIPOLA dataset: 1,122+ municipalities across 33 departments
-- Source: DANE DIVIPOLA (Departamento Administrativo Nacional de Estadistica)
-- ============================================================================

-- 1. Create table (global reference, NO workspace_id, NO RLS)
CREATE TABLE dane_municipalities (
  id SERIAL PRIMARY KEY,
  dane_code CHAR(5) NOT NULL UNIQUE,
  department_code CHAR(2) NOT NULL,
  department_name TEXT NOT NULL,
  municipality_name TEXT NOT NULL,
  municipality_name_normalized TEXT NOT NULL,
  department_name_normalized TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('America/Bogota', NOW())
);

-- 2. Indexes for lookup queries
CREATE INDEX idx_dane_muni_normalized ON dane_municipalities(municipality_name_normalized, department_name_normalized);
CREATE INDEX idx_dane_dept_code ON dane_municipalities(department_code);

-- 3. Permissions (NO RLS since global reference)
GRANT SELECT ON dane_municipalities TO authenticated;
GRANT SELECT ON dane_municipalities TO service_role;
GRANT USAGE, SELECT ON SEQUENCE dane_municipalities_id_seq TO authenticated, service_role;

-- 4. Seed ALL Colombian municipalities from DANE DIVIPOLA
INSERT INTO dane_municipalities (dane_code, department_code, department_name, municipality_name, municipality_name_normalized, department_name_normalized) VALUES
  ('91001', '91', 'Amazonas', 'Leticia', 'LETICIA', 'AMAZONAS'),
  ('91263', '91', 'Amazonas', 'El Encanto', 'EL ENCANTO', 'AMAZONAS'),
  ('91405', '91', 'Amazonas', 'La Chorrera', 'LA CHORRERA', 'AMAZONAS'),
  ('91407', '91', 'Amazonas', 'La Pedrera', 'LA PEDRERA', 'AMAZONAS'),
  ('91430', '91', 'Amazonas', 'La Victoria', 'LA VICTORIA', 'AMAZONAS'),
  ('91460', '91', 'Amazonas', 'Miriti - Parana', 'MIRITI - PARANA', 'AMAZONAS'),
  ('91530', '91', 'Amazonas', 'Puerto Alegria', 'PUERTO ALEGRIA', 'AMAZONAS'),
  ('91536', '91', 'Amazonas', 'Puerto Arica', 'PUERTO ARICA', 'AMAZONAS'),
  ('91540', '91', 'Amazonas', 'Puerto Narino', 'PUERTO NARINO', 'AMAZONAS'),
  ('91669', '91', 'Amazonas', 'Puerto Santander', 'PUERTO SANTANDER', 'AMAZONAS'),
  ('91798', '91', 'Amazonas', 'Tarapaca', 'TARAPACA', 'AMAZONAS'),
  ('05001', '05', 'Antioquia', 'Medellin', 'MEDELLIN', 'ANTIOQUIA'),
  ('05002', '05', 'Antioquia', 'Abejorral', 'ABEJORRAL', 'ANTIOQUIA'),
  ('05004', '05', 'Antioquia', 'Abriaqui', 'ABRIAQUI', 'ANTIOQUIA'),
  ('05021', '05', 'Antioquia', 'Alejandria', 'ALEJANDRIA', 'ANTIOQUIA'),
  ('05030', '05', 'Antioquia', 'Amaga', 'AMAGA', 'ANTIOQUIA'),
  ('05031', '05', 'Antioquia', 'Amalfi', 'AMALFI', 'ANTIOQUIA'),
  ('05034', '05', 'Antioquia', 'Andes', 'ANDES', 'ANTIOQUIA'),
  ('05036', '05', 'Antioquia', 'Angelopolis', 'ANGELOPOLIS', 'ANTIOQUIA'),
  ('05038', '05', 'Antioquia', 'Angostura', 'ANGOSTURA', 'ANTIOQUIA'),
  ('05040', '05', 'Antioquia', 'Anori', 'ANORI', 'ANTIOQUIA'),
  ('05042', '05', 'Antioquia', 'Santafe de Antioquia', 'SANTAFE DE ANTIOQUIA', 'ANTIOQUIA'),
  ('05044', '05', 'Antioquia', 'Anza', 'ANZA', 'ANTIOQUIA'),
  ('05045', '05', 'Antioquia', 'Apartado', 'APARTADO', 'ANTIOQUIA'),
  ('05051', '05', 'Antioquia', 'Arboletes', 'ARBOLETES', 'ANTIOQUIA'),
  ('05055', '05', 'Antioquia', 'Argelia', 'ARGELIA', 'ANTIOQUIA'),
  ('05059', '05', 'Antioquia', 'Armenia', 'ARMENIA', 'ANTIOQUIA'),
  ('05079', '05', 'Antioquia', 'Barbosa', 'BARBOSA', 'ANTIOQUIA'),
  ('05086', '05', 'Antioquia', 'Belmira', 'BELMIRA', 'ANTIOQUIA'),
  ('05088', '05', 'Antioquia', 'Bello', 'BELLO', 'ANTIOQUIA'),
  ('05091', '05', 'Antioquia', 'Betania', 'BETANIA', 'ANTIOQUIA'),
  ('05093', '05', 'Antioquia', 'Betulia', 'BETULIA', 'ANTIOQUIA'),
  ('05101', '05', 'Antioquia', 'Ciudad Bolivar', 'CIUDAD BOLIVAR', 'ANTIOQUIA'),
  ('05107', '05', 'Antioquia', 'Briceno', 'BRICENO', 'ANTIOQUIA'),
  ('05113', '05', 'Antioquia', 'Buritica', 'BURITICA', 'ANTIOQUIA'),
  ('05120', '05', 'Antioquia', 'Caceres', 'CACERES', 'ANTIOQUIA'),
  ('05125', '05', 'Antioquia', 'Caicedo', 'CAICEDO', 'ANTIOQUIA'),
  ('05129', '05', 'Antioquia', 'Caldas', 'CALDAS', 'ANTIOQUIA'),
  ('05134', '05', 'Antioquia', 'Campamento', 'CAMPAMENTO', 'ANTIOQUIA'),
  ('05138', '05', 'Antioquia', 'Canasgordas', 'CANASGORDAS', 'ANTIOQUIA'),
  ('05142', '05', 'Antioquia', 'Caracoli', 'CARACOLI', 'ANTIOQUIA'),
  ('05145', '05', 'Antioquia', 'Caramanta', 'CARAMANTA', 'ANTIOQUIA'),
  ('05147', '05', 'Antioquia', 'Carepa', 'CAREPA', 'ANTIOQUIA'),
  ('05148', '05', 'Antioquia', 'El Carmen de Viboral', 'EL CARMEN DE VIBORAL', 'ANTIOQUIA'),
  ('05150', '05', 'Antioquia', 'Carolina del Principe', 'CAROLINA DEL PRINCIPE', 'ANTIOQUIA'),
  ('05154', '05', 'Antioquia', 'Caucasia', 'CAUCASIA', 'ANTIOQUIA'),
  ('05172', '05', 'Antioquia', 'Chigorodo', 'CHIGORODO', 'ANTIOQUIA'),
  ('05190', '05', 'Antioquia', 'Cisneros', 'CISNEROS', 'ANTIOQUIA'),
  ('05197', '05', 'Antioquia', 'Cocorna', 'COCORNA', 'ANTIOQUIA'),
  ('05206', '05', 'Antioquia', 'Concepcion', 'CONCEPCION', 'ANTIOQUIA'),
  ('05209', '05', 'Antioquia', 'Concordia', 'CONCORDIA', 'ANTIOQUIA'),
  ('05212', '05', 'Antioquia', 'Copacabana', 'COPACABANA', 'ANTIOQUIA'),
  ('05234', '05', 'Antioquia', 'Dabeiba', 'DABEIBA', 'ANTIOQUIA'),
  ('05237', '05', 'Antioquia', 'Donmatias', 'DONMATIAS', 'ANTIOQUIA'),
  ('05240', '05', 'Antioquia', 'Ebejico', 'EBEJICO', 'ANTIOQUIA'),
  ('05250', '05', 'Antioquia', 'El Bagre', 'EL BAGRE', 'ANTIOQUIA'),
  ('05264', '05', 'Antioquia', 'Entrerrios', 'ENTRERRIOS', 'ANTIOQUIA'),
  ('05266', '05', 'Antioquia', 'Envigado', 'ENVIGADO', 'ANTIOQUIA'),
  ('05282', '05', 'Antioquia', 'Fredonia', 'FREDONIA', 'ANTIOQUIA'),
  ('05284', '05', 'Antioquia', 'Frontino', 'FRONTINO', 'ANTIOQUIA'),
  ('05306', '05', 'Antioquia', 'Giraldo', 'GIRALDO', 'ANTIOQUIA'),
  ('05308', '05', 'Antioquia', 'Girardota', 'GIRARDOTA', 'ANTIOQUIA'),
  ('05310', '05', 'Antioquia', 'Gomez Plata', 'GOMEZ PLATA', 'ANTIOQUIA'),
  ('05313', '05', 'Antioquia', 'Granada', 'GRANADA', 'ANTIOQUIA'),
  ('05315', '05', 'Antioquia', 'Guadalupe', 'GUADALUPE', 'ANTIOQUIA'),
  ('05318', '05', 'Antioquia', 'Guarne', 'GUARNE', 'ANTIOQUIA'),
  ('05321', '05', 'Antioquia', 'Guatape', 'GUATAPE', 'ANTIOQUIA'),
  ('05347', '05', 'Antioquia', 'Heliconia', 'HELICONIA', 'ANTIOQUIA'),
  ('05353', '05', 'Antioquia', 'Hispania', 'HISPANIA', 'ANTIOQUIA'),
  ('05360', '05', 'Antioquia', 'Itagui', 'ITAGUI', 'ANTIOQUIA'),
  ('05361', '05', 'Antioquia', 'Ituango', 'ITUANGO', 'ANTIOQUIA'),
  ('05364', '05', 'Antioquia', 'Jardin', 'JARDIN', 'ANTIOQUIA'),
  ('05368', '05', 'Antioquia', 'Jerico', 'JERICO', 'ANTIOQUIA'),
  ('05376', '05', 'Antioquia', 'La Ceja', 'LA CEJA', 'ANTIOQUIA'),
  ('05380', '05', 'Antioquia', 'La Estrella', 'LA ESTRELLA', 'ANTIOQUIA'),
  ('05390', '05', 'Antioquia', 'La Pintada', 'LA PINTADA', 'ANTIOQUIA'),
  ('05400', '05', 'Antioquia', 'La Union', 'LA UNION', 'ANTIOQUIA'),
  ('05411', '05', 'Antioquia', 'Liborina', 'LIBORINA', 'ANTIOQUIA'),
  ('05425', '05', 'Antioquia', 'Maceo', 'MACEO', 'ANTIOQUIA'),
  ('05440', '05', 'Antioquia', 'Marinilla', 'MARINILLA', 'ANTIOQUIA'),
  ('05467', '05', 'Antioquia', 'Montebello', 'MONTEBELLO', 'ANTIOQUIA'),
  ('05475', '05', 'Antioquia', 'Murindo', 'MURINDO', 'ANTIOQUIA'),
  ('05480', '05', 'Antioquia', 'Mutata', 'MUTATA', 'ANTIOQUIA'),
  ('05483', '05', 'Antioquia', 'Narino', 'NARINO', 'ANTIOQUIA'),
  ('05490', '05', 'Antioquia', 'Necocli', 'NECOCLI', 'ANTIOQUIA'),
  ('05495', '05', 'Antioquia', 'Nechi', 'NECHI', 'ANTIOQUIA'),
  ('05501', '05', 'Antioquia', 'Olaya', 'OLAYA', 'ANTIOQUIA'),
  ('05541', '05', 'Antioquia', 'Penol', 'PENOL', 'ANTIOQUIA'),
  ('05543', '05', 'Antioquia', 'Peque', 'PEQUE', 'ANTIOQUIA'),
  ('05576', '05', 'Antioquia', 'Pueblorrico', 'PUEBLORRICO', 'ANTIOQUIA'),
  ('05579', '05', 'Antioquia', 'Puerto Berrio', 'PUERTO BERRIO', 'ANTIOQUIA'),
  ('05585', '05', 'Antioquia', 'Puerto Nare', 'PUERTO NARE', 'ANTIOQUIA'),
  ('05591', '05', 'Antioquia', 'Puerto Triunfo', 'PUERTO TRIUNFO', 'ANTIOQUIA'),
  ('05604', '05', 'Antioquia', 'Remedios', 'REMEDIOS', 'ANTIOQUIA'),
  ('05607', '05', 'Antioquia', 'Retiro', 'RETIRO', 'ANTIOQUIA'),
  ('05615', '05', 'Antioquia', 'Rionegro', 'RIONEGRO', 'ANTIOQUIA'),
  ('05628', '05', 'Antioquia', 'Sabanalarga', 'SABANALARGA', 'ANTIOQUIA'),
  ('05631', '05', 'Antioquia', 'Sabaneta', 'SABANETA', 'ANTIOQUIA'),
  ('05642', '05', 'Antioquia', 'Salgar', 'SALGAR', 'ANTIOQUIA'),
  ('05647', '05', 'Antioquia', 'San Andres de Cuerquia', 'SAN ANDRES DE CUERQUIA', 'ANTIOQUIA');

INSERT INTO dane_municipalities (dane_code, department_code, department_name, municipality_name, municipality_name_normalized, department_name_normalized) VALUES
  ('05649', '05', 'Antioquia', 'San Carlos', 'SAN CARLOS', 'ANTIOQUIA'),
  ('05652', '05', 'Antioquia', 'San Francisco', 'SAN FRANCISCO', 'ANTIOQUIA'),
  ('05656', '05', 'Antioquia', 'San Jeronimo', 'SAN JERONIMO', 'ANTIOQUIA'),
  ('05658', '05', 'Antioquia', 'San Jose de la Montana', 'SAN JOSE DE LA MONTANA', 'ANTIOQUIA'),
  ('05659', '05', 'Antioquia', 'San Juan de Uraba', 'SAN JUAN DE URABA', 'ANTIOQUIA'),
  ('05660', '05', 'Antioquia', 'San Luis', 'SAN LUIS', 'ANTIOQUIA'),
  ('05664', '05', 'Antioquia', 'San Pedro de los Milagros', 'SAN PEDRO DE LOS MILAGROS', 'ANTIOQUIA'),
  ('05665', '05', 'Antioquia', 'San Pedro de Uraba', 'SAN PEDRO DE URABA', 'ANTIOQUIA'),
  ('05667', '05', 'Antioquia', 'San Rafael', 'SAN RAFAEL', 'ANTIOQUIA'),
  ('05670', '05', 'Antioquia', 'San Roque', 'SAN ROQUE', 'ANTIOQUIA'),
  ('05674', '05', 'Antioquia', 'San Vicente Ferrer', 'SAN VICENTE FERRER', 'ANTIOQUIA'),
  ('05679', '05', 'Antioquia', 'Santa Barbara', 'SANTA BARBARA', 'ANTIOQUIA'),
  ('05686', '05', 'Antioquia', 'Santa Rosa de Osos', 'SANTA ROSA DE OSOS', 'ANTIOQUIA'),
  ('05690', '05', 'Antioquia', 'Santo Domingo', 'SANTO DOMINGO', 'ANTIOQUIA'),
  ('05697', '05', 'Antioquia', 'El Santuario', 'EL SANTUARIO', 'ANTIOQUIA'),
  ('05736', '05', 'Antioquia', 'Segovia', 'SEGOVIA', 'ANTIOQUIA'),
  ('05756', '05', 'Antioquia', 'Sonson', 'SONSON', 'ANTIOQUIA'),
  ('05761', '05', 'Antioquia', 'Sopetran', 'SOPETRAN', 'ANTIOQUIA'),
  ('05789', '05', 'Antioquia', 'Tamesis', 'TAMESIS', 'ANTIOQUIA'),
  ('05790', '05', 'Antioquia', 'Taraza', 'TARAZA', 'ANTIOQUIA'),
  ('05792', '05', 'Antioquia', 'Tarso', 'TARSO', 'ANTIOQUIA'),
  ('05809', '05', 'Antioquia', 'Titiribi', 'TITIRIBI', 'ANTIOQUIA'),
  ('05819', '05', 'Antioquia', 'Toledo', 'TOLEDO', 'ANTIOQUIA'),
  ('05837', '05', 'Antioquia', 'Turbo', 'TURBO', 'ANTIOQUIA'),
  ('05842', '05', 'Antioquia', 'Uramita', 'URAMITA', 'ANTIOQUIA'),
  ('05847', '05', 'Antioquia', 'Urrao', 'URRAO', 'ANTIOQUIA'),
  ('05854', '05', 'Antioquia', 'Valdivia', 'VALDIVIA', 'ANTIOQUIA'),
  ('05856', '05', 'Antioquia', 'Valparaiso', 'VALPARAISO', 'ANTIOQUIA'),
  ('05858', '05', 'Antioquia', 'Vegachi', 'VEGACHI', 'ANTIOQUIA'),
  ('05861', '05', 'Antioquia', 'Venecia', 'VENECIA', 'ANTIOQUIA'),
  ('05873', '05', 'Antioquia', 'Vigia del Fuerte', 'VIGIA DEL FUERTE', 'ANTIOQUIA'),
  ('05885', '05', 'Antioquia', 'Yali', 'YALI', 'ANTIOQUIA'),
  ('05887', '05', 'Antioquia', 'Yarumal', 'YARUMAL', 'ANTIOQUIA'),
  ('05890', '05', 'Antioquia', 'Yolombo', 'YOLOMBO', 'ANTIOQUIA'),
  ('05893', '05', 'Antioquia', 'Yondo', 'YONDO', 'ANTIOQUIA'),
  ('05895', '05', 'Antioquia', 'Zaragoza', 'ZARAGOZA', 'ANTIOQUIA'),
  ('81001', '81', 'Arauca', 'Arauca', 'ARAUCA', 'ARAUCA'),
  ('81065', '81', 'Arauca', 'Arauquita', 'ARAUQUITA', 'ARAUCA'),
  ('81220', '81', 'Arauca', 'Cravo Norte', 'CRAVO NORTE', 'ARAUCA'),
  ('81300', '81', 'Arauca', 'Fortul', 'FORTUL', 'ARAUCA'),
  ('81591', '81', 'Arauca', 'Puerto Rondon', 'PUERTO RONDON', 'ARAUCA'),
  ('81736', '81', 'Arauca', 'Saravena', 'SARAVENA', 'ARAUCA'),
  ('81794', '81', 'Arauca', 'Tame', 'TAME', 'ARAUCA'),
  ('08001', '08', 'Atlantico', 'Barranquilla', 'BARRANQUILLA', 'ATLANTICO'),
  ('08078', '08', 'Atlantico', 'Baranoa', 'BARANOA', 'ATLANTICO'),
  ('08137', '08', 'Atlantico', 'Campo de la Cruz', 'CAMPO DE LA CRUZ', 'ATLANTICO'),
  ('08141', '08', 'Atlantico', 'Candelaria', 'CANDELARIA', 'ATLANTICO'),
  ('08296', '08', 'Atlantico', 'Galapa', 'GALAPA', 'ATLANTICO'),
  ('08372', '08', 'Atlantico', 'Juan de Acosta', 'JUAN DE ACOSTA', 'ATLANTICO'),
  ('08421', '08', 'Atlantico', 'Luruaco', 'LURUACO', 'ATLANTICO'),
  ('08433', '08', 'Atlantico', 'Malambo', 'MALAMBO', 'ATLANTICO'),
  ('08436', '08', 'Atlantico', 'Manati', 'MANATI', 'ATLANTICO'),
  ('08520', '08', 'Atlantico', 'Palmar de Varela', 'PALMAR DE VARELA', 'ATLANTICO'),
  ('08549', '08', 'Atlantico', 'Piojo', 'PIOJO', 'ATLANTICO'),
  ('08558', '08', 'Atlantico', 'Polonuevo', 'POLONUEVO', 'ATLANTICO'),
  ('08560', '08', 'Atlantico', 'Ponedera', 'PONEDERA', 'ATLANTICO'),
  ('08573', '08', 'Atlantico', 'Puerto Colombia', 'PUERTO COLOMBIA', 'ATLANTICO'),
  ('08606', '08', 'Atlantico', 'Repelon', 'REPELON', 'ATLANTICO'),
  ('08634', '08', 'Atlantico', 'Sabanagrande', 'SABANAGRANDE', 'ATLANTICO'),
  ('08638', '08', 'Atlantico', 'Sabanalarga', 'SABANALARGA', 'ATLANTICO'),
  ('08675', '08', 'Atlantico', 'Santa Lucia', 'SANTA LUCIA', 'ATLANTICO'),
  ('08685', '08', 'Atlantico', 'Santo Tomas', 'SANTO TOMAS', 'ATLANTICO'),
  ('08758', '08', 'Atlantico', 'Soledad', 'SOLEDAD', 'ATLANTICO'),
  ('08770', '08', 'Atlantico', 'Suan', 'SUAN', 'ATLANTICO'),
  ('08832', '08', 'Atlantico', 'Tubara', 'TUBARA', 'ATLANTICO'),
  ('08849', '08', 'Atlantico', 'Usiacuri', 'USIACURI', 'ATLANTICO'),
  ('11001', '11', 'Bogota D.C.', 'Bogota D.C.', 'BOGOTA D.C.', 'BOGOTA D.C.'),
  ('13001', '13', 'Bolivar', 'Cartagena de Indias', 'CARTAGENA DE INDIAS', 'BOLIVAR'),
  ('13006', '13', 'Bolivar', 'Achi', 'ACHI', 'BOLIVAR'),
  ('13030', '13', 'Bolivar', 'Altos del Rosario', 'ALTOS DEL ROSARIO', 'BOLIVAR'),
  ('13042', '13', 'Bolivar', 'Arenal', 'ARENAL', 'BOLIVAR'),
  ('13052', '13', 'Bolivar', 'Arjona', 'ARJONA', 'BOLIVAR'),
  ('13062', '13', 'Bolivar', 'Arroyohondo', 'ARROYOHONDO', 'BOLIVAR'),
  ('13074', '13', 'Bolivar', 'Barranco de Loba', 'BARRANCO DE LOBA', 'BOLIVAR'),
  ('13140', '13', 'Bolivar', 'Calamar', 'CALAMAR', 'BOLIVAR'),
  ('13160', '13', 'Bolivar', 'Cantagallo', 'CANTAGALLO', 'BOLIVAR'),
  ('13188', '13', 'Bolivar', 'Cicuco', 'CICUCO', 'BOLIVAR'),
  ('13212', '13', 'Bolivar', 'Cordoba', 'CORDOBA', 'BOLIVAR'),
  ('13222', '13', 'Bolivar', 'Clemencia', 'CLEMENCIA', 'BOLIVAR'),
  ('13244', '13', 'Bolivar', 'El Carmen de Bolivar', 'EL CARMEN DE BOLIVAR', 'BOLIVAR'),
  ('13248', '13', 'Bolivar', 'El Guamo', 'EL GUAMO', 'BOLIVAR'),
  ('13268', '13', 'Bolivar', 'El Penon', 'EL PENON', 'BOLIVAR'),
  ('13300', '13', 'Bolivar', 'Hatillo de Loba', 'HATILLO DE LOBA', 'BOLIVAR'),
  ('13430', '13', 'Bolivar', 'Magangue', 'MAGANGUE', 'BOLIVAR'),
  ('13433', '13', 'Bolivar', 'Mahates', 'MAHATES', 'BOLIVAR'),
  ('13440', '13', 'Bolivar', 'Margarita', 'MARGARITA', 'BOLIVAR'),
  ('13442', '13', 'Bolivar', 'Maria la Baja', 'MARIA LA BAJA', 'BOLIVAR'),
  ('13458', '13', 'Bolivar', 'Montecristo', 'MONTECRISTO', 'BOLIVAR'),
  ('13468', '13', 'Bolivar', 'Mompos', 'MOMPOS', 'BOLIVAR'),
  ('13473', '13', 'Bolivar', 'Morales', 'MORALES', 'BOLIVAR'),
  ('13490', '13', 'Bolivar', 'Norosi', 'NOROSI', 'BOLIVAR'),
  ('13549', '13', 'Bolivar', 'Pinillos', 'PINILLOS', 'BOLIVAR'),
  ('13580', '13', 'Bolivar', 'Regidor', 'REGIDOR', 'BOLIVAR'),
  ('13600', '13', 'Bolivar', 'Rio Viejo', 'RIO VIEJO', 'BOLIVAR'),
  ('13620', '13', 'Bolivar', 'San Cristobal', 'SAN CRISTOBAL', 'BOLIVAR'),
  ('13647', '13', 'Bolivar', 'San Estanislao', 'SAN ESTANISLAO', 'BOLIVAR'),
  ('13650', '13', 'Bolivar', 'San Fernando', 'SAN FERNANDO', 'BOLIVAR'),
  ('13654', '13', 'Bolivar', 'San Jacinto', 'SAN JACINTO', 'BOLIVAR'),
  ('13655', '13', 'Bolivar', 'San Jacinto del Cauca', 'SAN JACINTO DEL CAUCA', 'BOLIVAR'),
  ('13657', '13', 'Bolivar', 'San Juan Nepomuceno', 'SAN JUAN NEPOMUCENO', 'BOLIVAR');

INSERT INTO dane_municipalities (dane_code, department_code, department_name, municipality_name, municipality_name_normalized, department_name_normalized) VALUES
  ('13667', '13', 'Bolivar', 'San Martin de Loba', 'SAN MARTIN DE LOBA', 'BOLIVAR'),
  ('13670', '13', 'Bolivar', 'San Pablo', 'SAN PABLO', 'BOLIVAR'),
  ('13673', '13', 'Bolivar', 'Santa Catalina', 'SANTA CATALINA', 'BOLIVAR'),
  ('13683', '13', 'Bolivar', 'Santa Rosa', 'SANTA ROSA', 'BOLIVAR'),
  ('13688', '13', 'Bolivar', 'Santa Rosa del Sur', 'SANTA ROSA DEL SUR', 'BOLIVAR'),
  ('13744', '13', 'Bolivar', 'Simiti', 'SIMITI', 'BOLIVAR'),
  ('13760', '13', 'Bolivar', 'Soplaviento', 'SOPLAVIENTO', 'BOLIVAR'),
  ('13780', '13', 'Bolivar', 'Talaigua Nuevo', 'TALAIGUA NUEVO', 'BOLIVAR'),
  ('13810', '13', 'Bolivar', 'Tiquisio', 'TIQUISIO', 'BOLIVAR'),
  ('13836', '13', 'Bolivar', 'Turbaco', 'TURBACO', 'BOLIVAR'),
  ('13838', '13', 'Bolivar', 'Turbana', 'TURBANA', 'BOLIVAR'),
  ('13873', '13', 'Bolivar', 'Villanueva', 'VILLANUEVA', 'BOLIVAR'),
  ('13894', '13', 'Bolivar', 'Zambrano', 'ZAMBRANO', 'BOLIVAR'),
  ('15001', '15', 'Boyaca', 'Tunja', 'TUNJA', 'BOYACA'),
  ('15022', '15', 'Boyaca', 'Almeida', 'ALMEIDA', 'BOYACA'),
  ('15047', '15', 'Boyaca', 'Aquitania', 'AQUITANIA', 'BOYACA'),
  ('15051', '15', 'Boyaca', 'Arcabuco', 'ARCABUCO', 'BOYACA'),
  ('15087', '15', 'Boyaca', 'Belen', 'BELEN', 'BOYACA'),
  ('15090', '15', 'Boyaca', 'Berbeo', 'BERBEO', 'BOYACA'),
  ('15092', '15', 'Boyaca', 'Beteitiva', 'BETEITIVA', 'BOYACA'),
  ('15097', '15', 'Boyaca', 'Boavita', 'BOAVITA', 'BOYACA'),
  ('15104', '15', 'Boyaca', 'Boyaca', 'BOYACA', 'BOYACA'),
  ('15106', '15', 'Boyaca', 'Briceno', 'BRICENO', 'BOYACA'),
  ('15109', '15', 'Boyaca', 'Buenavista', 'BUENAVISTA', 'BOYACA'),
  ('15114', '15', 'Boyaca', 'Busbanza', 'BUSBANZA', 'BOYACA'),
  ('15131', '15', 'Boyaca', 'Caldas', 'CALDAS', 'BOYACA'),
  ('15135', '15', 'Boyaca', 'Campohermoso', 'CAMPOHERMOSO', 'BOYACA'),
  ('15162', '15', 'Boyaca', 'Cerinza', 'CERINZA', 'BOYACA'),
  ('15172', '15', 'Boyaca', 'Chinavita', 'CHINAVITA', 'BOYACA'),
  ('15176', '15', 'Boyaca', 'Chiquinquira', 'CHIQUINQUIRA', 'BOYACA'),
  ('15180', '15', 'Boyaca', 'Chiscas', 'CHISCAS', 'BOYACA'),
  ('15183', '15', 'Boyaca', 'Chita', 'CHITA', 'BOYACA'),
  ('15185', '15', 'Boyaca', 'Chitaraque', 'CHITARAQUE', 'BOYACA'),
  ('15187', '15', 'Boyaca', 'Chivata', 'CHIVATA', 'BOYACA'),
  ('15189', '15', 'Boyaca', 'Cienega', 'CIENEGA', 'BOYACA'),
  ('15204', '15', 'Boyaca', 'Combita', 'COMBITA', 'BOYACA'),
  ('15212', '15', 'Boyaca', 'Coper', 'COPER', 'BOYACA'),
  ('15215', '15', 'Boyaca', 'Corrales', 'CORRALES', 'BOYACA'),
  ('15218', '15', 'Boyaca', 'Covarachia', 'COVARACHIA', 'BOYACA'),
  ('15223', '15', 'Boyaca', 'Cubara', 'CUBARA', 'BOYACA'),
  ('15224', '15', 'Boyaca', 'Cucaita', 'CUCAITA', 'BOYACA'),
  ('15226', '15', 'Boyaca', 'Cuitiva', 'CUITIVA', 'BOYACA'),
  ('15232', '15', 'Boyaca', 'Chiquiza', 'CHIQUIZA', 'BOYACA'),
  ('15236', '15', 'Boyaca', 'Chivor', 'CHIVOR', 'BOYACA'),
  ('15238', '15', 'Boyaca', 'Duitama', 'DUITAMA', 'BOYACA'),
  ('15244', '15', 'Boyaca', 'El Cocuy', 'EL COCUY', 'BOYACA'),
  ('15248', '15', 'Boyaca', 'El Espino', 'EL ESPINO', 'BOYACA'),
  ('15272', '15', 'Boyaca', 'Firavitoba', 'FIRAVITOBA', 'BOYACA'),
  ('15276', '15', 'Boyaca', 'Floresta', 'FLORESTA', 'BOYACA'),
  ('15293', '15', 'Boyaca', 'Gachantiva', 'GACHANTIVA', 'BOYACA'),
  ('15296', '15', 'Boyaca', 'Gameza', 'GAMEZA', 'BOYACA'),
  ('15299', '15', 'Boyaca', 'Garagoa', 'GARAGOA', 'BOYACA'),
  ('15317', '15', 'Boyaca', 'Guacamayas', 'GUACAMAYAS', 'BOYACA'),
  ('15322', '15', 'Boyaca', 'Guateque', 'GUATEQUE', 'BOYACA'),
  ('15325', '15', 'Boyaca', 'Guayata', 'GUAYATA', 'BOYACA'),
  ('15332', '15', 'Boyaca', 'Guican de la Sierra', 'GUICAN DE LA SIERRA', 'BOYACA'),
  ('15362', '15', 'Boyaca', 'Iza', 'IZA', 'BOYACA'),
  ('15367', '15', 'Boyaca', 'Jenesano', 'JENESANO', 'BOYACA'),
  ('15368', '15', 'Boyaca', 'Jerico', 'JERICO', 'BOYACA'),
  ('15377', '15', 'Boyaca', 'Labranzagrande', 'LABRANZAGRANDE', 'BOYACA'),
  ('15380', '15', 'Boyaca', 'La Capilla', 'LA CAPILLA', 'BOYACA'),
  ('15401', '15', 'Boyaca', 'La Victoria', 'LA VICTORIA', 'BOYACA'),
  ('15403', '15', 'Boyaca', 'La Uvita', 'LA UVITA', 'BOYACA'),
  ('15407', '15', 'Boyaca', 'Villa de Leyva', 'VILLA DE LEYVA', 'BOYACA'),
  ('15425', '15', 'Boyaca', 'Macanal', 'MACANAL', 'BOYACA'),
  ('15442', '15', 'Boyaca', 'Maripi', 'MARIPI', 'BOYACA'),
  ('15455', '15', 'Boyaca', 'Miraflores', 'MIRAFLORES', 'BOYACA'),
  ('15464', '15', 'Boyaca', 'Mongua', 'MONGUA', 'BOYACA'),
  ('15466', '15', 'Boyaca', 'Mongui', 'MONGUI', 'BOYACA'),
  ('15469', '15', 'Boyaca', 'Moniquira', 'MONIQUIRA', 'BOYACA'),
  ('15476', '15', 'Boyaca', 'Motavita', 'MOTAVITA', 'BOYACA'),
  ('15480', '15', 'Boyaca', 'Muzo', 'MUZO', 'BOYACA'),
  ('15491', '15', 'Boyaca', 'Nobsa', 'NOBSA', 'BOYACA'),
  ('15494', '15', 'Boyaca', 'Nuevo Colon', 'NUEVO COLON', 'BOYACA'),
  ('15500', '15', 'Boyaca', 'Oicata', 'OICATA', 'BOYACA'),
  ('15507', '15', 'Boyaca', 'Otanche', 'OTANCHE', 'BOYACA'),
  ('15511', '15', 'Boyaca', 'Pachavita', 'PACHAVITA', 'BOYACA'),
  ('15514', '15', 'Boyaca', 'Paez', 'PAEZ', 'BOYACA'),
  ('15516', '15', 'Boyaca', 'Paipa', 'PAIPA', 'BOYACA'),
  ('15518', '15', 'Boyaca', 'Pajarito', 'PAJARITO', 'BOYACA'),
  ('15522', '15', 'Boyaca', 'Panqueba', 'PANQUEBA', 'BOYACA'),
  ('15531', '15', 'Boyaca', 'Pauna', 'PAUNA', 'BOYACA'),
  ('15533', '15', 'Boyaca', 'Paya', 'PAYA', 'BOYACA'),
  ('15537', '15', 'Boyaca', 'Paz de Rio', 'PAZ DE RIO', 'BOYACA'),
  ('15542', '15', 'Boyaca', 'Pesca', 'PESCA', 'BOYACA'),
  ('15550', '15', 'Boyaca', 'Pisba', 'PISBA', 'BOYACA'),
  ('15572', '15', 'Boyaca', 'Puerto Boyaca', 'PUERTO BOYACA', 'BOYACA'),
  ('15580', '15', 'Boyaca', 'Quipama', 'QUIPAMA', 'BOYACA'),
  ('15599', '15', 'Boyaca', 'Ramiriqui', 'RAMIRIQUI', 'BOYACA'),
  ('15600', '15', 'Boyaca', 'Raquira', 'RAQUIRA', 'BOYACA'),
  ('15621', '15', 'Boyaca', 'Rondon', 'RONDON', 'BOYACA'),
  ('15632', '15', 'Boyaca', 'Saboya', 'SABOYA', 'BOYACA'),
  ('15638', '15', 'Boyaca', 'Sachica', 'SACHICA', 'BOYACA'),
  ('15646', '15', 'Boyaca', 'Samaca', 'SAMACA', 'BOYACA'),
  ('15660', '15', 'Boyaca', 'San Eduardo', 'SAN EDUARDO', 'BOYACA'),
  ('15664', '15', 'Boyaca', 'San Jose de Pare', 'SAN JOSE DE PARE', 'BOYACA'),
  ('15667', '15', 'Boyaca', 'San Luis de Gaceno', 'SAN LUIS DE GACENO', 'BOYACA'),
  ('15673', '15', 'Boyaca', 'San Mateo', 'SAN MATEO', 'BOYACA'),
  ('15676', '15', 'Boyaca', 'San Miguel de Sema', 'SAN MIGUEL DE SEMA', 'BOYACA'),
  ('15681', '15', 'Boyaca', 'San Pablo de Borbur', 'SAN PABLO DE BORBUR', 'BOYACA');

INSERT INTO dane_municipalities (dane_code, department_code, department_name, municipality_name, municipality_name_normalized, department_name_normalized) VALUES
  ('15686', '15', 'Boyaca', 'Santana', 'SANTANA', 'BOYACA'),
  ('15690', '15', 'Boyaca', 'Santa Maria', 'SANTA MARIA', 'BOYACA'),
  ('15693', '15', 'Boyaca', 'Santa Rosa de Viterbo', 'SANTA ROSA DE VITERBO', 'BOYACA'),
  ('15696', '15', 'Boyaca', 'Santa Sofia', 'SANTA SOFIA', 'BOYACA'),
  ('15720', '15', 'Boyaca', 'Sativanorte', 'SATIVANORTE', 'BOYACA'),
  ('15723', '15', 'Boyaca', 'Sativasur', 'SATIVASUR', 'BOYACA'),
  ('15740', '15', 'Boyaca', 'Siachoque', 'SIACHOQUE', 'BOYACA'),
  ('15753', '15', 'Boyaca', 'Soata', 'SOATA', 'BOYACA'),
  ('15755', '15', 'Boyaca', 'Socota', 'SOCOTA', 'BOYACA'),
  ('15757', '15', 'Boyaca', 'Socha', 'SOCHA', 'BOYACA'),
  ('15759', '15', 'Boyaca', 'Sogamoso', 'SOGAMOSO', 'BOYACA'),
  ('15761', '15', 'Boyaca', 'Somondoco', 'SOMONDOCO', 'BOYACA'),
  ('15762', '15', 'Boyaca', 'Sora', 'SORA', 'BOYACA'),
  ('15763', '15', 'Boyaca', 'Sotaquira', 'SOTAQUIRA', 'BOYACA'),
  ('15764', '15', 'Boyaca', 'Soraca', 'SORACA', 'BOYACA'),
  ('15774', '15', 'Boyaca', 'Susacon', 'SUSACON', 'BOYACA'),
  ('15776', '15', 'Boyaca', 'Sutamarchan', 'SUTAMARCHAN', 'BOYACA'),
  ('15778', '15', 'Boyaca', 'Sutatenza', 'SUTATENZA', 'BOYACA'),
  ('15790', '15', 'Boyaca', 'Tasco', 'TASCO', 'BOYACA'),
  ('15798', '15', 'Boyaca', 'Tenza', 'TENZA', 'BOYACA'),
  ('15804', '15', 'Boyaca', 'Tibana', 'TIBANA', 'BOYACA'),
  ('15806', '15', 'Boyaca', 'Tibasosa', 'TIBASOSA', 'BOYACA'),
  ('15808', '15', 'Boyaca', 'Tinjaca', 'TINJACA', 'BOYACA'),
  ('15810', '15', 'Boyaca', 'Tipacoque', 'TIPACOQUE', 'BOYACA'),
  ('15814', '15', 'Boyaca', 'Toca', 'TOCA', 'BOYACA'),
  ('15816', '15', 'Boyaca', 'Togui', 'TOGUI', 'BOYACA'),
  ('15820', '15', 'Boyaca', 'Topaga', 'TOPAGA', 'BOYACA'),
  ('15822', '15', 'Boyaca', 'Tota', 'TOTA', 'BOYACA'),
  ('15832', '15', 'Boyaca', 'Tunungua', 'TUNUNGUA', 'BOYACA'),
  ('15835', '15', 'Boyaca', 'Turmeque', 'TURMEQUE', 'BOYACA'),
  ('15837', '15', 'Boyaca', 'Tuta', 'TUTA', 'BOYACA'),
  ('15839', '15', 'Boyaca', 'Tutaza', 'TUTAZA', 'BOYACA'),
  ('15842', '15', 'Boyaca', 'Umbita', 'UMBITA', 'BOYACA'),
  ('15861', '15', 'Boyaca', 'Ventaquemada', 'VENTAQUEMADA', 'BOYACA'),
  ('15879', '15', 'Boyaca', 'Viracacha', 'VIRACACHA', 'BOYACA'),
  ('15897', '15', 'Boyaca', 'Zetaquira', 'ZETAQUIRA', 'BOYACA'),
  ('17001', '17', 'Caldas', 'Manizales', 'MANIZALES', 'CALDAS'),
  ('17013', '17', 'Caldas', 'Aguadas', 'AGUADAS', 'CALDAS'),
  ('17042', '17', 'Caldas', 'Anserma', 'ANSERMA', 'CALDAS'),
  ('17050', '17', 'Caldas', 'Aranzazu', 'ARANZAZU', 'CALDAS'),
  ('17088', '17', 'Caldas', 'Belalcazar', 'BELALCAZAR', 'CALDAS'),
  ('17174', '17', 'Caldas', 'Chinchina', 'CHINCHINA', 'CALDAS'),
  ('17272', '17', 'Caldas', 'Filadelfia', 'FILADELFIA', 'CALDAS'),
  ('17380', '17', 'Caldas', 'La Dorada', 'LA DORADA', 'CALDAS'),
  ('17388', '17', 'Caldas', 'La Merced', 'LA MERCED', 'CALDAS'),
  ('17433', '17', 'Caldas', 'Manzanares', 'MANZANARES', 'CALDAS'),
  ('17442', '17', 'Caldas', 'Marmato', 'MARMATO', 'CALDAS'),
  ('17444', '17', 'Caldas', 'Marquetalia', 'MARQUETALIA', 'CALDAS'),
  ('17446', '17', 'Caldas', 'Marulanda', 'MARULANDA', 'CALDAS'),
  ('17486', '17', 'Caldas', 'Neira', 'NEIRA', 'CALDAS'),
  ('17495', '17', 'Caldas', 'Norcasia', 'NORCASIA', 'CALDAS'),
  ('17513', '17', 'Caldas', 'Pacora', 'PACORA', 'CALDAS'),
  ('17524', '17', 'Caldas', 'Palestina', 'PALESTINA', 'CALDAS'),
  ('17541', '17', 'Caldas', 'Pensilvania', 'PENSILVANIA', 'CALDAS'),
  ('17614', '17', 'Caldas', 'Riosucio', 'RIOSUCIO', 'CALDAS'),
  ('17616', '17', 'Caldas', 'Risaralda', 'RISARALDA', 'CALDAS'),
  ('17653', '17', 'Caldas', 'Salamina', 'SALAMINA', 'CALDAS'),
  ('17662', '17', 'Caldas', 'Samana', 'SAMANA', 'CALDAS'),
  ('17665', '17', 'Caldas', 'San Jose', 'SAN JOSE', 'CALDAS'),
  ('17777', '17', 'Caldas', 'Supia', 'SUPIA', 'CALDAS'),
  ('17867', '17', 'Caldas', 'Victoria', 'VICTORIA', 'CALDAS'),
  ('17873', '17', 'Caldas', 'Villamaria', 'VILLAMARIA', 'CALDAS'),
  ('17877', '17', 'Caldas', 'Viterbo', 'VITERBO', 'CALDAS'),
  ('18001', '18', 'Caqueta', 'Florencia', 'FLORENCIA', 'CAQUETA'),
  ('18029', '18', 'Caqueta', 'Albania', 'ALBANIA', 'CAQUETA'),
  ('18094', '18', 'Caqueta', 'Belen de los Andaquies', 'BELEN DE LOS ANDAQUIES', 'CAQUETA'),
  ('18150', '18', 'Caqueta', 'Cartagena del Chaira', 'CARTAGENA DEL CHAIRA', 'CAQUETA'),
  ('18205', '18', 'Caqueta', 'Curillo', 'CURILLO', 'CAQUETA'),
  ('18247', '18', 'Caqueta', 'El Doncello', 'EL DONCELLO', 'CAQUETA'),
  ('18256', '18', 'Caqueta', 'El Paujil', 'EL PAUJIL', 'CAQUETA'),
  ('18410', '18', 'Caqueta', 'La Montanita', 'LA MONTANITA', 'CAQUETA'),
  ('18460', '18', 'Caqueta', 'Milan', 'MILAN', 'CAQUETA'),
  ('18479', '18', 'Caqueta', 'Morelia', 'MORELIA', 'CAQUETA'),
  ('18592', '18', 'Caqueta', 'Puerto Rico', 'PUERTO RICO', 'CAQUETA'),
  ('18610', '18', 'Caqueta', 'San Jose del Fragua', 'SAN JOSE DEL FRAGUA', 'CAQUETA'),
  ('18753', '18', 'Caqueta', 'San Vicente del Caguan', 'SAN VICENTE DEL CAGUAN', 'CAQUETA'),
  ('18756', '18', 'Caqueta', 'Solano', 'SOLANO', 'CAQUETA'),
  ('18785', '18', 'Caqueta', 'Solita', 'SOLITA', 'CAQUETA'),
  ('18860', '18', 'Caqueta', 'Valparaiso', 'VALPARAISO', 'CAQUETA'),
  ('85001', '85', 'Casanare', 'Yopal', 'YOPAL', 'CASANARE'),
  ('85010', '85', 'Casanare', 'Aguazul', 'AGUAZUL', 'CASANARE'),
  ('85015', '85', 'Casanare', 'Chameza', 'CHAMEZA', 'CASANARE'),
  ('85125', '85', 'Casanare', 'Hato Corozal', 'HATO COROZAL', 'CASANARE'),
  ('85136', '85', 'Casanare', 'La Salina', 'LA SALINA', 'CASANARE'),
  ('85139', '85', 'Casanare', 'Mani', 'MANI', 'CASANARE'),
  ('85162', '85', 'Casanare', 'Monterrey', 'MONTERREY', 'CASANARE'),
  ('85225', '85', 'Casanare', 'Nunchia', 'NUNCHIA', 'CASANARE'),
  ('85230', '85', 'Casanare', 'Orocue', 'OROCUE', 'CASANARE'),
  ('85250', '85', 'Casanare', 'Paz de Ariporo', 'PAZ DE ARIPORO', 'CASANARE'),
  ('85263', '85', 'Casanare', 'Pore', 'PORE', 'CASANARE'),
  ('85279', '85', 'Casanare', 'Recetor', 'RECETOR', 'CASANARE'),
  ('85300', '85', 'Casanare', 'Sabanalarga', 'SABANALARGA', 'CASANARE'),
  ('85315', '85', 'Casanare', 'Sacama', 'SACAMA', 'CASANARE'),
  ('85325', '85', 'Casanare', 'San Luis de Palenque', 'SAN LUIS DE PALENQUE', 'CASANARE'),
  ('85400', '85', 'Casanare', 'Tamara', 'TAMARA', 'CASANARE'),
  ('85410', '85', 'Casanare', 'Tauramena', 'TAURAMENA', 'CASANARE'),
  ('85430', '85', 'Casanare', 'Trinidad', 'TRINIDAD', 'CASANARE'),
  ('85440', '85', 'Casanare', 'Villanueva', 'VILLANUEVA', 'CASANARE'),
  ('19001', '19', 'Cauca', 'Popayan', 'POPAYAN', 'CAUCA'),
  ('19022', '19', 'Cauca', 'Almaguer', 'ALMAGUER', 'CAUCA');

INSERT INTO dane_municipalities (dane_code, department_code, department_name, municipality_name, municipality_name_normalized, department_name_normalized) VALUES
  ('19050', '19', 'Cauca', 'Argelia', 'ARGELIA', 'CAUCA'),
  ('19075', '19', 'Cauca', 'Balboa', 'BALBOA', 'CAUCA'),
  ('19100', '19', 'Cauca', 'Bolivar', 'BOLIVAR', 'CAUCA'),
  ('19110', '19', 'Cauca', 'Buenos Aires', 'BUENOS AIRES', 'CAUCA'),
  ('19130', '19', 'Cauca', 'Cajibio', 'CAJIBIO', 'CAUCA'),
  ('19137', '19', 'Cauca', 'Caldono', 'CALDONO', 'CAUCA'),
  ('19142', '19', 'Cauca', 'Caloto', 'CALOTO', 'CAUCA'),
  ('19212', '19', 'Cauca', 'Corinto', 'CORINTO', 'CAUCA'),
  ('19256', '19', 'Cauca', 'El Tambo', 'EL TAMBO', 'CAUCA'),
  ('19290', '19', 'Cauca', 'Florencia', 'FLORENCIA', 'CAUCA'),
  ('19300', '19', 'Cauca', 'Guachene', 'GUACHENE', 'CAUCA'),
  ('19318', '19', 'Cauca', 'Guapi', 'GUAPI', 'CAUCA'),
  ('19355', '19', 'Cauca', 'Inza', 'INZA', 'CAUCA'),
  ('19364', '19', 'Cauca', 'Jambalo', 'JAMBALO', 'CAUCA'),
  ('19392', '19', 'Cauca', 'La Sierra', 'LA SIERRA', 'CAUCA'),
  ('19397', '19', 'Cauca', 'La Vega', 'LA VEGA', 'CAUCA'),
  ('19418', '19', 'Cauca', 'Lopez de Micay', 'LOPEZ DE MICAY', 'CAUCA'),
  ('19450', '19', 'Cauca', 'Mercaderes', 'MERCADERES', 'CAUCA'),
  ('19455', '19', 'Cauca', 'Miranda', 'MIRANDA', 'CAUCA'),
  ('19473', '19', 'Cauca', 'Morales', 'MORALES', 'CAUCA'),
  ('19513', '19', 'Cauca', 'Padilla', 'PADILLA', 'CAUCA'),
  ('19517', '19', 'Cauca', 'Paez', 'PAEZ', 'CAUCA'),
  ('19532', '19', 'Cauca', 'Patia', 'PATIA', 'CAUCA'),
  ('19533', '19', 'Cauca', 'Piamonte', 'PIAMONTE', 'CAUCA'),
  ('19548', '19', 'Cauca', 'Piendamo', 'PIENDAMO', 'CAUCA'),
  ('19573', '19', 'Cauca', 'Puerto Tejada', 'PUERTO TEJADA', 'CAUCA'),
  ('19585', '19', 'Cauca', 'Purace', 'PURACE', 'CAUCA'),
  ('19622', '19', 'Cauca', 'Rosas', 'ROSAS', 'CAUCA'),
  ('19693', '19', 'Cauca', 'San Sebastian', 'SAN SEBASTIAN', 'CAUCA'),
  ('19698', '19', 'Cauca', 'Santander de Quilichao', 'SANTANDER DE QUILICHAO', 'CAUCA'),
  ('19701', '19', 'Cauca', 'Santa Rosa', 'SANTA ROSA', 'CAUCA'),
  ('19743', '19', 'Cauca', 'Silvia', 'SILVIA', 'CAUCA'),
  ('19760', '19', 'Cauca', 'Sotara', 'SOTARA', 'CAUCA'),
  ('19780', '19', 'Cauca', 'Suarez', 'SUAREZ', 'CAUCA'),
  ('19785', '19', 'Cauca', 'Sucre', 'SUCRE', 'CAUCA'),
  ('19807', '19', 'Cauca', 'Timbio', 'TIMBIO', 'CAUCA'),
  ('19809', '19', 'Cauca', 'Timbiqui', 'TIMBIQUI', 'CAUCA'),
  ('19821', '19', 'Cauca', 'Toribio', 'TORIBIO', 'CAUCA'),
  ('19824', '19', 'Cauca', 'Totoro', 'TOTORO', 'CAUCA'),
  ('19845', '19', 'Cauca', 'Villa Rica', 'VILLA RICA', 'CAUCA'),
  ('20001', '20', 'Cesar', 'Valledupar', 'VALLEDUPAR', 'CESAR'),
  ('20011', '20', 'Cesar', 'Aguachica', 'AGUACHICA', 'CESAR'),
  ('20013', '20', 'Cesar', 'Agustin Codazzi', 'AGUSTIN CODAZZI', 'CESAR'),
  ('20032', '20', 'Cesar', 'Astrea', 'ASTREA', 'CESAR'),
  ('20045', '20', 'Cesar', 'Becerril', 'BECERRIL', 'CESAR'),
  ('20060', '20', 'Cesar', 'Bosconia', 'BOSCONIA', 'CESAR'),
  ('20175', '20', 'Cesar', 'Chimichagua', 'CHIMICHAGUA', 'CESAR'),
  ('20178', '20', 'Cesar', 'Chiriguana', 'CHIRIGUANA', 'CESAR'),
  ('20228', '20', 'Cesar', 'Curumani', 'CURUMANI', 'CESAR'),
  ('20238', '20', 'Cesar', 'El Copey', 'EL COPEY', 'CESAR'),
  ('20250', '20', 'Cesar', 'El Paso', 'EL PASO', 'CESAR'),
  ('20295', '20', 'Cesar', 'Gamarra', 'GAMARRA', 'CESAR'),
  ('20310', '20', 'Cesar', 'Gonzalez', 'GONZALEZ', 'CESAR'),
  ('20383', '20', 'Cesar', 'La Gloria', 'LA GLORIA', 'CESAR'),
  ('20400', '20', 'Cesar', 'La Jagua de Ibirico', 'LA JAGUA DE IBIRICO', 'CESAR'),
  ('20443', '20', 'Cesar', 'Manaure Balcon del Cesar', 'MANAURE BALCON DEL CESAR', 'CESAR'),
  ('20517', '20', 'Cesar', 'Pailitas', 'PAILITAS', 'CESAR'),
  ('20550', '20', 'Cesar', 'Pelaya', 'PELAYA', 'CESAR'),
  ('20570', '20', 'Cesar', 'Pueblo Bello', 'PUEBLO BELLO', 'CESAR'),
  ('20614', '20', 'Cesar', 'Rio de Oro', 'RIO DE ORO', 'CESAR'),
  ('20621', '20', 'Cesar', 'La Paz', 'LA PAZ', 'CESAR'),
  ('20710', '20', 'Cesar', 'San Alberto', 'SAN ALBERTO', 'CESAR'),
  ('20750', '20', 'Cesar', 'San Diego', 'SAN DIEGO', 'CESAR'),
  ('20770', '20', 'Cesar', 'San Martin', 'SAN MARTIN', 'CESAR'),
  ('20787', '20', 'Cesar', 'Tamalameque', 'TAMALAMEQUE', 'CESAR'),
  ('27001', '27', 'Choco', 'Quibdo', 'QUIBDO', 'CHOCO'),
  ('27006', '27', 'Choco', 'Acandi', 'ACANDI', 'CHOCO'),
  ('27025', '27', 'Choco', 'Alto Baudo', 'ALTO BAUDO', 'CHOCO'),
  ('27050', '27', 'Choco', 'Atrato', 'ATRATO', 'CHOCO'),
  ('27073', '27', 'Choco', 'Bagado', 'BAGADO', 'CHOCO'),
  ('27075', '27', 'Choco', 'Bahia Solano', 'BAHIA SOLANO', 'CHOCO'),
  ('27077', '27', 'Choco', 'Bajo Baudo', 'BAJO BAUDO', 'CHOCO'),
  ('27099', '27', 'Choco', 'Bojaya', 'BOJAYA', 'CHOCO'),
  ('27135', '27', 'Choco', 'El Canton del San Pablo', 'EL CANTON DEL SAN PABLO', 'CHOCO'),
  ('27150', '27', 'Choco', 'Carmen del Darien', 'CARMEN DEL DARIEN', 'CHOCO'),
  ('27160', '27', 'Choco', 'Certegui', 'CERTEGUI', 'CHOCO'),
  ('27205', '27', 'Choco', 'Condoto', 'CONDOTO', 'CHOCO'),
  ('27245', '27', 'Choco', 'El Carmen de Atrato', 'EL CARMEN DE ATRATO', 'CHOCO'),
  ('27250', '27', 'Choco', 'El Litoral del San Juan', 'EL LITORAL DEL SAN JUAN', 'CHOCO'),
  ('27361', '27', 'Choco', 'Istmina', 'ISTMINA', 'CHOCO'),
  ('27372', '27', 'Choco', 'Jurado', 'JURADO', 'CHOCO'),
  ('27413', '27', 'Choco', 'Lloro', 'LLORO', 'CHOCO'),
  ('27425', '27', 'Choco', 'Medio Atrato', 'MEDIO ATRATO', 'CHOCO'),
  ('27430', '27', 'Choco', 'Medio Baudo', 'MEDIO BAUDO', 'CHOCO'),
  ('27450', '27', 'Choco', 'Medio San Juan', 'MEDIO SAN JUAN', 'CHOCO'),
  ('27491', '27', 'Choco', 'Novita', 'NOVITA', 'CHOCO'),
  ('27495', '27', 'Choco', 'Nuqui', 'NUQUI', 'CHOCO'),
  ('27580', '27', 'Choco', 'Rio Iro', 'RIO IRO', 'CHOCO'),
  ('27600', '27', 'Choco', 'Rio Quito', 'RIO QUITO', 'CHOCO'),
  ('27615', '27', 'Choco', 'Riosucio', 'RIOSUCIO', 'CHOCO'),
  ('27660', '27', 'Choco', 'San Jose del Palmar', 'SAN JOSE DEL PALMAR', 'CHOCO'),
  ('27745', '27', 'Choco', 'Sipi', 'SIPI', 'CHOCO'),
  ('27787', '27', 'Choco', 'Tado', 'TADO', 'CHOCO'),
  ('27800', '27', 'Choco', 'Unguia', 'UNGUIA', 'CHOCO'),
  ('27810', '27', 'Choco', 'Union Panamericana', 'UNION PANAMERICANA', 'CHOCO'),
  ('23001', '23', 'Cordoba', 'Monteria', 'MONTERIA', 'CORDOBA'),
  ('23068', '23', 'Cordoba', 'Ayapel', 'AYAPEL', 'CORDOBA'),
  ('23079', '23', 'Cordoba', 'Buenavista', 'BUENAVISTA', 'CORDOBA'),
  ('23090', '23', 'Cordoba', 'Canalete', 'CANALETE', 'CORDOBA'),
  ('23162', '23', 'Cordoba', 'Cerete', 'CERETE', 'CORDOBA');

INSERT INTO dane_municipalities (dane_code, department_code, department_name, municipality_name, municipality_name_normalized, department_name_normalized) VALUES
  ('23168', '23', 'Cordoba', 'Chima', 'CHIMA', 'CORDOBA'),
  ('23182', '23', 'Cordoba', 'Chinu', 'CHINU', 'CORDOBA'),
  ('23189', '23', 'Cordoba', 'Cienaga de Oro', 'CIENAGA DE ORO', 'CORDOBA'),
  ('23300', '23', 'Cordoba', 'Cotorra', 'COTORRA', 'CORDOBA'),
  ('23350', '23', 'Cordoba', 'La Apartada', 'LA APARTADA', 'CORDOBA'),
  ('23417', '23', 'Cordoba', 'Lorica', 'LORICA', 'CORDOBA'),
  ('23419', '23', 'Cordoba', 'Los Cordobas', 'LOS CORDOBAS', 'CORDOBA'),
  ('23464', '23', 'Cordoba', 'Momil', 'MOMIL', 'CORDOBA'),
  ('23466', '23', 'Cordoba', 'Montelibano', 'MONTELIBANO', 'CORDOBA'),
  ('23500', '23', 'Cordoba', 'Moñitos', 'MONITOS', 'CORDOBA'),
  ('23555', '23', 'Cordoba', 'Planeta Rica', 'PLANETA RICA', 'CORDOBA'),
  ('23570', '23', 'Cordoba', 'Pueblo Nuevo', 'PUEBLO NUEVO', 'CORDOBA'),
  ('23574', '23', 'Cordoba', 'Puerto Escondido', 'PUERTO ESCONDIDO', 'CORDOBA'),
  ('23580', '23', 'Cordoba', 'Puerto Libertador', 'PUERTO LIBERTADOR', 'CORDOBA'),
  ('23586', '23', 'Cordoba', 'Purisima de la Concepcion', 'PURISIMA DE LA CONCEPCION', 'CORDOBA'),
  ('23660', '23', 'Cordoba', 'Sahagun', 'SAHAGUN', 'CORDOBA'),
  ('23670', '23', 'Cordoba', 'San Andres de Sotavento', 'SAN ANDRES DE SOTAVENTO', 'CORDOBA'),
  ('23672', '23', 'Cordoba', 'San Antero', 'SAN ANTERO', 'CORDOBA'),
  ('23675', '23', 'Cordoba', 'San Bernardo del Viento', 'SAN BERNARDO DEL VIENTO', 'CORDOBA'),
  ('23678', '23', 'Cordoba', 'San Carlos', 'SAN CARLOS', 'CORDOBA'),
  ('23682', '23', 'Cordoba', 'San Jose de Ure', 'SAN JOSE DE URE', 'CORDOBA'),
  ('23686', '23', 'Cordoba', 'San Pelayo', 'SAN PELAYO', 'CORDOBA'),
  ('23807', '23', 'Cordoba', 'Tierra Alta', 'TIERRA ALTA', 'CORDOBA'),
  ('23815', '23', 'Cordoba', 'Tuchin', 'TUCHIN', 'CORDOBA'),
  ('23855', '23', 'Cordoba', 'Valencia', 'VALENCIA', 'CORDOBA'),
  ('25001', '25', 'Cundinamarca', 'Agua de Dios', 'AGUA DE DIOS', 'CUNDINAMARCA'),
  ('25019', '25', 'Cundinamarca', 'Alban', 'ALBAN', 'CUNDINAMARCA'),
  ('25035', '25', 'Cundinamarca', 'Anapoima', 'ANAPOIMA', 'CUNDINAMARCA'),
  ('25040', '25', 'Cundinamarca', 'Anolaima', 'ANOLAIMA', 'CUNDINAMARCA'),
  ('25053', '25', 'Cundinamarca', 'Arbelaez', 'ARBELAEZ', 'CUNDINAMARCA'),
  ('25086', '25', 'Cundinamarca', 'Beltran', 'BELTRAN', 'CUNDINAMARCA'),
  ('25095', '25', 'Cundinamarca', 'Bituima', 'BITUIMA', 'CUNDINAMARCA'),
  ('25099', '25', 'Cundinamarca', 'Bojaca', 'BOJACA', 'CUNDINAMARCA'),
  ('25120', '25', 'Cundinamarca', 'Cabrera', 'CABRERA', 'CUNDINAMARCA'),
  ('25123', '25', 'Cundinamarca', 'Cachipay', 'CACHIPAY', 'CUNDINAMARCA'),
  ('25126', '25', 'Cundinamarca', 'Cajica', 'CAJICA', 'CUNDINAMARCA'),
  ('25148', '25', 'Cundinamarca', 'Caparrapi', 'CAPARRAPI', 'CUNDINAMARCA'),
  ('25151', '25', 'Cundinamarca', 'Caqueza', 'CAQUEZA', 'CUNDINAMARCA'),
  ('25154', '25', 'Cundinamarca', 'Carmen de Carupa', 'CARMEN DE CARUPA', 'CUNDINAMARCA'),
  ('25168', '25', 'Cundinamarca', 'Chaguani', 'CHAGUANI', 'CUNDINAMARCA'),
  ('25175', '25', 'Cundinamarca', 'Chia', 'CHIA', 'CUNDINAMARCA'),
  ('25178', '25', 'Cundinamarca', 'Chipaque', 'CHIPAQUE', 'CUNDINAMARCA'),
  ('25181', '25', 'Cundinamarca', 'Choachi', 'CHOACHI', 'CUNDINAMARCA'),
  ('25183', '25', 'Cundinamarca', 'Choconta', 'CHOCONTA', 'CUNDINAMARCA'),
  ('25200', '25', 'Cundinamarca', 'Cogua', 'COGUA', 'CUNDINAMARCA'),
  ('25214', '25', 'Cundinamarca', 'Cota', 'COTA', 'CUNDINAMARCA'),
  ('25224', '25', 'Cundinamarca', 'Cucunuba', 'CUCUNUBA', 'CUNDINAMARCA'),
  ('25245', '25', 'Cundinamarca', 'El Colegio', 'EL COLEGIO', 'CUNDINAMARCA'),
  ('25258', '25', 'Cundinamarca', 'El Penon', 'EL PENON', 'CUNDINAMARCA'),
  ('25260', '25', 'Cundinamarca', 'El Rosal', 'EL ROSAL', 'CUNDINAMARCA'),
  ('25269', '25', 'Cundinamarca', 'Facatativa', 'FACATATIVA', 'CUNDINAMARCA'),
  ('25279', '25', 'Cundinamarca', 'Fomeque', 'FOMEQUE', 'CUNDINAMARCA'),
  ('25281', '25', 'Cundinamarca', 'Fosca', 'FOSCA', 'CUNDINAMARCA'),
  ('25286', '25', 'Cundinamarca', 'Funza', 'FUNZA', 'CUNDINAMARCA'),
  ('25288', '25', 'Cundinamarca', 'Fuquene', 'FUQUENE', 'CUNDINAMARCA'),
  ('25290', '25', 'Cundinamarca', 'Fusagasuga', 'FUSAGASUGA', 'CUNDINAMARCA'),
  ('25293', '25', 'Cundinamarca', 'Gachala', 'GACHALA', 'CUNDINAMARCA'),
  ('25295', '25', 'Cundinamarca', 'Gachancipa', 'GACHANCIPA', 'CUNDINAMARCA'),
  ('25297', '25', 'Cundinamarca', 'Gacheta', 'GACHETA', 'CUNDINAMARCA'),
  ('25299', '25', 'Cundinamarca', 'Gama', 'GAMA', 'CUNDINAMARCA'),
  ('25307', '25', 'Cundinamarca', 'Girardot', 'GIRARDOT', 'CUNDINAMARCA'),
  ('25312', '25', 'Cundinamarca', 'Granada', 'GRANADA', 'CUNDINAMARCA'),
  ('25317', '25', 'Cundinamarca', 'Guacheta', 'GUACHETA', 'CUNDINAMARCA'),
  ('25320', '25', 'Cundinamarca', 'Guaduas', 'GUADUAS', 'CUNDINAMARCA'),
  ('25322', '25', 'Cundinamarca', 'Guasca', 'GUASCA', 'CUNDINAMARCA'),
  ('25324', '25', 'Cundinamarca', 'Guataqui', 'GUATAQUI', 'CUNDINAMARCA'),
  ('25326', '25', 'Cundinamarca', 'Guatavita', 'GUATAVITA', 'CUNDINAMARCA'),
  ('25328', '25', 'Cundinamarca', 'Guayabal de Siquima', 'GUAYABAL DE SIQUIMA', 'CUNDINAMARCA'),
  ('25335', '25', 'Cundinamarca', 'Guayabetal', 'GUAYABETAL', 'CUNDINAMARCA'),
  ('25339', '25', 'Cundinamarca', 'Gutierrez', 'GUTIERREZ', 'CUNDINAMARCA'),
  ('25368', '25', 'Cundinamarca', 'Jerusalen', 'JERUSALEN', 'CUNDINAMARCA'),
  ('25372', '25', 'Cundinamarca', 'Junin', 'JUNIN', 'CUNDINAMARCA'),
  ('25377', '25', 'Cundinamarca', 'La Calera', 'LA CALERA', 'CUNDINAMARCA'),
  ('25386', '25', 'Cundinamarca', 'La Mesa', 'LA MESA', 'CUNDINAMARCA'),
  ('25394', '25', 'Cundinamarca', 'La Palma', 'LA PALMA', 'CUNDINAMARCA'),
  ('25398', '25', 'Cundinamarca', 'La Pena', 'LA PENA', 'CUNDINAMARCA'),
  ('25402', '25', 'Cundinamarca', 'La Vega', 'LA VEGA', 'CUNDINAMARCA'),
  ('25407', '25', 'Cundinamarca', 'Lenguazaque', 'LENGUAZAQUE', 'CUNDINAMARCA'),
  ('25426', '25', 'Cundinamarca', 'Macheta', 'MACHETA', 'CUNDINAMARCA'),
  ('25430', '25', 'Cundinamarca', 'Madrid', 'MADRID', 'CUNDINAMARCA'),
  ('25436', '25', 'Cundinamarca', 'Manta', 'MANTA', 'CUNDINAMARCA'),
  ('25438', '25', 'Cundinamarca', 'Medina', 'MEDINA', 'CUNDINAMARCA'),
  ('25473', '25', 'Cundinamarca', 'Mosquera', 'MOSQUERA', 'CUNDINAMARCA'),
  ('25483', '25', 'Cundinamarca', 'Narino', 'NARINO', 'CUNDINAMARCA'),
  ('25486', '25', 'Cundinamarca', 'Nemocon', 'NEMOCON', 'CUNDINAMARCA'),
  ('25488', '25', 'Cundinamarca', 'Nilo', 'NILO', 'CUNDINAMARCA'),
  ('25489', '25', 'Cundinamarca', 'Nimaima', 'NIMAIMA', 'CUNDINAMARCA'),
  ('25491', '25', 'Cundinamarca', 'Nocaima', 'NOCAIMA', 'CUNDINAMARCA'),
  ('25506', '25', 'Cundinamarca', 'Venecia', 'VENECIA', 'CUNDINAMARCA'),
  ('25513', '25', 'Cundinamarca', 'Pacho', 'PACHO', 'CUNDINAMARCA'),
  ('25518', '25', 'Cundinamarca', 'Paime', 'PAIME', 'CUNDINAMARCA'),
  ('25524', '25', 'Cundinamarca', 'Pandi', 'PANDI', 'CUNDINAMARCA'),
  ('25530', '25', 'Cundinamarca', 'Paratebueno', 'PARATEBUENO', 'CUNDINAMARCA'),
  ('25535', '25', 'Cundinamarca', 'Pasca', 'PASCA', 'CUNDINAMARCA'),
  ('25572', '25', 'Cundinamarca', 'Puerto Salgar', 'PUERTO SALGAR', 'CUNDINAMARCA'),
  ('25580', '25', 'Cundinamarca', 'Puli', 'PULI', 'CUNDINAMARCA'),
  ('25592', '25', 'Cundinamarca', 'Quebradanegra', 'QUEBRADANEGRA', 'CUNDINAMARCA'),
  ('25594', '25', 'Cundinamarca', 'Quetame', 'QUETAME', 'CUNDINAMARCA'),
  ('25596', '25', 'Cundinamarca', 'Quipile', 'QUIPILE', 'CUNDINAMARCA'),
  ('25599', '25', 'Cundinamarca', 'Apulo', 'APULO', 'CUNDINAMARCA');

INSERT INTO dane_municipalities (dane_code, department_code, department_name, municipality_name, municipality_name_normalized, department_name_normalized) VALUES
  ('25612', '25', 'Cundinamarca', 'Ricaurte', 'RICAURTE', 'CUNDINAMARCA'),
  ('25645', '25', 'Cundinamarca', 'San Antonio del Tequendama', 'SAN ANTONIO DEL TEQUENDAMA', 'CUNDINAMARCA'),
  ('25649', '25', 'Cundinamarca', 'San Bernardo', 'SAN BERNARDO', 'CUNDINAMARCA'),
  ('25653', '25', 'Cundinamarca', 'San Cayetano', 'SAN CAYETANO', 'CUNDINAMARCA'),
  ('25658', '25', 'Cundinamarca', 'San Francisco', 'SAN FRANCISCO', 'CUNDINAMARCA'),
  ('25662', '25', 'Cundinamarca', 'San Juan de Rioseco', 'SAN JUAN DE RIOSECO', 'CUNDINAMARCA'),
  ('25718', '25', 'Cundinamarca', 'Sasaima', 'SASAIMA', 'CUNDINAMARCA'),
  ('25736', '25', 'Cundinamarca', 'Sesquile', 'SESQUILE', 'CUNDINAMARCA'),
  ('25740', '25', 'Cundinamarca', 'Sibate', 'SIBATE', 'CUNDINAMARCA'),
  ('25743', '25', 'Cundinamarca', 'Silvania', 'SILVANIA', 'CUNDINAMARCA'),
  ('25745', '25', 'Cundinamarca', 'Simijaca', 'SIMIJACA', 'CUNDINAMARCA'),
  ('25754', '25', 'Cundinamarca', 'Soacha', 'SOACHA', 'CUNDINAMARCA'),
  ('25758', '25', 'Cundinamarca', 'Sopo', 'SOPO', 'CUNDINAMARCA'),
  ('25769', '25', 'Cundinamarca', 'Subachoque', 'SUBACHOQUE', 'CUNDINAMARCA'),
  ('25772', '25', 'Cundinamarca', 'Suesca', 'SUESCA', 'CUNDINAMARCA'),
  ('25777', '25', 'Cundinamarca', 'Supata', 'SUPATA', 'CUNDINAMARCA'),
  ('25779', '25', 'Cundinamarca', 'Susa', 'SUSA', 'CUNDINAMARCA'),
  ('25781', '25', 'Cundinamarca', 'Sutatausa', 'SUTATAUSA', 'CUNDINAMARCA'),
  ('25785', '25', 'Cundinamarca', 'Tabio', 'TABIO', 'CUNDINAMARCA'),
  ('25793', '25', 'Cundinamarca', 'Tausa', 'TAUSA', 'CUNDINAMARCA'),
  ('25797', '25', 'Cundinamarca', 'Tena', 'TENA', 'CUNDINAMARCA'),
  ('25799', '25', 'Cundinamarca', 'Tenjo', 'TENJO', 'CUNDINAMARCA'),
  ('25805', '25', 'Cundinamarca', 'Tibacuy', 'TIBACUY', 'CUNDINAMARCA'),
  ('25807', '25', 'Cundinamarca', 'Tibirita', 'TIBIRITA', 'CUNDINAMARCA'),
  ('25815', '25', 'Cundinamarca', 'Tocaima', 'TOCAIMA', 'CUNDINAMARCA'),
  ('25817', '25', 'Cundinamarca', 'Tocancipa', 'TOCANCIPA', 'CUNDINAMARCA'),
  ('25823', '25', 'Cundinamarca', 'Topaipi', 'TOPAIPI', 'CUNDINAMARCA'),
  ('25839', '25', 'Cundinamarca', 'Ubala', 'UBALA', 'CUNDINAMARCA'),
  ('25841', '25', 'Cundinamarca', 'Ubaque', 'UBAQUE', 'CUNDINAMARCA'),
  ('25843', '25', 'Cundinamarca', 'Villa de San Diego de Ubate', 'VILLA DE SAN DIEGO DE UBATE', 'CUNDINAMARCA'),
  ('25845', '25', 'Cundinamarca', 'Une', 'UNE', 'CUNDINAMARCA'),
  ('25851', '25', 'Cundinamarca', 'Utica', 'UTICA', 'CUNDINAMARCA'),
  ('25862', '25', 'Cundinamarca', 'Vergara', 'VERGARA', 'CUNDINAMARCA'),
  ('25867', '25', 'Cundinamarca', 'Viani', 'VIANI', 'CUNDINAMARCA'),
  ('25871', '25', 'Cundinamarca', 'Villagomez', 'VILLAGOMEZ', 'CUNDINAMARCA'),
  ('25873', '25', 'Cundinamarca', 'Villapinzon', 'VILLAPINZON', 'CUNDINAMARCA'),
  ('25875', '25', 'Cundinamarca', 'Villeta', 'VILLETA', 'CUNDINAMARCA'),
  ('25878', '25', 'Cundinamarca', 'Viota', 'VIOTA', 'CUNDINAMARCA'),
  ('25885', '25', 'Cundinamarca', 'Yacopi', 'YACOPI', 'CUNDINAMARCA'),
  ('25898', '25', 'Cundinamarca', 'Zipacon', 'ZIPACON', 'CUNDINAMARCA'),
  ('25899', '25', 'Cundinamarca', 'Zipaquira', 'ZIPAQUIRA', 'CUNDINAMARCA'),
  ('94001', '94', 'Guainia', 'Inirida', 'INIRIDA', 'GUAINIA'),
  ('94343', '94', 'Guainia', 'Barranco Minas', 'BARRANCO MINAS', 'GUAINIA'),
  ('94663', '94', 'Guainia', 'Mapiripana', 'MAPIRIPANA', 'GUAINIA'),
  ('94883', '94', 'Guainia', 'San Felipe', 'SAN FELIPE', 'GUAINIA'),
  ('94884', '94', 'Guainia', 'Puerto Colombia', 'PUERTO COLOMBIA', 'GUAINIA'),
  ('94885', '94', 'Guainia', 'La Guadalupe', 'LA GUADALUPE', 'GUAINIA'),
  ('94886', '94', 'Guainia', 'Cacahual', 'CACAHUAL', 'GUAINIA'),
  ('94887', '94', 'Guainia', 'Pana Pana', 'PANA PANA', 'GUAINIA'),
  ('94888', '94', 'Guainia', 'Morichal', 'MORICHAL', 'GUAINIA'),
  ('95001', '95', 'Guaviare', 'San Jose del Guaviare', 'SAN JOSE DEL GUAVIARE', 'GUAVIARE'),
  ('95015', '95', 'Guaviare', 'Calamar', 'CALAMAR', 'GUAVIARE'),
  ('95025', '95', 'Guaviare', 'El Retorno', 'EL RETORNO', 'GUAVIARE'),
  ('95200', '95', 'Guaviare', 'Miraflores', 'MIRAFLORES', 'GUAVIARE'),
  ('41001', '41', 'Huila', 'Neiva', 'NEIVA', 'HUILA'),
  ('41006', '41', 'Huila', 'Acevedo', 'ACEVEDO', 'HUILA'),
  ('41013', '41', 'Huila', 'Agrado', 'AGRADO', 'HUILA'),
  ('41016', '41', 'Huila', 'Aipe', 'AIPE', 'HUILA'),
  ('41020', '41', 'Huila', 'Algeciras', 'ALGECIRAS', 'HUILA'),
  ('41026', '41', 'Huila', 'Altamira', 'ALTAMIRA', 'HUILA'),
  ('41078', '41', 'Huila', 'Baraya', 'BARAYA', 'HUILA'),
  ('41132', '41', 'Huila', 'Campoalegre', 'CAMPOALEGRE', 'HUILA'),
  ('41206', '41', 'Huila', 'Colombia', 'COLOMBIA', 'HUILA'),
  ('41244', '41', 'Huila', 'Elias', 'ELIAS', 'HUILA'),
  ('41298', '41', 'Huila', 'Garzon', 'GARZON', 'HUILA'),
  ('41306', '41', 'Huila', 'Gigante', 'GIGANTE', 'HUILA'),
  ('41319', '41', 'Huila', 'Guadalupe', 'GUADALUPE', 'HUILA'),
  ('41349', '41', 'Huila', 'Hobo', 'HOBO', 'HUILA'),
  ('41357', '41', 'Huila', 'Iquira', 'IQUIRA', 'HUILA'),
  ('41359', '41', 'Huila', 'Isnos', 'ISNOS', 'HUILA'),
  ('41378', '41', 'Huila', 'La Argentina', 'LA ARGENTINA', 'HUILA'),
  ('41396', '41', 'Huila', 'La Plata', 'LA PLATA', 'HUILA'),
  ('41483', '41', 'Huila', 'Nataga', 'NATAGA', 'HUILA'),
  ('41503', '41', 'Huila', 'Oporapa', 'OPORAPA', 'HUILA'),
  ('41518', '41', 'Huila', 'Paicol', 'PAICOL', 'HUILA'),
  ('41524', '41', 'Huila', 'Palermo', 'PALERMO', 'HUILA'),
  ('41530', '41', 'Huila', 'Palestina', 'PALESTINA', 'HUILA'),
  ('41548', '41', 'Huila', 'Pital', 'PITAL', 'HUILA'),
  ('41551', '41', 'Huila', 'Pitalito', 'PITALITO', 'HUILA'),
  ('41615', '41', 'Huila', 'Rivera', 'RIVERA', 'HUILA'),
  ('41660', '41', 'Huila', 'Saladoblanco', 'SALADOBLANCO', 'HUILA'),
  ('41668', '41', 'Huila', 'San Agustin', 'SAN AGUSTIN', 'HUILA'),
  ('41676', '41', 'Huila', 'Santa Maria', 'SANTA MARIA', 'HUILA'),
  ('41770', '41', 'Huila', 'Suaza', 'SUAZA', 'HUILA'),
  ('41791', '41', 'Huila', 'Tarqui', 'TARQUI', 'HUILA'),
  ('41797', '41', 'Huila', 'Tesalia', 'TESALIA', 'HUILA'),
  ('41799', '41', 'Huila', 'Tello', 'TELLO', 'HUILA'),
  ('41801', '41', 'Huila', 'Teruel', 'TERUEL', 'HUILA'),
  ('41807', '41', 'Huila', 'Timana', 'TIMANA', 'HUILA'),
  ('41872', '41', 'Huila', 'Villavieja', 'VILLAVIEJA', 'HUILA'),
  ('41885', '41', 'Huila', 'Yaguara', 'YAGUARA', 'HUILA'),
  ('44001', '44', 'La Guajira', 'Riohacha', 'RIOHACHA', 'LA GUAJIRA'),
  ('44035', '44', 'La Guajira', 'Albania', 'ALBANIA', 'LA GUAJIRA'),
  ('44078', '44', 'La Guajira', 'Barrancas', 'BARRANCAS', 'LA GUAJIRA'),
  ('44090', '44', 'La Guajira', 'Dibulla', 'DIBULLA', 'LA GUAJIRA'),
  ('44098', '44', 'La Guajira', 'Distraccion', 'DISTRACCION', 'LA GUAJIRA'),
  ('44110', '44', 'La Guajira', 'El Molino', 'EL MOLINO', 'LA GUAJIRA'),
  ('44279', '44', 'La Guajira', 'Fonseca', 'FONSECA', 'LA GUAJIRA'),
  ('44378', '44', 'La Guajira', 'Hatonuevo', 'HATONUEVO', 'LA GUAJIRA'),
  ('44420', '44', 'La Guajira', 'La Jagua del Pilar', 'LA JAGUA DEL PILAR', 'LA GUAJIRA');

INSERT INTO dane_municipalities (dane_code, department_code, department_name, municipality_name, municipality_name_normalized, department_name_normalized) VALUES
  ('44430', '44', 'La Guajira', 'Maicao', 'MAICAO', 'LA GUAJIRA'),
  ('44560', '44', 'La Guajira', 'Manaure', 'MANAURE', 'LA GUAJIRA'),
  ('44650', '44', 'La Guajira', 'San Juan del Cesar', 'SAN JUAN DEL CESAR', 'LA GUAJIRA'),
  ('44847', '44', 'La Guajira', 'Uribia', 'URIBIA', 'LA GUAJIRA'),
  ('44855', '44', 'La Guajira', 'Urumita', 'URUMITA', 'LA GUAJIRA'),
  ('44874', '44', 'La Guajira', 'Villanueva', 'VILLANUEVA', 'LA GUAJIRA'),
  ('47001', '47', 'Magdalena', 'Santa Marta', 'SANTA MARTA', 'MAGDALENA'),
  ('47030', '47', 'Magdalena', 'Algarrobo', 'ALGARROBO', 'MAGDALENA'),
  ('47053', '47', 'Magdalena', 'Aracataca', 'ARACATACA', 'MAGDALENA'),
  ('47058', '47', 'Magdalena', 'Ariguani', 'ARIGUANI', 'MAGDALENA'),
  ('47161', '47', 'Magdalena', 'Cerro de San Antonio', 'CERRO DE SAN ANTONIO', 'MAGDALENA'),
  ('47170', '47', 'Magdalena', 'Chibolo', 'CHIBOLO', 'MAGDALENA'),
  ('47189', '47', 'Magdalena', 'Cienaga', 'CIENAGA', 'MAGDALENA'),
  ('47205', '47', 'Magdalena', 'Concordia', 'CONCORDIA', 'MAGDALENA'),
  ('47245', '47', 'Magdalena', 'El Banco', 'EL BANCO', 'MAGDALENA'),
  ('47258', '47', 'Magdalena', 'El Pinon', 'EL PINON', 'MAGDALENA'),
  ('47268', '47', 'Magdalena', 'El Reten', 'EL RETEN', 'MAGDALENA'),
  ('47288', '47', 'Magdalena', 'Fundacion', 'FUNDACION', 'MAGDALENA'),
  ('47318', '47', 'Magdalena', 'Guamal', 'GUAMAL', 'MAGDALENA'),
  ('47460', '47', 'Magdalena', 'Nueva Granada', 'NUEVA GRANADA', 'MAGDALENA'),
  ('47541', '47', 'Magdalena', 'Pedraza', 'PEDRAZA', 'MAGDALENA'),
  ('47545', '47', 'Magdalena', 'Pijiño del Carmen', 'PIJINO DEL CARMEN', 'MAGDALENA'),
  ('47551', '47', 'Magdalena', 'Pivijay', 'PIVIJAY', 'MAGDALENA'),
  ('47555', '47', 'Magdalena', 'Plato', 'PLATO', 'MAGDALENA'),
  ('47570', '47', 'Magdalena', 'Puebloviejo', 'PUEBLOVIEJO', 'MAGDALENA'),
  ('47605', '47', 'Magdalena', 'Remolino', 'REMOLINO', 'MAGDALENA'),
  ('47660', '47', 'Magdalena', 'Sabanas de San Angel', 'SABANAS DE SAN ANGEL', 'MAGDALENA'),
  ('47675', '47', 'Magdalena', 'Salamina', 'SALAMINA', 'MAGDALENA'),
  ('47692', '47', 'Magdalena', 'San Sebastian de Buenavista', 'SAN SEBASTIAN DE BUENAVISTA', 'MAGDALENA'),
  ('47703', '47', 'Magdalena', 'San Zenon', 'SAN ZENON', 'MAGDALENA'),
  ('47707', '47', 'Magdalena', 'Santa Ana', 'SANTA ANA', 'MAGDALENA'),
  ('47720', '47', 'Magdalena', 'Santa Barbara de Pinto', 'SANTA BARBARA DE PINTO', 'MAGDALENA'),
  ('47745', '47', 'Magdalena', 'Sitio Nuevo', 'SITIO NUEVO', 'MAGDALENA'),
  ('47798', '47', 'Magdalena', 'Tenerife', 'TENERIFE', 'MAGDALENA'),
  ('47960', '47', 'Magdalena', 'Zapayan', 'ZAPAYAN', 'MAGDALENA'),
  ('47980', '47', 'Magdalena', 'Zona Bananera', 'ZONA BANANERA', 'MAGDALENA'),
  ('50001', '50', 'Meta', 'Villavicencio', 'VILLAVICENCIO', 'META'),
  ('50006', '50', 'Meta', 'Acacias', 'ACACIAS', 'META'),
  ('50110', '50', 'Meta', 'Barranca de Upia', 'BARRANCA DE UPIA', 'META'),
  ('50124', '50', 'Meta', 'Cabuyaro', 'CABUYARO', 'META'),
  ('50150', '50', 'Meta', 'Castilla la Nueva', 'CASTILLA LA NUEVA', 'META'),
  ('50223', '50', 'Meta', 'Cubarral', 'CUBARRAL', 'META'),
  ('50226', '50', 'Meta', 'Cumaral', 'CUMARAL', 'META'),
  ('50245', '50', 'Meta', 'El Calvario', 'EL CALVARIO', 'META'),
  ('50251', '50', 'Meta', 'El Castillo', 'EL CASTILLO', 'META'),
  ('50270', '50', 'Meta', 'El Dorado', 'EL DORADO', 'META'),
  ('50287', '50', 'Meta', 'Fuente de Oro', 'FUENTE DE ORO', 'META'),
  ('50313', '50', 'Meta', 'Granada', 'GRANADA', 'META'),
  ('50318', '50', 'Meta', 'Guamal', 'GUAMAL', 'META'),
  ('50325', '50', 'Meta', 'Mapiripan', 'MAPIRIPAN', 'META'),
  ('50330', '50', 'Meta', 'Mesetas', 'MESETAS', 'META'),
  ('50350', '50', 'Meta', 'La Macarena', 'LA MACARENA', 'META'),
  ('50370', '50', 'Meta', 'Uribe', 'URIBE', 'META'),
  ('50400', '50', 'Meta', 'Lejanias', 'LEJANIAS', 'META'),
  ('50450', '50', 'Meta', 'Puerto Concordia', 'PUERTO CONCORDIA', 'META'),
  ('50568', '50', 'Meta', 'Puerto Gaitan', 'PUERTO GAITAN', 'META'),
  ('50573', '50', 'Meta', 'Puerto Lopez', 'PUERTO LOPEZ', 'META'),
  ('50577', '50', 'Meta', 'Puerto Lleras', 'PUERTO LLERAS', 'META'),
  ('50590', '50', 'Meta', 'Puerto Rico', 'PUERTO RICO', 'META'),
  ('50606', '50', 'Meta', 'Restrepo', 'RESTREPO', 'META'),
  ('50680', '50', 'Meta', 'San Carlos de Guaroa', 'SAN CARLOS DE GUAROA', 'META'),
  ('50683', '50', 'Meta', 'San Juan de Arama', 'SAN JUAN DE ARAMA', 'META'),
  ('50686', '50', 'Meta', 'San Juanito', 'SAN JUANITO', 'META'),
  ('50689', '50', 'Meta', 'San Martin', 'SAN MARTIN', 'META'),
  ('50711', '50', 'Meta', 'Vista Hermosa', 'VISTA HERMOSA', 'META'),
  ('52001', '52', 'Narino', 'Pasto', 'PASTO', 'NARINO'),
  ('52019', '52', 'Narino', 'Alban', 'ALBAN', 'NARINO'),
  ('52022', '52', 'Narino', 'Aldana', 'ALDANA', 'NARINO'),
  ('52036', '52', 'Narino', 'Ancuya', 'ANCUYA', 'NARINO'),
  ('52051', '52', 'Narino', 'Arboleda', 'ARBOLEDA', 'NARINO'),
  ('52079', '52', 'Narino', 'Barbacoas', 'BARBACOAS', 'NARINO'),
  ('52083', '52', 'Narino', 'Belen', 'BELEN', 'NARINO'),
  ('52110', '52', 'Narino', 'Buesaco', 'BUESACO', 'NARINO'),
  ('52203', '52', 'Narino', 'Colon', 'COLON', 'NARINO'),
  ('52207', '52', 'Narino', 'Consaca', 'CONSACA', 'NARINO'),
  ('52210', '52', 'Narino', 'Contadero', 'CONTADERO', 'NARINO'),
  ('52215', '52', 'Narino', 'Cordoba', 'CORDOBA', 'NARINO'),
  ('52224', '52', 'Narino', 'Cuaspud', 'CUASPUD', 'NARINO'),
  ('52227', '52', 'Narino', 'Cumbal', 'CUMBAL', 'NARINO'),
  ('52233', '52', 'Narino', 'Cumbitara', 'CUMBITARA', 'NARINO'),
  ('52240', '52', 'Narino', 'Chachagui', 'CHACHAGUI', 'NARINO'),
  ('52250', '52', 'Narino', 'El Charco', 'EL CHARCO', 'NARINO'),
  ('52254', '52', 'Narino', 'El Penol', 'EL PENOL', 'NARINO'),
  ('52256', '52', 'Narino', 'El Rosario', 'EL ROSARIO', 'NARINO'),
  ('52258', '52', 'Narino', 'El Tablon de Gomez', 'EL TABLON DE GOMEZ', 'NARINO'),
  ('52260', '52', 'Narino', 'El Tambo', 'EL TAMBO', 'NARINO'),
  ('52287', '52', 'Narino', 'Funes', 'FUNES', 'NARINO'),
  ('52317', '52', 'Narino', 'Guachucal', 'GUACHUCAL', 'NARINO'),
  ('52320', '52', 'Narino', 'Guaitarilla', 'GUAITARILLA', 'NARINO'),
  ('52323', '52', 'Narino', 'Gualmatan', 'GUALMATAN', 'NARINO'),
  ('52352', '52', 'Narino', 'Iles', 'ILES', 'NARINO'),
  ('52354', '52', 'Narino', 'Imues', 'IMUES', 'NARINO'),
  ('52356', '52', 'Narino', 'Ipiales', 'IPIALES', 'NARINO'),
  ('52378', '52', 'Narino', 'La Cruz', 'LA CRUZ', 'NARINO'),
  ('52381', '52', 'Narino', 'La Florida', 'LA FLORIDA', 'NARINO'),
  ('52385', '52', 'Narino', 'La Llanada', 'LA LLANADA', 'NARINO'),
  ('52390', '52', 'Narino', 'La Tola', 'LA TOLA', 'NARINO'),
  ('52399', '52', 'Narino', 'La Union', 'LA UNION', 'NARINO'),
  ('52405', '52', 'Narino', 'Leiva', 'LEIVA', 'NARINO'),
  ('52411', '52', 'Narino', 'Linares', 'LINARES', 'NARINO');

INSERT INTO dane_municipalities (dane_code, department_code, department_name, municipality_name, municipality_name_normalized, department_name_normalized) VALUES
  ('52418', '52', 'Narino', 'Los Andes', 'LOS ANDES', 'NARINO'),
  ('52427', '52', 'Narino', 'Magui', 'MAGUI', 'NARINO'),
  ('52435', '52', 'Narino', 'Mallama', 'MALLAMA', 'NARINO'),
  ('52473', '52', 'Narino', 'Mosquera', 'MOSQUERA', 'NARINO'),
  ('52480', '52', 'Narino', 'Narino', 'NARINO', 'NARINO'),
  ('52490', '52', 'Narino', 'Olaya Herrera', 'OLAYA HERRERA', 'NARINO'),
  ('52506', '52', 'Narino', 'Ospina', 'OSPINA', 'NARINO'),
  ('52520', '52', 'Narino', 'Francisco Pizarro', 'FRANCISCO PIZARRO', 'NARINO'),
  ('52540', '52', 'Narino', 'Policarpa', 'POLICARPA', 'NARINO'),
  ('52560', '52', 'Narino', 'Potosi', 'POTOSI', 'NARINO'),
  ('52565', '52', 'Narino', 'Providencia', 'PROVIDENCIA', 'NARINO'),
  ('52573', '52', 'Narino', 'Puerres', 'PUERRES', 'NARINO'),
  ('52585', '52', 'Narino', 'Pupiales', 'PUPIALES', 'NARINO'),
  ('52612', '52', 'Narino', 'Ricaurte', 'RICAURTE', 'NARINO'),
  ('52621', '52', 'Narino', 'Roberto Payan', 'ROBERTO PAYAN', 'NARINO'),
  ('52678', '52', 'Narino', 'Samaniego', 'SAMANIEGO', 'NARINO'),
  ('52683', '52', 'Narino', 'Sandona', 'SANDONA', 'NARINO'),
  ('52685', '52', 'Narino', 'San Bernardo', 'SAN BERNARDO', 'NARINO'),
  ('52687', '52', 'Narino', 'San Lorenzo', 'SAN LORENZO', 'NARINO'),
  ('52693', '52', 'Narino', 'San Pablo', 'SAN PABLO', 'NARINO'),
  ('52694', '52', 'Narino', 'San Pedro de Cartago', 'SAN PEDRO DE CARTAGO', 'NARINO'),
  ('52696', '52', 'Narino', 'Santa Barbara', 'SANTA BARBARA', 'NARINO'),
  ('52699', '52', 'Narino', 'Santacruz', 'SANTACRUZ', 'NARINO'),
  ('52720', '52', 'Narino', 'Sapuyes', 'SAPUYES', 'NARINO'),
  ('52786', '52', 'Narino', 'Taminango', 'TAMINANGO', 'NARINO'),
  ('52788', '52', 'Narino', 'Tangua', 'TANGUA', 'NARINO'),
  ('52835', '52', 'Narino', 'San Andres de Tumaco', 'SAN ANDRES DE TUMACO', 'NARINO'),
  ('52838', '52', 'Narino', 'Tuquerres', 'TUQUERRES', 'NARINO'),
  ('52885', '52', 'Narino', 'Yacuanquer', 'YACUANQUER', 'NARINO'),
  ('54001', '54', 'Norte de Santander', 'Cucuta', 'CUCUTA', 'NORTE DE SANTANDER'),
  ('54003', '54', 'Norte de Santander', 'Abrego', 'ABREGO', 'NORTE DE SANTANDER'),
  ('54051', '54', 'Norte de Santander', 'Arboledas', 'ARBOLEDAS', 'NORTE DE SANTANDER'),
  ('54099', '54', 'Norte de Santander', 'Bochalema', 'BOCHALEMA', 'NORTE DE SANTANDER'),
  ('54109', '54', 'Norte de Santander', 'Bucarasica', 'BUCARASICA', 'NORTE DE SANTANDER'),
  ('54125', '54', 'Norte de Santander', 'Cachira', 'CACHIRA', 'NORTE DE SANTANDER'),
  ('54128', '54', 'Norte de Santander', 'Cacota', 'CACOTA', 'NORTE DE SANTANDER'),
  ('54172', '54', 'Norte de Santander', 'Chinacota', 'CHINACOTA', 'NORTE DE SANTANDER'),
  ('54174', '54', 'Norte de Santander', 'Chitaga', 'CHITAGA', 'NORTE DE SANTANDER'),
  ('54206', '54', 'Norte de Santander', 'Convencion', 'CONVENCION', 'NORTE DE SANTANDER'),
  ('54223', '54', 'Norte de Santander', 'Cucutilla', 'CUCUTILLA', 'NORTE DE SANTANDER'),
  ('54239', '54', 'Norte de Santander', 'Durania', 'DURANIA', 'NORTE DE SANTANDER'),
  ('54245', '54', 'Norte de Santander', 'El Carmen', 'EL CARMEN', 'NORTE DE SANTANDER'),
  ('54250', '54', 'Norte de Santander', 'El Tarra', 'EL TARRA', 'NORTE DE SANTANDER'),
  ('54261', '54', 'Norte de Santander', 'El Zulia', 'EL ZULIA', 'NORTE DE SANTANDER'),
  ('54313', '54', 'Norte de Santander', 'Gramalote', 'GRAMALOTE', 'NORTE DE SANTANDER'),
  ('54344', '54', 'Norte de Santander', 'Hacari', 'HACARI', 'NORTE DE SANTANDER'),
  ('54347', '54', 'Norte de Santander', 'Herran', 'HERRAN', 'NORTE DE SANTANDER'),
  ('54377', '54', 'Norte de Santander', 'Labateca', 'LABATECA', 'NORTE DE SANTANDER'),
  ('54385', '54', 'Norte de Santander', 'La Esperanza', 'LA ESPERANZA', 'NORTE DE SANTANDER'),
  ('54398', '54', 'Norte de Santander', 'La Playa de Belen', 'LA PLAYA DE BELEN', 'NORTE DE SANTANDER'),
  ('54405', '54', 'Norte de Santander', 'Los Patios', 'LOS PATIOS', 'NORTE DE SANTANDER'),
  ('54418', '54', 'Norte de Santander', 'Lourdes', 'LOURDES', 'NORTE DE SANTANDER'),
  ('54480', '54', 'Norte de Santander', 'Mutiscua', 'MUTISCUA', 'NORTE DE SANTANDER'),
  ('54498', '54', 'Norte de Santander', 'Ocana', 'OCANA', 'NORTE DE SANTANDER'),
  ('54518', '54', 'Norte de Santander', 'Pamplona', 'PAMPLONA', 'NORTE DE SANTANDER'),
  ('54520', '54', 'Norte de Santander', 'Pamplonita', 'PAMPLONITA', 'NORTE DE SANTANDER'),
  ('54553', '54', 'Norte de Santander', 'Puerto Santander', 'PUERTO SANTANDER', 'NORTE DE SANTANDER'),
  ('54599', '54', 'Norte de Santander', 'Ragonvalia', 'RAGONVALIA', 'NORTE DE SANTANDER'),
  ('54660', '54', 'Norte de Santander', 'Salazar', 'SALAZAR', 'NORTE DE SANTANDER'),
  ('54670', '54', 'Norte de Santander', 'San Calixto', 'SAN CALIXTO', 'NORTE DE SANTANDER'),
  ('54673', '54', 'Norte de Santander', 'San Cayetano', 'SAN CAYETANO', 'NORTE DE SANTANDER'),
  ('54680', '54', 'Norte de Santander', 'Santiago', 'SANTIAGO', 'NORTE DE SANTANDER'),
  ('54720', '54', 'Norte de Santander', 'Sardinata', 'SARDINATA', 'NORTE DE SANTANDER'),
  ('54743', '54', 'Norte de Santander', 'Silos', 'SILOS', 'NORTE DE SANTANDER'),
  ('54800', '54', 'Norte de Santander', 'Teorama', 'TEORAMA', 'NORTE DE SANTANDER'),
  ('54810', '54', 'Norte de Santander', 'Tibu', 'TIBU', 'NORTE DE SANTANDER'),
  ('54820', '54', 'Norte de Santander', 'Toledo', 'TOLEDO', 'NORTE DE SANTANDER'),
  ('54871', '54', 'Norte de Santander', 'Villa Caro', 'VILLA CARO', 'NORTE DE SANTANDER'),
  ('54874', '54', 'Norte de Santander', 'Villa del Rosario', 'VILLA DEL ROSARIO', 'NORTE DE SANTANDER'),
  ('86001', '86', 'Putumayo', 'Mocoa', 'MOCOA', 'PUTUMAYO'),
  ('86219', '86', 'Putumayo', 'Colon', 'COLON', 'PUTUMAYO'),
  ('86320', '86', 'Putumayo', 'Orito', 'ORITO', 'PUTUMAYO'),
  ('86568', '86', 'Putumayo', 'Puerto Asis', 'PUERTO ASIS', 'PUTUMAYO'),
  ('86569', '86', 'Putumayo', 'Puerto Caicedo', 'PUERTO CAICEDO', 'PUTUMAYO'),
  ('86571', '86', 'Putumayo', 'Puerto Guzman', 'PUERTO GUZMAN', 'PUTUMAYO'),
  ('86573', '86', 'Putumayo', 'Leguizamo', 'LEGUIZAMO', 'PUTUMAYO'),
  ('86749', '86', 'Putumayo', 'Sibundoy', 'SIBUNDOY', 'PUTUMAYO'),
  ('86755', '86', 'Putumayo', 'San Francisco', 'SAN FRANCISCO', 'PUTUMAYO'),
  ('86757', '86', 'Putumayo', 'San Miguel', 'SAN MIGUEL', 'PUTUMAYO'),
  ('86760', '86', 'Putumayo', 'Santiago', 'SANTIAGO', 'PUTUMAYO'),
  ('86865', '86', 'Putumayo', 'Valle del Guamuez', 'VALLE DEL GUAMUEZ', 'PUTUMAYO'),
  ('86885', '86', 'Putumayo', 'Villagarzon', 'VILLAGARZON', 'PUTUMAYO'),
  ('63001', '63', 'Quindio', 'Armenia', 'ARMENIA', 'QUINDIO'),
  ('63111', '63', 'Quindio', 'Buenavista', 'BUENAVISTA', 'QUINDIO'),
  ('63130', '63', 'Quindio', 'Calarca', 'CALARCA', 'QUINDIO'),
  ('63190', '63', 'Quindio', 'Circasia', 'CIRCASIA', 'QUINDIO'),
  ('63212', '63', 'Quindio', 'Cordoba', 'CORDOBA', 'QUINDIO'),
  ('63272', '63', 'Quindio', 'Filandia', 'FILANDIA', 'QUINDIO'),
  ('63302', '63', 'Quindio', 'Genova', 'GENOVA', 'QUINDIO'),
  ('63401', '63', 'Quindio', 'La Tebaida', 'LA TEBAIDA', 'QUINDIO'),
  ('63470', '63', 'Quindio', 'Montenegro', 'MONTENEGRO', 'QUINDIO'),
  ('63548', '63', 'Quindio', 'Pijao', 'PIJAO', 'QUINDIO'),
  ('63594', '63', 'Quindio', 'Quimbaya', 'QUIMBAYA', 'QUINDIO'),
  ('63690', '63', 'Quindio', 'Salento', 'SALENTO', 'QUINDIO'),
  ('66001', '66', 'Risaralda', 'Pereira', 'PEREIRA', 'RISARALDA'),
  ('66045', '66', 'Risaralda', 'Apia', 'APIA', 'RISARALDA'),
  ('66075', '66', 'Risaralda', 'Balboa', 'BALBOA', 'RISARALDA'),
  ('66088', '66', 'Risaralda', 'Belen de Umbria', 'BELEN DE UMBRIA', 'RISARALDA'),
  ('66170', '66', 'Risaralda', 'Dosquebradas', 'DOSQUEBRADAS', 'RISARALDA'),
  ('66318', '66', 'Risaralda', 'Guatica', 'GUATICA', 'RISARALDA');

INSERT INTO dane_municipalities (dane_code, department_code, department_name, municipality_name, municipality_name_normalized, department_name_normalized) VALUES
  ('66383', '66', 'Risaralda', 'La Celia', 'LA CELIA', 'RISARALDA'),
  ('66400', '66', 'Risaralda', 'La Virginia', 'LA VIRGINIA', 'RISARALDA'),
  ('66440', '66', 'Risaralda', 'Marsella', 'MARSELLA', 'RISARALDA'),
  ('66456', '66', 'Risaralda', 'Mistrato', 'MISTRATO', 'RISARALDA'),
  ('66572', '66', 'Risaralda', 'Pueblo Rico', 'PUEBLO RICO', 'RISARALDA'),
  ('66594', '66', 'Risaralda', 'Quinchia', 'QUINCHIA', 'RISARALDA'),
  ('66682', '66', 'Risaralda', 'Santa Rosa de Cabal', 'SANTA ROSA DE CABAL', 'RISARALDA'),
  ('66687', '66', 'Risaralda', 'Santuario', 'SANTUARIO', 'RISARALDA'),
  ('88001', '88', 'San Andres y Providencia', 'San Andres', 'SAN ANDRES', 'SAN ANDRES Y PROVIDENCIA'),
  ('88564', '88', 'San Andres y Providencia', 'Providencia', 'PROVIDENCIA', 'SAN ANDRES Y PROVIDENCIA'),
  ('68001', '68', 'Santander', 'Bucaramanga', 'BUCARAMANGA', 'SANTANDER'),
  ('68013', '68', 'Santander', 'Aguada', 'AGUADA', 'SANTANDER'),
  ('68020', '68', 'Santander', 'Albania', 'ALBANIA', 'SANTANDER'),
  ('68051', '68', 'Santander', 'Aratoca', 'ARATOCA', 'SANTANDER'),
  ('68077', '68', 'Santander', 'Barbosa', 'BARBOSA', 'SANTANDER'),
  ('68079', '68', 'Santander', 'Barichara', 'BARICHARA', 'SANTANDER'),
  ('68081', '68', 'Santander', 'Barrancabermeja', 'BARRANCABERMEJA', 'SANTANDER'),
  ('68092', '68', 'Santander', 'Betulia', 'BETULIA', 'SANTANDER'),
  ('68101', '68', 'Santander', 'Bolivar', 'BOLIVAR', 'SANTANDER'),
  ('68121', '68', 'Santander', 'Cabrera', 'CABRERA', 'SANTANDER'),
  ('68132', '68', 'Santander', 'California', 'CALIFORNIA', 'SANTANDER'),
  ('68147', '68', 'Santander', 'Capitanejo', 'CAPITANEJO', 'SANTANDER'),
  ('68152', '68', 'Santander', 'Carcasi', 'CARCASI', 'SANTANDER'),
  ('68160', '68', 'Santander', 'Cepita', 'CEPITA', 'SANTANDER'),
  ('68162', '68', 'Santander', 'Cerrito', 'CERRITO', 'SANTANDER'),
  ('68167', '68', 'Santander', 'Charala', 'CHARALA', 'SANTANDER'),
  ('68169', '68', 'Santander', 'Charta', 'CHARTA', 'SANTANDER'),
  ('68176', '68', 'Santander', 'Chima', 'CHIMA', 'SANTANDER'),
  ('68179', '68', 'Santander', 'Chipata', 'CHIPATA', 'SANTANDER'),
  ('68190', '68', 'Santander', 'Cimitarra', 'CIMITARRA', 'SANTANDER'),
  ('68207', '68', 'Santander', 'Concepcion', 'CONCEPCION', 'SANTANDER'),
  ('68209', '68', 'Santander', 'Confines', 'CONFINES', 'SANTANDER'),
  ('68211', '68', 'Santander', 'Contratacion', 'CONTRATACION', 'SANTANDER'),
  ('68217', '68', 'Santander', 'Coromoro', 'COROMORO', 'SANTANDER'),
  ('68229', '68', 'Santander', 'Curiti', 'CURITI', 'SANTANDER'),
  ('68235', '68', 'Santander', 'El Carmen de Chucuri', 'EL CARMEN DE CHUCURI', 'SANTANDER'),
  ('68245', '68', 'Santander', 'El Guacamayo', 'EL GUACAMAYO', 'SANTANDER'),
  ('68250', '68', 'Santander', 'El Penon', 'EL PENON', 'SANTANDER'),
  ('68255', '68', 'Santander', 'El Playon', 'EL PLAYON', 'SANTANDER'),
  ('68264', '68', 'Santander', 'Enciso', 'ENCISO', 'SANTANDER'),
  ('68266', '68', 'Santander', 'Encino', 'ENCINO', 'SANTANDER'),
  ('68271', '68', 'Santander', 'Florian', 'FLORIAN', 'SANTANDER'),
  ('68276', '68', 'Santander', 'Floridablanca', 'FLORIDABLANCA', 'SANTANDER'),
  ('68296', '68', 'Santander', 'Galan', 'GALAN', 'SANTANDER'),
  ('68298', '68', 'Santander', 'Gambita', 'GAMBITA', 'SANTANDER'),
  ('68307', '68', 'Santander', 'Giron', 'GIRON', 'SANTANDER'),
  ('68318', '68', 'Santander', 'Guaca', 'GUACA', 'SANTANDER'),
  ('68320', '68', 'Santander', 'Guadalupe', 'GUADALUPE', 'SANTANDER'),
  ('68322', '68', 'Santander', 'Guapota', 'GUAPOTA', 'SANTANDER'),
  ('68324', '68', 'Santander', 'Guavata', 'GUAVATA', 'SANTANDER'),
  ('68327', '68', 'Santander', 'Guepsa', 'GUEPSA', 'SANTANDER'),
  ('68344', '68', 'Santander', 'Hato', 'HATO', 'SANTANDER'),
  ('68368', '68', 'Santander', 'Jesus Maria', 'JESUS MARIA', 'SANTANDER'),
  ('68370', '68', 'Santander', 'Jordan', 'JORDAN', 'SANTANDER'),
  ('68377', '68', 'Santander', 'La Belleza', 'LA BELLEZA', 'SANTANDER'),
  ('68385', '68', 'Santander', 'Landazuri', 'LANDAZURI', 'SANTANDER'),
  ('68397', '68', 'Santander', 'La Paz', 'LA PAZ', 'SANTANDER'),
  ('68406', '68', 'Santander', 'Lebrija', 'LEBRIJA', 'SANTANDER'),
  ('68418', '68', 'Santander', 'Los Santos', 'LOS SANTOS', 'SANTANDER'),
  ('68425', '68', 'Santander', 'Macaravita', 'MACARAVITA', 'SANTANDER'),
  ('68432', '68', 'Santander', 'Malaga', 'MALAGA', 'SANTANDER'),
  ('68444', '68', 'Santander', 'Matanza', 'MATANZA', 'SANTANDER'),
  ('68464', '68', 'Santander', 'Mogotes', 'MOGOTES', 'SANTANDER'),
  ('68468', '68', 'Santander', 'Molagavita', 'MOLAGAVITA', 'SANTANDER'),
  ('68498', '68', 'Santander', 'Ocamonte', 'OCAMONTE', 'SANTANDER'),
  ('68500', '68', 'Santander', 'Oiba', 'OIBA', 'SANTANDER'),
  ('68502', '68', 'Santander', 'Onzaga', 'ONZAGA', 'SANTANDER'),
  ('68522', '68', 'Santander', 'Palmar', 'PALMAR', 'SANTANDER'),
  ('68524', '68', 'Santander', 'Palmas del Socorro', 'PALMAS DEL SOCORRO', 'SANTANDER'),
  ('68533', '68', 'Santander', 'Paramo', 'PARAMO', 'SANTANDER'),
  ('68547', '68', 'Santander', 'Piedecuesta', 'PIEDECUESTA', 'SANTANDER'),
  ('68549', '68', 'Santander', 'Pinchote', 'PINCHOTE', 'SANTANDER'),
  ('68572', '68', 'Santander', 'Puente Nacional', 'PUENTE NACIONAL', 'SANTANDER'),
  ('68573', '68', 'Santander', 'Puerto Parra', 'PUERTO PARRA', 'SANTANDER'),
  ('68575', '68', 'Santander', 'Puerto Wilches', 'PUERTO WILCHES', 'SANTANDER'),
  ('68615', '68', 'Santander', 'Rionegro', 'RIONEGRO', 'SANTANDER'),
  ('68655', '68', 'Santander', 'Sabana de Torres', 'SABANA DE TORRES', 'SANTANDER'),
  ('68669', '68', 'Santander', 'San Andres', 'SAN ANDRES', 'SANTANDER'),
  ('68673', '68', 'Santander', 'San Benito', 'SAN BENITO', 'SANTANDER'),
  ('68679', '68', 'Santander', 'San Gil', 'SAN GIL', 'SANTANDER'),
  ('68682', '68', 'Santander', 'San Joaquin', 'SAN JOAQUIN', 'SANTANDER'),
  ('68684', '68', 'Santander', 'San Jose de Miranda', 'SAN JOSE DE MIRANDA', 'SANTANDER'),
  ('68686', '68', 'Santander', 'San Miguel', 'SAN MIGUEL', 'SANTANDER'),
  ('68689', '68', 'Santander', 'San Vicente de Chucuri', 'SAN VICENTE DE CHUCURI', 'SANTANDER'),
  ('68705', '68', 'Santander', 'Santa Barbara', 'SANTA BARBARA', 'SANTANDER'),
  ('68720', '68', 'Santander', 'Santa Helena del Opon', 'SANTA HELENA DEL OPON', 'SANTANDER'),
  ('68745', '68', 'Santander', 'Simacota', 'SIMACOTA', 'SANTANDER'),
  ('68755', '68', 'Santander', 'Socorro', 'SOCORRO', 'SANTANDER'),
  ('68770', '68', 'Santander', 'Suaita', 'SUAITA', 'SANTANDER'),
  ('68773', '68', 'Santander', 'Sucre', 'SUCRE', 'SANTANDER'),
  ('68780', '68', 'Santander', 'Surata', 'SURATA', 'SANTANDER'),
  ('68820', '68', 'Santander', 'Tona', 'TONA', 'SANTANDER'),
  ('68855', '68', 'Santander', 'Valle de San Jose', 'VALLE DE SAN JOSE', 'SANTANDER'),
  ('68861', '68', 'Santander', 'Velez', 'VELEZ', 'SANTANDER'),
  ('68867', '68', 'Santander', 'Vetas', 'VETAS', 'SANTANDER'),
  ('68872', '68', 'Santander', 'Villanueva', 'VILLANUEVA', 'SANTANDER'),
  ('68895', '68', 'Santander', 'Zapatoca', 'ZAPATOCA', 'SANTANDER'),
  ('70001', '70', 'Sucre', 'Sincelejo', 'SINCELEJO', 'SUCRE'),
  ('70110', '70', 'Sucre', 'Buenavista', 'BUENAVISTA', 'SUCRE'),
  ('70124', '70', 'Sucre', 'Caimito', 'CAIMITO', 'SUCRE');

INSERT INTO dane_municipalities (dane_code, department_code, department_name, municipality_name, municipality_name_normalized, department_name_normalized) VALUES
  ('70204', '70', 'Sucre', 'Coloso', 'COLOSO', 'SUCRE'),
  ('70215', '70', 'Sucre', 'Corozal', 'COROZAL', 'SUCRE'),
  ('70221', '70', 'Sucre', 'Coveñas', 'COVENAS', 'SUCRE'),
  ('70230', '70', 'Sucre', 'Chalan', 'CHALAN', 'SUCRE'),
  ('70233', '70', 'Sucre', 'El Roble', 'EL ROBLE', 'SUCRE'),
  ('70235', '70', 'Sucre', 'Galeras', 'GALERAS', 'SUCRE'),
  ('70265', '70', 'Sucre', 'Guaranda', 'GUARANDA', 'SUCRE'),
  ('70400', '70', 'Sucre', 'La Union', 'LA UNION', 'SUCRE'),
  ('70418', '70', 'Sucre', 'Los Palmitos', 'LOS PALMITOS', 'SUCRE'),
  ('70429', '70', 'Sucre', 'Majagual', 'MAJAGUAL', 'SUCRE'),
  ('70473', '70', 'Sucre', 'Morroa', 'MORROA', 'SUCRE'),
  ('70508', '70', 'Sucre', 'Ovejas', 'OVEJAS', 'SUCRE'),
  ('70523', '70', 'Sucre', 'Palmito', 'PALMITO', 'SUCRE'),
  ('70670', '70', 'Sucre', 'Sampues', 'SAMPUES', 'SUCRE'),
  ('70678', '70', 'Sucre', 'San Benito Abad', 'SAN BENITO ABAD', 'SUCRE'),
  ('70702', '70', 'Sucre', 'San Juan de Betulia', 'SAN JUAN DE BETULIA', 'SUCRE'),
  ('70708', '70', 'Sucre', 'San Marcos', 'SAN MARCOS', 'SUCRE'),
  ('70713', '70', 'Sucre', 'San Onofre', 'SAN ONOFRE', 'SUCRE'),
  ('70717', '70', 'Sucre', 'San Pedro', 'SAN PEDRO', 'SUCRE'),
  ('70742', '70', 'Sucre', 'San Luis de Since', 'SAN LUIS DE SINCE', 'SUCRE'),
  ('70771', '70', 'Sucre', 'Sucre', 'SUCRE', 'SUCRE'),
  ('70820', '70', 'Sucre', 'Santiago de Tolu', 'SANTIAGO DE TOLU', 'SUCRE'),
  ('70823', '70', 'Sucre', 'Tolu Viejo', 'TOLU VIEJO', 'SUCRE'),
  ('73001', '73', 'Tolima', 'Ibague', 'IBAGUE', 'TOLIMA'),
  ('73024', '73', 'Tolima', 'Alpujarra', 'ALPUJARRA', 'TOLIMA'),
  ('73026', '73', 'Tolima', 'Alvarado', 'ALVARADO', 'TOLIMA'),
  ('73030', '73', 'Tolima', 'Ambalema', 'AMBALEMA', 'TOLIMA'),
  ('73043', '73', 'Tolima', 'Anzoategui', 'ANZOATEGUI', 'TOLIMA'),
  ('73055', '73', 'Tolima', 'Armero Guayabal', 'ARMERO GUAYABAL', 'TOLIMA'),
  ('73067', '73', 'Tolima', 'Ataco', 'ATACO', 'TOLIMA'),
  ('73124', '73', 'Tolima', 'Cajamarca', 'CAJAMARCA', 'TOLIMA'),
  ('73148', '73', 'Tolima', 'Carmen de Apicala', 'CARMEN DE APICALA', 'TOLIMA'),
  ('73152', '73', 'Tolima', 'Casabianca', 'CASABIANCA', 'TOLIMA'),
  ('73168', '73', 'Tolima', 'Chaparral', 'CHAPARRAL', 'TOLIMA'),
  ('73200', '73', 'Tolima', 'Coello', 'COELLO', 'TOLIMA'),
  ('73217', '73', 'Tolima', 'Coyaima', 'COYAIMA', 'TOLIMA'),
  ('73226', '73', 'Tolima', 'Cunday', 'CUNDAY', 'TOLIMA'),
  ('73236', '73', 'Tolima', 'Dolores', 'DOLORES', 'TOLIMA'),
  ('73268', '73', 'Tolima', 'Espinal', 'ESPINAL', 'TOLIMA'),
  ('73270', '73', 'Tolima', 'Falan', 'FALAN', 'TOLIMA'),
  ('73275', '73', 'Tolima', 'Flandes', 'FLANDES', 'TOLIMA'),
  ('73283', '73', 'Tolima', 'Fresno', 'FRESNO', 'TOLIMA'),
  ('73319', '73', 'Tolima', 'Guamo', 'GUAMO', 'TOLIMA'),
  ('73347', '73', 'Tolima', 'Herveo', 'HERVEO', 'TOLIMA'),
  ('73349', '73', 'Tolima', 'Honda', 'HONDA', 'TOLIMA'),
  ('73352', '73', 'Tolima', 'Icononzo', 'ICONONZO', 'TOLIMA'),
  ('73408', '73', 'Tolima', 'Lerida', 'LERIDA', 'TOLIMA'),
  ('73411', '73', 'Tolima', 'Libano', 'LIBANO', 'TOLIMA'),
  ('73443', '73', 'Tolima', 'San Sebastian de Mariquita', 'SAN SEBASTIAN DE MARIQUITA', 'TOLIMA'),
  ('73449', '73', 'Tolima', 'Melgar', 'MELGAR', 'TOLIMA'),
  ('73461', '73', 'Tolima', 'Murillo', 'MURILLO', 'TOLIMA'),
  ('73483', '73', 'Tolima', 'Natagaima', 'NATAGAIMA', 'TOLIMA'),
  ('73504', '73', 'Tolima', 'Ortega', 'ORTEGA', 'TOLIMA'),
  ('73520', '73', 'Tolima', 'Palocabildo', 'PALOCABILDO', 'TOLIMA'),
  ('73547', '73', 'Tolima', 'Piedras', 'PIEDRAS', 'TOLIMA'),
  ('73555', '73', 'Tolima', 'Planadas', 'PLANADAS', 'TOLIMA'),
  ('73563', '73', 'Tolima', 'Prado', 'PRADO', 'TOLIMA'),
  ('73585', '73', 'Tolima', 'Purificacion', 'PURIFICACION', 'TOLIMA'),
  ('73616', '73', 'Tolima', 'Rioblanco', 'RIOBLANCO', 'TOLIMA'),
  ('73622', '73', 'Tolima', 'Roncesvalles', 'RONCESVALLES', 'TOLIMA'),
  ('73624', '73', 'Tolima', 'Rovira', 'ROVIRA', 'TOLIMA'),
  ('73671', '73', 'Tolima', 'Saldana', 'SALDANA', 'TOLIMA'),
  ('73675', '73', 'Tolima', 'San Antonio', 'SAN ANTONIO', 'TOLIMA'),
  ('73678', '73', 'Tolima', 'San Luis', 'SAN LUIS', 'TOLIMA'),
  ('73686', '73', 'Tolima', 'Santa Isabel', 'SANTA ISABEL', 'TOLIMA'),
  ('73770', '73', 'Tolima', 'Suarez', 'SUAREZ', 'TOLIMA'),
  ('73854', '73', 'Tolima', 'Valle de San Juan', 'VALLE DE SAN JUAN', 'TOLIMA'),
  ('73861', '73', 'Tolima', 'Venadillo', 'VENADILLO', 'TOLIMA'),
  ('73870', '73', 'Tolima', 'Villahermosa', 'VILLAHERMOSA', 'TOLIMA'),
  ('73873', '73', 'Tolima', 'Villarrica', 'VILLARRICA', 'TOLIMA'),
  ('76001', '76', 'Valle del Cauca', 'Cali', 'CALI', 'VALLE DEL CAUCA'),
  ('76020', '76', 'Valle del Cauca', 'Alcala', 'ALCALA', 'VALLE DEL CAUCA'),
  ('76036', '76', 'Valle del Cauca', 'Andalucia', 'ANDALUCIA', 'VALLE DEL CAUCA'),
  ('76041', '76', 'Valle del Cauca', 'Ansermanuevo', 'ANSERMANUEVO', 'VALLE DEL CAUCA'),
  ('76054', '76', 'Valle del Cauca', 'Argelia', 'ARGELIA', 'VALLE DEL CAUCA'),
  ('76100', '76', 'Valle del Cauca', 'Bolivar', 'BOLIVAR', 'VALLE DEL CAUCA'),
  ('76109', '76', 'Valle del Cauca', 'Buenaventura', 'BUENAVENTURA', 'VALLE DEL CAUCA'),
  ('76111', '76', 'Valle del Cauca', 'Guadalajara de Buga', 'GUADALAJARA DE BUGA', 'VALLE DEL CAUCA'),
  ('76113', '76', 'Valle del Cauca', 'Bugalagrande', 'BUGALAGRANDE', 'VALLE DEL CAUCA'),
  ('76122', '76', 'Valle del Cauca', 'Caicedonia', 'CAICEDONIA', 'VALLE DEL CAUCA'),
  ('76126', '76', 'Valle del Cauca', 'Calima', 'CALIMA', 'VALLE DEL CAUCA'),
  ('76130', '76', 'Valle del Cauca', 'Candelaria', 'CANDELARIA', 'VALLE DEL CAUCA'),
  ('76147', '76', 'Valle del Cauca', 'Cartago', 'CARTAGO', 'VALLE DEL CAUCA'),
  ('76233', '76', 'Valle del Cauca', 'Dagua', 'DAGUA', 'VALLE DEL CAUCA'),
  ('76243', '76', 'Valle del Cauca', 'El Aguila', 'EL AGUILA', 'VALLE DEL CAUCA'),
  ('76246', '76', 'Valle del Cauca', 'El Cairo', 'EL CAIRO', 'VALLE DEL CAUCA'),
  ('76248', '76', 'Valle del Cauca', 'El Cerrito', 'EL CERRITO', 'VALLE DEL CAUCA'),
  ('76250', '76', 'Valle del Cauca', 'El Dovio', 'EL DOVIO', 'VALLE DEL CAUCA'),
  ('76275', '76', 'Valle del Cauca', 'Florida', 'FLORIDA', 'VALLE DEL CAUCA'),
  ('76306', '76', 'Valle del Cauca', 'Ginebra', 'GINEBRA', 'VALLE DEL CAUCA'),
  ('76318', '76', 'Valle del Cauca', 'Guacari', 'GUACARI', 'VALLE DEL CAUCA'),
  ('76364', '76', 'Valle del Cauca', 'Jamundi', 'JAMUNDI', 'VALLE DEL CAUCA'),
  ('76377', '76', 'Valle del Cauca', 'La Cumbre', 'LA CUMBRE', 'VALLE DEL CAUCA'),
  ('76400', '76', 'Valle del Cauca', 'La Union', 'LA UNION', 'VALLE DEL CAUCA'),
  ('76403', '76', 'Valle del Cauca', 'La Victoria', 'LA VICTORIA', 'VALLE DEL CAUCA'),
  ('76497', '76', 'Valle del Cauca', 'Obando', 'OBANDO', 'VALLE DEL CAUCA'),
  ('76520', '76', 'Valle del Cauca', 'Palmira', 'PALMIRA', 'VALLE DEL CAUCA'),
  ('76563', '76', 'Valle del Cauca', 'Pradera', 'PRADERA', 'VALLE DEL CAUCA'),
  ('76606', '76', 'Valle del Cauca', 'Restrepo', 'RESTREPO', 'VALLE DEL CAUCA'),
  ('76616', '76', 'Valle del Cauca', 'Riofrio', 'RIOFRIO', 'VALLE DEL CAUCA');

INSERT INTO dane_municipalities (dane_code, department_code, department_name, municipality_name, municipality_name_normalized, department_name_normalized) VALUES
  ('76622', '76', 'Valle del Cauca', 'Roldanillo', 'ROLDANILLO', 'VALLE DEL CAUCA'),
  ('76670', '76', 'Valle del Cauca', 'San Pedro', 'SAN PEDRO', 'VALLE DEL CAUCA'),
  ('76736', '76', 'Valle del Cauca', 'Sevilla', 'SEVILLA', 'VALLE DEL CAUCA'),
  ('76823', '76', 'Valle del Cauca', 'Toro', 'TORO', 'VALLE DEL CAUCA'),
  ('76828', '76', 'Valle del Cauca', 'Trujillo', 'TRUJILLO', 'VALLE DEL CAUCA'),
  ('76834', '76', 'Valle del Cauca', 'Tulua', 'TULUA', 'VALLE DEL CAUCA'),
  ('76845', '76', 'Valle del Cauca', 'Ulloa', 'ULLOA', 'VALLE DEL CAUCA'),
  ('76863', '76', 'Valle del Cauca', 'Versalles', 'VERSALLES', 'VALLE DEL CAUCA'),
  ('76869', '76', 'Valle del Cauca', 'Vijes', 'VIJES', 'VALLE DEL CAUCA'),
  ('76890', '76', 'Valle del Cauca', 'Yotoco', 'YOTOCO', 'VALLE DEL CAUCA'),
  ('76892', '76', 'Valle del Cauca', 'Yumbo', 'YUMBO', 'VALLE DEL CAUCA'),
  ('76895', '76', 'Valle del Cauca', 'Zarzal', 'ZARZAL', 'VALLE DEL CAUCA'),
  ('97001', '97', 'Vaupes', 'Mitu', 'MITU', 'VAUPES'),
  ('97161', '97', 'Vaupes', 'Caruru', 'CARURU', 'VAUPES'),
  ('97511', '97', 'Vaupes', 'Pacoa', 'PACOA', 'VAUPES'),
  ('97666', '97', 'Vaupes', 'Taraira', 'TARAIRA', 'VAUPES'),
  ('97777', '97', 'Vaupes', 'Papunaua', 'PAPUNAUA', 'VAUPES'),
  ('97889', '97', 'Vaupes', 'Yavarate', 'YAVARATE', 'VAUPES'),
  ('99001', '99', 'Vichada', 'Puerto Carreno', 'PUERTO CARRENO', 'VICHADA'),
  ('99524', '99', 'Vichada', 'La Primavera', 'LA PRIMAVERA', 'VICHADA'),
  ('99624', '99', 'Vichada', 'Santa Rosalia', 'SANTA ROSALIA', 'VICHADA'),
  ('99773', '99', 'Vichada', 'Cumaribo', 'CUMARIBO', 'VICHADA');

-- Total municipalities seeded: 1122
