-- ============================================================================
-- Coordinadora Carrier Coverage Table
-- 1,489 cities served by Coordinadora with COD availability flag
-- Source: Coordinadora Mercantil S.A. city coverage list
-- ============================================================================

-- 1. Create table (global reference, NO workspace_id, NO RLS)
CREATE TABLE carrier_coverage (
  id SERIAL PRIMARY KEY,
  carrier TEXT NOT NULL DEFAULT 'coordinadora',
  city_coordinadora TEXT NOT NULL,
  city_name TEXT NOT NULL,
  department_abbrev TEXT NOT NULL,
  dane_municipality_id INTEGER REFERENCES dane_municipalities(id),
  supports_cod BOOLEAN NOT NULL DEFAULT false,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('America/Bogota', NOW()),
  UNIQUE(carrier, city_coordinadora)
);

-- 2. Indexes for lookup queries
CREATE INDEX idx_carrier_coverage_lookup ON carrier_coverage(carrier, city_name, department_abbrev);
CREATE INDEX idx_carrier_coverage_cod ON carrier_coverage(carrier, supports_cod) WHERE is_active = true;
CREATE INDEX idx_carrier_coverage_dane ON carrier_coverage(dane_municipality_id) WHERE dane_municipality_id IS NOT NULL;

-- 3. Permissions (NO RLS since global reference)
GRANT SELECT ON carrier_coverage TO authenticated;
GRANT SELECT ON carrier_coverage TO service_role;
GRANT USAGE, SELECT ON SEQUENCE carrier_coverage_id_seq TO authenticated, service_role;

-- 4. Seed ALL Coordinadora cities
-- TODO: Update supports_cod when COD city list is provided
INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'ABEJORRAL (ANT)', 'ABEJORRAL', 'ANT'),
  ('coordinadora', 'ABREGO (N/STDER)', 'ABREGO', 'N/STDER'),
  ('coordinadora', 'ABRIAQUI (ANT)', 'ABRIAQUI', 'ANT'),
  ('coordinadora', 'ACACIAS (META)', 'ACACIAS', 'META'),
  ('coordinadora', 'ACANDI (CHOCO)', 'ACANDI', 'CHOCO'),
  ('coordinadora', 'ACAPULCO (STDER)', 'ACAPULCO', 'STDER'),
  ('coordinadora', 'ACEVEDO (HLA)', 'ACEVEDO', 'HLA'),
  ('coordinadora', 'ACHI (BOL)', 'ACHI', 'BOL'),
  ('coordinadora', 'AGRADO (HLA)', 'AGRADO', 'HLA'),
  ('coordinadora', 'AGUA DE DIOS (C/MARCA)', 'AGUA DE DIOS', 'C/MARCA'),
  ('coordinadora', 'AGUACHICA (CES)', 'AGUACHICA', 'CES'),
  ('coordinadora', 'AGUACLARA (C/NARE)', 'AGUACLARA', 'C/NARE'),
  ('coordinadora', 'AGUADA (STDER)', 'AGUADA', 'STDER'),
  ('coordinadora', 'AGUADAS (CDAS)', 'AGUADAS', 'CDAS'),
  ('coordinadora', 'AGUAS BLANCAS (CES)', 'AGUAS BLANCAS', 'CES'),
  ('coordinadora', 'AGUAZUL (C/NARE)', 'AGUAZUL', 'C/NARE'),
  ('coordinadora', 'AIPE (HLA)', 'AIPE', 'HLA'),
  ('coordinadora', 'ALBAN (C/MARCA)', 'ALBAN', 'C/MARCA'),
  ('coordinadora', 'ALBANIA (ANT)', 'ALBANIA', 'ANT'),
  ('coordinadora', 'ALBANIA (CAQ)', 'ALBANIA', 'CAQ'),
  ('coordinadora', 'ALBANIA (GUAJ)', 'ALBANIA', 'GUAJ'),
  ('coordinadora', 'ALCALA (VALLE)', 'ALCALA', 'VALLE'),
  ('coordinadora', 'ALDANA (NAR)', 'ALDANA', 'NAR'),
  ('coordinadora', 'ALEJANDRIA (ANT)', 'ALEJANDRIA', 'ANT'),
  ('coordinadora', 'ALGARROBO (MG/LENA)', 'ALGARROBO', 'MG/LENA'),
  ('coordinadora', 'ALGECIRAS (HLA)', 'ALGECIRAS', 'HLA'),
  ('coordinadora', 'ALMAGUER (CAU)', 'ALMAGUER', 'CAU'),
  ('coordinadora', 'ALMEIDA (BOY)', 'ALMEIDA', 'BOY'),
  ('coordinadora', 'ALPUJARRA (TOL)', 'ALPUJARRA', 'TOL'),
  ('coordinadora', 'ALTAMIRA (ANT)', 'ALTAMIRA', 'ANT'),
  ('coordinadora', 'ALTAMIRA (HLA)', 'ALTAMIRA', 'HLA'),
  ('coordinadora', 'ALTAQUER (NAR)', 'ALTAQUER', 'NAR'),
  ('coordinadora', 'ALTO BAUDO (CHOCO)', 'ALTO BAUDO', 'CHOCO'),
  ('coordinadora', 'ALTO DE TABLAZO (CDAS)', 'ALTO DE TABLAZO', 'CDAS'),
  ('coordinadora', 'ALVARADO (TOL)', 'ALVARADO', 'TOL'),
  ('coordinadora', 'ALVARO OBREGON (CMX)', 'ALVARO OBREGON', 'CMX'),
  ('coordinadora', 'AMAGA (ANT)', 'AMAGA', 'ANT'),
  ('coordinadora', 'AMAIME (VALLE)', 'AMAIME', 'VALLE'),
  ('coordinadora', 'AMALFI (ANT)', 'AMALFI', 'ANT'),
  ('coordinadora', 'AMBALEMA (TOL)', 'AMBALEMA', 'TOL'),
  ('coordinadora', 'ANAPOIMA (C/MARCA)', 'ANAPOIMA', 'C/MARCA'),
  ('coordinadora', 'ANCUYA (NAR)', 'ANCUYA', 'NAR'),
  ('coordinadora', 'ANDAGOYA (CHOCO)', 'ANDAGOYA', 'CHOCO'),
  ('coordinadora', 'ANDALUCIA (VALLE)', 'ANDALUCIA', 'VALLE'),
  ('coordinadora', 'ANDES (ANT)', 'ANDES', 'ANT'),
  ('coordinadora', 'ANGELOPOLIS (ANT)', 'ANGELOPOLIS', 'ANT'),
  ('coordinadora', 'ANGOSTURA (ANT)', 'ANGOSTURA', 'ANT'),
  ('coordinadora', 'ANIMAS (CHOCO)', 'ANIMAS', 'CHOCO'),
  ('coordinadora', 'ANOLAIMA (C/MARCA)', 'ANOLAIMA', 'C/MARCA'),
  ('coordinadora', 'ANORI (ANT)', 'ANORI', 'ANT'),
  ('coordinadora', 'ANSERMA (CDAS)', 'ANSERMA', 'CDAS'),
  ('coordinadora', 'ANSERMA NUEVO (VALLE)', 'ANSERMA NUEVO', 'VALLE'),
  ('coordinadora', 'ANTEQUERA (CES)', 'ANTEQUERA', 'CES'),
  ('coordinadora', 'ANZA (ANT)', 'ANZA', 'ANT'),
  ('coordinadora', 'ANZOATEGUI (TOL)', 'ANZOATEGUI', 'TOL'),
  ('coordinadora', 'APARTADO (ANT)', 'APARTADO', 'ANT'),
  ('coordinadora', 'APIA (RS)', 'APIA', 'RS'),
  ('coordinadora', 'APIAY (META)', 'APIAY', 'META'),
  ('coordinadora', 'APULO (C/MARCA)', 'APULO', 'C/MARCA'),
  ('coordinadora', 'AQUITANIA (BOY)', 'AQUITANIA', 'BOY'),
  ('coordinadora', 'ARACATACA (MG/LENA)', 'ARACATACA', 'MG/LENA'),
  ('coordinadora', 'ARANZAZU (CDAS)', 'ARANZAZU', 'CDAS'),
  ('coordinadora', 'ARATOCA (STDER)', 'ARATOCA', 'STDER'),
  ('coordinadora', 'ARAUCA (ARAU)', 'ARAUCA', 'ARAU'),
  ('coordinadora', 'ARAUCA (CDAS)', 'ARAUCA', 'CDAS'),
  ('coordinadora', 'ARAUQUITA (ARAU)', 'ARAUQUITA', 'ARAU'),
  ('coordinadora', 'ARBELAEZ (C/MARCA)', 'ARBELAEZ', 'C/MARCA'),
  ('coordinadora', 'ARBOLEDA (CDAS)', 'ARBOLEDA', 'CDAS'),
  ('coordinadora', 'ARBOLEDAS (N/STDER)', 'ARBOLEDAS', 'N/STDER'),
  ('coordinadora', 'ARBOLETES (ANT)', 'ARBOLETES', 'ANT'),
  ('coordinadora', 'ARCABUCO (BOY)', 'ARCABUCO', 'BOY'),
  ('coordinadora', 'ARENAL (BOL)', 'ARENAL', 'BOL'),
  ('coordinadora', 'ARGELIA (ANT)', 'ARGELIA', 'ANT'),
  ('coordinadora', 'ARGELIA (CAU)', 'ARGELIA', 'CAU'),
  ('coordinadora', 'ARGELIA (VALLE)', 'ARGELIA', 'VALLE'),
  ('coordinadora', 'ARGENTINA (HLA)', 'ARGENTINA', 'HLA'),
  ('coordinadora', 'ARJONA (BOL)', 'ARJONA', 'BOL'),
  ('coordinadora', 'ARJONA (CES)', 'ARJONA', 'CES'),
  ('coordinadora', 'ARMA (CDAS)', 'ARMA', 'CDAS'),
  ('coordinadora', 'ARMENIA (QDIO)', 'ARMENIA', 'QDIO'),
  ('coordinadora', 'ARMENIA MANTEQUILLA (ANT)', 'ARMENIA MANTEQUILLA', 'ANT'),
  ('coordinadora', 'ARMERO GUAYABAL (TOL)', 'ARMERO GUAYABAL', 'TOL'),
  ('coordinadora', 'ARROYO DE PIEDRA (ATL)', 'ARROYO DE PIEDRA', 'ATL'),
  ('coordinadora', 'ASTREA (CES)', 'ASTREA', 'CES'),
  ('coordinadora', 'ATACO (TOL)', 'ATACO', 'TOL'),
  ('coordinadora', 'ATIZAPAN DE ZARAGOZA (MEX)', 'ATIZAPAN DE ZARAGOZA', 'MEX'),
  ('coordinadora', 'AYACUCHO (CES)', 'AYACUCHO', 'CES'),
  ('coordinadora', 'AYAPEL (CORD)', 'AYAPEL', 'CORD'),
  ('coordinadora', 'AZACRANAL (C/MARCA)', 'AZACRANAL', 'C/MARCA'),
  ('coordinadora', 'AZCAPOTZALCO (CMX)', 'AZCAPOTZALCO', 'CMX'),
  ('coordinadora', 'BADILLO (CES)', 'BADILLO', 'CES'),
  ('coordinadora', 'BAGAZAL (C/MARCA)', 'BAGAZAL', 'C/MARCA'),
  ('coordinadora', 'BAHIA SOLANO MUTIS (CHOCO)', 'BAHIA SOLANO MUTIS', 'CHOCO'),
  ('coordinadora', 'BAJO BAUDO PIZARRO (CHOCO)', 'BAJO BAUDO PIZARRO', 'CHOCO'),
  ('coordinadora', 'BAJO DEL LIMON (CORD)', 'BAJO DEL LIMON', 'CORD'),
  ('coordinadora', 'BAJO TABLAZO (CDAS)', 'BAJO TABLAZO', 'CDAS'),
  ('coordinadora', 'BALBOA (CAU)', 'BALBOA', 'CAU'),
  ('coordinadora', 'BALBOA (RS)', 'BALBOA', 'RS'),
  ('coordinadora', 'BALLESTAS (BOL)', 'BALLESTAS', 'BOL'),
  ('coordinadora', 'BARANOA (ATL)', 'BARANOA', 'ATL');

INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'BARAYA (HLA)', 'BARAYA', 'HLA'),
  ('coordinadora', 'BARBACOAS (NAR)', 'BARBACOAS', 'NAR'),
  ('coordinadora', 'BARBOSA (ANT)', 'BARBOSA', 'ANT'),
  ('coordinadora', 'BARBOSA (STDER)', 'BARBOSA', 'STDER'),
  ('coordinadora', 'BARCELONA (QDIO)', 'BARCELONA', 'QDIO'),
  ('coordinadora', 'BARICHARA (STDER)', 'BARICHARA', 'STDER'),
  ('coordinadora', 'BARRANCA DE UPIA (META)', 'BARRANCA DE UPIA', 'META'),
  ('coordinadora', 'BARRANCABERMEJA (STDER)', 'BARRANCABERMEJA', 'STDER'),
  ('coordinadora', 'BARRANCAS (GUAJ)', 'BARRANCAS', 'GUAJ'),
  ('coordinadora', 'BARRANCO DE LOBA (BOL)', 'BARRANCO DE LOBA', 'BOL'),
  ('coordinadora', 'BARRANQUILLA (ATL)', 'BARRANQUILLA', 'ATL'),
  ('coordinadora', 'BARU (BOL)', 'BARU', 'BOL'),
  ('coordinadora', 'BAYUNCA (BOL)', 'BAYUNCA', 'BOL'),
  ('coordinadora', 'BECERRIL (CES)', 'BECERRIL', 'CES'),
  ('coordinadora', 'BELALCAZAR (CDAS)', 'BELALCAZAR', 'CDAS'),
  ('coordinadora', 'BELALCAZAR PAEZ (CAU)', 'BELALCAZAR PAEZ', 'CAU'),
  ('coordinadora', 'BELEN (BOY)', 'BELEN', 'BOY'),
  ('coordinadora', 'BELEN (CORD)', 'BELEN', 'CORD'),
  ('coordinadora', 'BELEN (HLA)', 'BELEN', 'HLA'),
  ('coordinadora', 'BELEN (NAR)', 'BELEN', 'NAR'),
  ('coordinadora', 'BELEN DE LOS ANDAQUIES (CAQ)', 'BELEN DE LOS ANDAQUIES', 'CAQ'),
  ('coordinadora', 'BELEN DE UMBRIA (RS)', 'BELEN DE UMBRIA', 'RS'),
  ('coordinadora', 'BELENCITO (BOY)', 'BELENCITO', 'BOY'),
  ('coordinadora', 'BELLO (ANT)', 'BELLO', 'ANT'),
  ('coordinadora', 'BELMIRA (ANT)', 'BELMIRA', 'ANT'),
  ('coordinadora', 'BENITO JUAREZ (CMX)', 'BENITO JUAREZ', 'CMX'),
  ('coordinadora', 'BERBEO (BOY)', 'BERBEO', 'BOY'),
  ('coordinadora', 'BERRUECOS ARBOLEDA (NAR)', 'BERRUECOS ARBOLEDA', 'NAR'),
  ('coordinadora', 'BETANIA (ANT)', 'BETANIA', 'ANT'),
  ('coordinadora', 'BETEITIVA (BOY)', 'BETEITIVA', 'BOY'),
  ('coordinadora', 'BETULIA (ANT)', 'BETULIA', 'ANT'),
  ('coordinadora', 'BETULIA (STDER)', 'BETULIA', 'STDER'),
  ('coordinadora', 'BITUIMA (C/MARCA)', 'BITUIMA', 'C/MARCA'),
  ('coordinadora', 'BOAVITA (BOY)', 'BOAVITA', 'BOY'),
  ('coordinadora', 'BOCHALEMA (N/STDER)', 'BOCHALEMA', 'N/STDER'),
  ('coordinadora', 'BOGOTA (C/MARCA)', 'BOGOTA', 'C/MARCA'),
  ('coordinadora', 'BOJACA (C/MARCA)', 'BOJACA', 'C/MARCA'),
  ('coordinadora', 'BOJAYA (CHOCO)', 'BOJAYA', 'CHOCO'),
  ('coordinadora', 'BOLIVAR (CAU)', 'BOLIVAR', 'CAU'),
  ('coordinadora', 'BOLIVAR (STDER)', 'BOLIVAR', 'STDER'),
  ('coordinadora', 'BOLIVAR (VALLE)', 'BOLIVAR', 'VALLE'),
  ('coordinadora', 'BOLIVIA (CDAS)', 'BOLIVIA', 'CDAS'),
  ('coordinadora', 'BOLOMBOLO (ANT)', 'BOLOMBOLO', 'ANT'),
  ('coordinadora', 'BONAFONT (CDAS)', 'BONAFONT', 'CDAS'),
  ('coordinadora', 'BONDA (MG/LENA)', 'BONDA', 'MG/LENA'),
  ('coordinadora', 'BOQUERON (C/MARCA)', 'BOQUERON', 'C/MARCA'),
  ('coordinadora', 'BOQUERON (TOL)', 'BOQUERON', 'TOL'),
  ('coordinadora', 'BOSCONIA (CES)', 'BOSCONIA', 'CES'),
  ('coordinadora', 'BOYACA (BOY)', 'BOYACA', 'BOY'),
  ('coordinadora', 'BRICEÑO (ANT)', 'BRICEÑO', 'ANT'),
  ('coordinadora', 'BRICEÑO (BOY)', 'BRICEÑO', 'BOY'),
  ('coordinadora', 'BRICEÑO (C/MARCA)', 'BRICEÑO', 'C/MARCA'),
  ('coordinadora', 'BRISAS DEL HONG KONG (P/MAYO)', 'BRISAS DEL HONG KONG', 'P/MAYO'),
  ('coordinadora', 'BRUSELAS (HLA)', 'BRUSELAS', 'HLA'),
  ('coordinadora', 'BUCARAMANGA (STDER)', 'BUCARAMANGA', 'STDER'),
  ('coordinadora', 'BUCARASICA (N/STDER)', 'BUCARASICA', 'N/STDER'),
  ('coordinadora', 'BUENA SENA (BOL)', 'BUENA SENA', 'BOL'),
  ('coordinadora', 'BUENA VISTA (CORD)', 'BUENA VISTA', 'CORD'),
  ('coordinadora', 'BUENAVENTURA (VALLE)', 'BUENAVENTURA', 'VALLE'),
  ('coordinadora', 'BUENAVISTA (BOY)', 'BUENAVISTA', 'BOY'),
  ('coordinadora', 'BUENAVISTA (GUAJ)', 'BUENAVISTA', 'GUAJ'),
  ('coordinadora', 'BUENAVISTA (QDIO)', 'BUENAVISTA', 'QDIO'),
  ('coordinadora', 'BUENOS AIRES (CAU)', 'BUENOS AIRES', 'CAU'),
  ('coordinadora', 'BUENOS AIRES (TOL)', 'BUENOS AIRES', 'TOL'),
  ('coordinadora', 'BUESACO (NAR)', 'BUESACO', 'NAR'),
  ('coordinadora', 'BUESAQUILLO (NAR)', 'BUESAQUILLO', 'NAR'),
  ('coordinadora', 'BUGA (VALLE)', 'BUGA', 'VALLE'),
  ('coordinadora', 'BUGA LA GRANDE (VALLE)', 'BUGA LA GRANDE', 'VALLE'),
  ('coordinadora', 'BURITICA (ANT)', 'BURITICA', 'ANT'),
  ('coordinadora', 'BUSBANZA (BOY)', 'BUSBANZA', 'BOY'),
  ('coordinadora', 'CABRERA (C/MARCA)', 'CABRERA', 'C/MARCA'),
  ('coordinadora', 'CABRERA (NAR)', 'CABRERA', 'NAR'),
  ('coordinadora', 'CABUYA (CORD)', 'CABUYA', 'CORD'),
  ('coordinadora', 'CACERES (ANT)', 'CACERES', 'ANT'),
  ('coordinadora', 'CACHIPAY (C/MARCA)', 'CACHIPAY', 'C/MARCA'),
  ('coordinadora', 'CACHIRA (N/STDER)', 'CACHIRA', 'N/STDER'),
  ('coordinadora', 'CACICAZGO (C/MARCA)', 'CACICAZGO', 'C/MARCA'),
  ('coordinadora', 'CACOTA (N/STDER)', 'CACOTA', 'N/STDER'),
  ('coordinadora', 'CAGUAN (HLA)', 'CAGUAN', 'HLA'),
  ('coordinadora', 'CAICEDO (ANT)', 'CAICEDO', 'ANT'),
  ('coordinadora', 'CAICEDONIA (VALLE)', 'CAICEDONIA', 'VALLE'),
  ('coordinadora', 'CAIMITO (SUCRE)', 'CAIMITO', 'SUCRE'),
  ('coordinadora', 'CAJAMARCA (TOL)', 'CAJAMARCA', 'TOL'),
  ('coordinadora', 'CAJAPI (NAR)', 'CAJAPI', 'NAR'),
  ('coordinadora', 'CAJETE (CAU)', 'CAJETE', 'CAU'),
  ('coordinadora', 'CAJIBIO (CAU)', 'CAJIBIO', 'CAU'),
  ('coordinadora', 'CAJICA (C/MARCA)', 'CAJICA', 'C/MARCA'),
  ('coordinadora', 'CALAMAR (BOL)', 'CALAMAR', 'BOL'),
  ('coordinadora', 'CALARCA (QDIO)', 'CALARCA', 'QDIO'),
  ('coordinadora', 'CALDAS (ANT)', 'CALDAS', 'ANT'),
  ('coordinadora', 'CALDAS (BOY)', 'CALDAS', 'BOY'),
  ('coordinadora', 'CALDAS VIEJO (TOL)', 'CALDAS VIEJO', 'TOL'),
  ('coordinadora', 'CALDONO (CAU)', 'CALDONO', 'CAU'),
  ('coordinadora', 'CALI (VALLE)', 'CALI', 'VALLE'),
  ('coordinadora', 'CALIBIO (CAU)', 'CALIBIO', 'CAU'),
  ('coordinadora', 'CALOTO (CAU)', 'CALOTO', 'CAU'),
  ('coordinadora', 'CAMBAO (C/MARCA)', 'CAMBAO', 'C/MARCA'),
  ('coordinadora', 'CAMILO C (ANT)', 'CAMILO C', 'ANT'),
  ('coordinadora', 'CAMPAMENTO (ANT)', 'CAMPAMENTO', 'ANT'),
  ('coordinadora', 'CAMPECHE (ATL)', 'CAMPECHE', 'ATL');

INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'CAMPO DE LA CRUZ (ATL)', 'CAMPO DE LA CRUZ', 'ATL'),
  ('coordinadora', 'CAMPOALEGRE (HLA)', 'CAMPOALEGRE', 'HLA'),
  ('coordinadora', 'CAMPOALEGRE (VALLE)', 'CAMPOALEGRE', 'VALLE'),
  ('coordinadora', 'CAMPOHERMOSO (BOY)', 'CAMPOHERMOSO', 'BOY'),
  ('coordinadora', 'CANALETE (CORD)', 'CANALETE', 'CORD'),
  ('coordinadora', 'CANDELARIA (ATL)', 'CANDELARIA', 'ATL'),
  ('coordinadora', 'CANDELARIA (VALLE)', 'CANDELARIA', 'VALLE'),
  ('coordinadora', 'CANDELILLAS (NAR)', 'CANDELILLAS', 'NAR'),
  ('coordinadora', 'CANTAGALLO (BOL)', 'CANTAGALLO', 'BOL'),
  ('coordinadora', 'CAPARRAPI (C/MARCA)', 'CAPARRAPI', 'C/MARCA'),
  ('coordinadora', 'CAPELLANIA (C/MARCA)', 'CAPELLANIA', 'C/MARCA'),
  ('coordinadora', 'CAPITANEJO (STDER)', 'CAPITANEJO', 'STDER'),
  ('coordinadora', 'CAPURGANA (CHOCO)', 'CAPURGANA', 'CHOCO'),
  ('coordinadora', 'CAQUEZA (C/MARCA)', 'CAQUEZA', 'C/MARCA'),
  ('coordinadora', 'CARACOLI (ANT)', 'CARACOLI', 'ANT'),
  ('coordinadora', 'CARACOLICITO (CES)', 'CARACOLICITO', 'CES'),
  ('coordinadora', 'CARAMANTA (ANT)', 'CARAMANTA', 'ANT'),
  ('coordinadora', 'CARCASI (STDER)', 'CARCASI', 'STDER'),
  ('coordinadora', 'CAREPA (ANT)', 'CAREPA', 'ANT'),
  ('coordinadora', 'CARLOSAMA  CUASPUD (NAR)', 'CARLOSAMA  CUASPUD', 'NAR'),
  ('coordinadora', 'CARMEN DE APICALA (TOL)', 'CARMEN DE APICALA', 'TOL'),
  ('coordinadora', 'CARMEN DE CARUPA (C/MARCA)', 'CARMEN DE CARUPA', 'C/MARCA'),
  ('coordinadora', 'CAROLINA (CORD)', 'CAROLINA', 'CORD'),
  ('coordinadora', 'CAROLINA DEL PRINCIPE (ANT)', 'CAROLINA DEL PRINCIPE', 'ANT'),
  ('coordinadora', 'CARRILLO (CORD)', 'CARRILLO', 'CORD'),
  ('coordinadora', 'CARRIZAL (CORD)', 'CARRIZAL', 'CORD'),
  ('coordinadora', 'CARTAGENA (BOL)', 'CARTAGENA', 'BOL'),
  ('coordinadora', 'CARTAGENA (C/MARCA)', 'CARTAGENA', 'C/MARCA'),
  ('coordinadora', 'CARTAGENA DEL CHAIRA (CAQ)', 'CARTAGENA DEL CHAIRA', 'CAQ'),
  ('coordinadora', 'CARTAGO (VALLE)', 'CARTAGO', 'VALLE'),
  ('coordinadora', 'CASABIANCA (TOL)', 'CASABIANCA', 'TOL'),
  ('coordinadora', 'CASCAJAL (ATL)', 'CASCAJAL', 'ATL'),
  ('coordinadora', 'CASCAJAL (C/MARCA)', 'CASCAJAL', 'C/MARCA'),
  ('coordinadora', 'CASTILLA (CDAS)', 'CASTILLA', 'CDAS'),
  ('coordinadora', 'CASTILLA (TOL)', 'CASTILLA', 'TOL'),
  ('coordinadora', 'CASTILLA LA NUEVA (META)', 'CASTILLA LA NUEVA', 'META'),
  ('coordinadora', 'CATAMBUCO (NAR)', 'CATAMBUCO', 'NAR'),
  ('coordinadora', 'CAUCASIA (ANT)', 'CAUCASIA', 'ANT'),
  ('coordinadora', 'CAÑASGORDAS (ANT)', 'CAÑASGORDAS', 'ANT'),
  ('coordinadora', 'CAÑAVERAL (BOL)', 'CAÑAVERAL', 'BOL'),
  ('coordinadora', 'CAÑAVERAL (CDAS)', 'CAÑAVERAL', 'CDAS'),
  ('coordinadora', 'CAÑAVERAL VILLANUEVA (VALLE)', 'CAÑAVERAL VILLANUEVA', 'VALLE'),
  ('coordinadora', 'CEBADAL (NAR)', 'CEBADAL', 'NAR'),
  ('coordinadora', 'CERETE (CORD)', 'CERETE', 'CORD'),
  ('coordinadora', 'CERINZA (BOY)', 'CERINZA', 'BOY'),
  ('coordinadora', 'CERRITO (STDER)', 'CERRITO', 'STDER'),
  ('coordinadora', 'CERRO SAN ANTONIO (MG/LENA)', 'CERRO SAN ANTONIO', 'MG/LENA'),
  ('coordinadora', 'CERTEGUI (CHOCO)', 'CERTEGUI', 'CHOCO'),
  ('coordinadora', 'CHACHAGUI (NAR)', 'CHACHAGUI', 'NAR'),
  ('coordinadora', 'CHAGUANI (C/MARCA)', 'CHAGUANI', 'C/MARCA'),
  ('coordinadora', 'CHAPARRAL (TOL)', 'CHAPARRAL', 'TOL'),
  ('coordinadora', 'CHARALA (STDER)', 'CHARALA', 'STDER'),
  ('coordinadora', 'CHENCHE ASOLEADO (TOL)', 'CHENCHE ASOLEADO', 'TOL'),
  ('coordinadora', 'CHIA (C/MARCA)', 'CHIA', 'C/MARCA'),
  ('coordinadora', 'CHICOLOAPAN (MEX)', 'CHICOLOAPAN', 'MEX'),
  ('coordinadora', 'CHICORAL (TOL)', 'CHICORAL', 'TOL'),
  ('coordinadora', 'CHIGORODO (ANT)', 'CHIGORODO', 'ANT'),
  ('coordinadora', 'CHIMA (CORD)', 'CHIMA', 'CORD'),
  ('coordinadora', 'CHIMALHUACAN (MEX)', 'CHIMALHUACAN', 'MEX'),
  ('coordinadora', 'CHIMICHAGUA (CES)', 'CHIMICHAGUA', 'CES'),
  ('coordinadora', 'CHINACOTA (N/STDER)', 'CHINACOTA', 'N/STDER'),
  ('coordinadora', 'CHINAUTA (C/MARCA)', 'CHINAUTA', 'C/MARCA'),
  ('coordinadora', 'CHINAVITA (BOY)', 'CHINAVITA', 'BOY'),
  ('coordinadora', 'CHINCHINA (CDAS)', 'CHINCHINA', 'CDAS'),
  ('coordinadora', 'CHINU (CORD)', 'CHINU', 'CORD'),
  ('coordinadora', 'CHIPAQUE (C/MARCA)', 'CHIPAQUE', 'C/MARCA'),
  ('coordinadora', 'CHIPATA (STDER)', 'CHIPATA', 'STDER'),
  ('coordinadora', 'CHIPUELO ORIENTE (TOL)', 'CHIPUELO ORIENTE', 'TOL'),
  ('coordinadora', 'CHIQUINQUIRA (BOY)', 'CHIQUINQUIRA', 'BOY'),
  ('coordinadora', 'CHIQUIZA (BOY)', 'CHIQUIZA', 'BOY'),
  ('coordinadora', 'CHIRIGUANA (CES)', 'CHIRIGUANA', 'CES'),
  ('coordinadora', 'CHISCAS (BOY)', 'CHISCAS', 'BOY'),
  ('coordinadora', 'CHITA (BOY)', 'CHITA', 'BOY'),
  ('coordinadora', 'CHITAGA (N/STDER)', 'CHITAGA', 'N/STDER'),
  ('coordinadora', 'CHITARAQUE (BOY)', 'CHITARAQUE', 'BOY'),
  ('coordinadora', 'CHIVATA (BOY)', 'CHIVATA', 'BOY'),
  ('coordinadora', 'CHIVOLO (MG/LENA)', 'CHIVOLO', 'MG/LENA'),
  ('coordinadora', 'CHIVOR (BOY)', 'CHIVOR', 'BOY'),
  ('coordinadora', 'CHOACHI (C/MARCA)', 'CHOACHI', 'C/MARCA'),
  ('coordinadora', 'CHOCONTA (C/MARCA)', 'CHOCONTA', 'C/MARCA'),
  ('coordinadora', 'CHUCUNES (NAR)', 'CHUCUNES', 'NAR'),
  ('coordinadora', 'CHUSACA (C/MARCA)', 'CHUSACA', 'C/MARCA'),
  ('coordinadora', 'CICUCO (BOL)', 'CICUCO', 'BOL'),
  ('coordinadora', 'CIENAGA (MG/LENA)', 'CIENAGA', 'MG/LENA'),
  ('coordinadora', 'CIENAGA DE ORO (CORD)', 'CIENAGA DE ORO', 'CORD'),
  ('coordinadora', 'CIENAGA HONDA (CAU)', 'CIENAGA HONDA', 'CAU'),
  ('coordinadora', 'CIENEGA (BOY)', 'CIENEGA', 'BOY'),
  ('coordinadora', 'CIMITARRA (STDER)', 'CIMITARRA', 'STDER'),
  ('coordinadora', 'CIRCASIA (QDIO)', 'CIRCASIA', 'QDIO'),
  ('coordinadora', 'CISNEROS (ANT)', 'CISNEROS', 'ANT'),
  ('coordinadora', 'CISNEROS (VALLE)', 'CISNEROS', 'VALLE'),
  ('coordinadora', 'CIUDAD BOLIVAR (ANT)', 'CIUDAD BOLIVAR', 'ANT'),
  ('coordinadora', 'CLEMENCIA (BOL)', 'CLEMENCIA', 'BOL'),
  ('coordinadora', 'COACALCO DE BERRIOZABAL (MEX)', 'COACALCO DE BERRIOZABAL', 'MEX'),
  ('coordinadora', 'COCONUCO (CAU)', 'COCONUCO', 'CAU'),
  ('coordinadora', 'COCORNA (ANT)', 'COCORNA', 'ANT'),
  ('coordinadora', 'CODAZZI- AGUSTIN (CES)', 'CODAZZI- AGUSTIN', 'CES'),
  ('coordinadora', 'COELLO (TOL)', 'COELLO', 'TOL'),
  ('coordinadora', 'COELLO - COCORA (TOL)', 'COELLO - COCORA', 'TOL'),
  ('coordinadora', 'COGUA (C/MARCA)', 'COGUA', 'C/MARCA');

INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'COLOMBIA (ATL)', 'COLOMBIA', 'ATL'),
  ('coordinadora', 'COLOMBIA (HLA)', 'COLOMBIA', 'HLA'),
  ('coordinadora', 'COLOMBOY (CORD)', 'COLOMBOY', 'CORD'),
  ('coordinadora', 'COLON (P/MAYO)', 'COLON', 'P/MAYO'),
  ('coordinadora', 'COMBITA (BOY)', 'COMBITA', 'BOY'),
  ('coordinadora', 'CONCEPCION (ANT)', 'CONCEPCION', 'ANT'),
  ('coordinadora', 'CONCEPCION (STDER)', 'CONCEPCION', 'STDER'),
  ('coordinadora', 'CONCORDIA (ANT)', 'CONCORDIA', 'ANT'),
  ('coordinadora', 'CONDOTO (CHOCO)', 'CONDOTO', 'CHOCO'),
  ('coordinadora', 'CONSACA (NAR)', 'CONSACA', 'NAR'),
  ('coordinadora', 'CONTADERO (NAR)', 'CONTADERO', 'NAR'),
  ('coordinadora', 'CONTRATACION (STDER)', 'CONTRATACION', 'STDER'),
  ('coordinadora', 'CONVENCION (N/STDER)', 'CONVENCION', 'N/STDER'),
  ('coordinadora', 'CONVENIO (TOL)', 'CONVENIO', 'TOL'),
  ('coordinadora', 'COPACABANA (ANT)', 'COPACABANA', 'ANT'),
  ('coordinadora', 'COPER (BOY)', 'COPER', 'BOY'),
  ('coordinadora', 'CORDOBA (BOL)', 'CORDOBA', 'BOL'),
  ('coordinadora', 'CORDOBA (NAR)', 'CORDOBA', 'NAR'),
  ('coordinadora', 'CORDOBA (QDIO)', 'CORDOBA', 'QDIO'),
  ('coordinadora', 'CORINTO (CAU)', 'CORINTO', 'CAU'),
  ('coordinadora', 'COROZAL (SUCRE)', 'COROZAL', 'SUCRE'),
  ('coordinadora', 'CORRAL DE SAN LUIS (ATL)', 'CORRAL DE SAN LUIS', 'ATL'),
  ('coordinadora', 'CORRALEJAS (C/MARCA)', 'CORRALEJAS', 'C/MARCA'),
  ('coordinadora', 'CORRALES (BOY)', 'CORRALES', 'BOY'),
  ('coordinadora', 'COSCUEZ (BOY)', 'COSCUEZ', 'BOY'),
  ('coordinadora', 'COSTA RICA (VALLE)', 'COSTA RICA', 'VALLE'),
  ('coordinadora', 'COTA (C/MARCA)', 'COTA', 'C/MARCA'),
  ('coordinadora', 'COTORRA (CORD)', 'COTORRA', 'CORD'),
  ('coordinadora', 'COVARACHIA (BOY)', 'COVARACHIA', 'BOY'),
  ('coordinadora', 'COVEÑAS (SUCRE)', 'COVEÑAS', 'SUCRE'),
  ('coordinadora', 'COYAIMA (TOL)', 'COYAIMA', 'TOL'),
  ('coordinadora', 'COYOACAN (CMX)', 'COYOACAN', 'CMX'),
  ('coordinadora', 'COYOTEPEC (MEX)', 'COYOTEPEC', 'MEX'),
  ('coordinadora', 'CRAVO NORTE (ARAU)', 'CRAVO NORTE', 'ARAU'),
  ('coordinadora', 'CRIOLLO (HLA)', 'CRIOLLO', 'HLA'),
  ('coordinadora', 'CRUCERO DE GUALI (CAU)', 'CRUCERO DE GUALI', 'CAU'),
  ('coordinadora', 'CUAJIMALPA DE MORELOS (CMX)', 'CUAJIMALPA DE MORELOS', 'CMX'),
  ('coordinadora', 'CUATRO ESQUINAS (NAR)', 'CUATRO ESQUINAS', 'NAR'),
  ('coordinadora', 'CUATRO VIENTOS (CES)', 'CUATRO VIENTOS', 'CES'),
  ('coordinadora', 'CUAUHTEMOC (CMX)', 'CUAUHTEMOC', 'CMX'),
  ('coordinadora', 'CUAUTITLAN (MEX)', 'CUAUTITLAN', 'MEX'),
  ('coordinadora', 'CUAUTITLAN IZCALLI (MEX)', 'CUAUTITLAN IZCALLI', 'MEX'),
  ('coordinadora', 'CUBARA (BOY)', 'CUBARA', 'BOY'),
  ('coordinadora', 'CUBARRAL SAN LUIS (META)', 'CUBARRAL SAN LUIS', 'META'),
  ('coordinadora', 'CUCAITA (BOY)', 'CUCAITA', 'BOY'),
  ('coordinadora', 'CUCUNUBA (C/MARCA)', 'CUCUNUBA', 'C/MARCA'),
  ('coordinadora', 'CUCUTA (N/STDER)', 'CUCUTA', 'N/STDER'),
  ('coordinadora', 'CUCUTILLA (N/STDER)', 'CUCUTILLA', 'N/STDER'),
  ('coordinadora', 'CUITIVA (BOY)', 'CUITIVA', 'BOY'),
  ('coordinadora', 'CUMACA (C/MARCA)', 'CUMACA', 'C/MARCA'),
  ('coordinadora', 'CUMARAL (META)', 'CUMARAL', 'META'),
  ('coordinadora', 'CUMARIBO (VICH)', 'CUMARIBO', 'VICH'),
  ('coordinadora', 'CUMBAL (NAR)', 'CUMBAL', 'NAR'),
  ('coordinadora', 'CUMBITARA (NAR)', 'CUMBITARA', 'NAR'),
  ('coordinadora', 'CUNDAY (TOL)', 'CUNDAY', 'TOL'),
  ('coordinadora', 'CUPIAGUA (C/NARE)', 'CUPIAGUA', 'C/NARE'),
  ('coordinadora', 'CURILLO (CAQ)', 'CURILLO', 'CAQ'),
  ('coordinadora', 'CURITI (STDER)', 'CURITI', 'STDER'),
  ('coordinadora', 'CURRULAO (ANT)', 'CURRULAO', 'ANT'),
  ('coordinadora', 'CURUMANI (CES)', 'CURUMANI', 'CES'),
  ('coordinadora', 'CUSIANA POZO (C/NARE)', 'CUSIANA POZO', 'C/NARE'),
  ('coordinadora', 'DABEIBA (ANT)', 'DABEIBA', 'ANT'),
  ('coordinadora', 'DAGUA (VALLE)', 'DAGUA', 'VALLE'),
  ('coordinadora', 'DARIEN (VALLE)', 'DARIEN', 'VALLE'),
  ('coordinadora', 'DAZA (NAR)', 'DAZA', 'NAR'),
  ('coordinadora', 'DISTRACCION (GUAJ)', 'DISTRACCION', 'GUAJ'),
  ('coordinadora', 'DOIMA (TOL)', 'DOIMA', 'TOL'),
  ('coordinadora', 'DOLORES (TOL)', 'DOLORES', 'TOL'),
  ('coordinadora', 'DON ALONSO (SUCRE)', 'DON ALONSO', 'SUCRE'),
  ('coordinadora', 'DON MATIAS (ANT)', 'DON MATIAS', 'ANT'),
  ('coordinadora', 'DORADAL (ANT)', 'DORADAL', 'ANT'),
  ('coordinadora', 'DOSQUEBRADAS (RS)', 'DOSQUEBRADAS', 'RS'),
  ('coordinadora', 'DUITAMA (BOY)', 'DUITAMA', 'BOY'),
  ('coordinadora', 'DURANIA (N/STDER)', 'DURANIA', 'N/STDER'),
  ('coordinadora', 'EBEJICO (ANT)', 'EBEJICO', 'ANT'),
  ('coordinadora', 'ECATEPEC DE MORELOS (MEX)', 'ECATEPEC DE MORELOS', 'MEX'),
  ('coordinadora', 'EL AGUILA (VALLE)', 'EL AGUILA', 'VALLE'),
  ('coordinadora', 'EL BAGRE (ANT)', 'EL BAGRE', 'ANT'),
  ('coordinadora', 'EL BANCO (MG/LENA)', 'EL BANCO', 'MG/LENA'),
  ('coordinadora', 'EL BAURA (TOL)', 'EL BAURA', 'TOL'),
  ('coordinadora', 'EL BORDO (CAU)', 'EL BORDO', 'CAU'),
  ('coordinadora', 'EL CAIRO (VALLE)', 'EL CAIRO', 'VALLE'),
  ('coordinadora', 'EL CARITO (CORD)', 'EL CARITO', 'CORD'),
  ('coordinadora', 'EL CARMELO (VALLE)', 'EL CARMELO', 'VALLE'),
  ('coordinadora', 'EL CARMEN (N/STDER)', 'EL CARMEN', 'N/STDER'),
  ('coordinadora', 'EL CARMEN (VALLE)', 'EL CARMEN', 'VALLE'),
  ('coordinadora', 'EL CARMEN DE ATRATO (CHOCO)', 'EL CARMEN DE ATRATO', 'CHOCO'),
  ('coordinadora', 'EL CARMEN DE BOLIVAR (BOL)', 'EL CARMEN DE BOLIVAR', 'BOL'),
  ('coordinadora', 'EL CARMEN DE CHUCURI (STDER)', 'EL CARMEN DE CHUCURI', 'STDER'),
  ('coordinadora', 'EL CARMEN DE VIBORAL (ANT)', 'EL CARMEN DE VIBORAL', 'ANT'),
  ('coordinadora', 'EL CASTILLO (QDIO)', 'EL CASTILLO', 'QDIO'),
  ('coordinadora', 'EL CENTRO (STDER)', 'EL CENTRO', 'STDER'),
  ('coordinadora', 'EL CERRITO (VALLE)', 'EL CERRITO', 'VALLE'),
  ('coordinadora', 'EL CHARCO (NAR)', 'EL CHARCO', 'NAR'),
  ('coordinadora', 'EL CHARQUITO (C/MARCA)', 'EL CHARQUITO', 'C/MARCA'),
  ('coordinadora', 'EL COCUY (BOY)', 'EL COCUY', 'BOY'),
  ('coordinadora', 'EL COLEGIO MESITAS (C/MARCA)', 'EL COLEGIO MESITAS', 'C/MARCA'),
  ('coordinadora', 'EL COPEY (CES)', 'EL COPEY', 'CES'),
  ('coordinadora', 'EL DIFICIL (MG/LENA)', 'EL DIFICIL', 'MG/LENA'),
  ('coordinadora', 'EL DIVISO (NAR)', 'EL DIVISO', 'NAR');

INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'EL DOCE (ANT)', 'EL DOCE', 'ANT'),
  ('coordinadora', 'EL DONCELLO (CAQ)', 'EL DONCELLO', 'CAQ'),
  ('coordinadora', 'EL DOVIO (VALLE)', 'EL DOVIO', 'VALLE'),
  ('coordinadora', 'EL ENCANO (NAR)', 'EL ENCANO', 'NAR'),
  ('coordinadora', 'EL ERMITAÑO (BOY)', 'EL ERMITAÑO', 'BOY'),
  ('coordinadora', 'EL ESPINO (BOY)', 'EL ESPINO', 'BOY'),
  ('coordinadora', 'EL ESPINO (NAR)', 'EL ESPINO', 'NAR'),
  ('coordinadora', 'EL ESTRECHO (CAU)', 'EL ESTRECHO', 'CAU'),
  ('coordinadora', 'EL GUAMO (BOL)', 'EL GUAMO', 'BOL'),
  ('coordinadora', 'EL GUASIMO (CAU)', 'EL GUASIMO', 'CAU'),
  ('coordinadora', 'EL HATICO (GUAJ)', 'EL HATICO', 'GUAJ'),
  ('coordinadora', 'EL LAUREL (QDIO)', 'EL LAUREL', 'QDIO'),
  ('coordinadora', 'EL LIMON (TOL)', 'EL LIMON', 'TOL'),
  ('coordinadora', 'EL LLANITO (CAU)', 'EL LLANITO', 'CAU'),
  ('coordinadora', 'EL LLANO (CDAS)', 'EL LLANO', 'CDAS'),
  ('coordinadora', 'EL MARFIL (BOY)', 'EL MARFIL', 'BOY'),
  ('coordinadora', 'EL MOLINO (GUAJ)', 'EL MOLINO', 'GUAJ'),
  ('coordinadora', 'EL MORRO (C/NARE)', 'EL MORRO', 'C/NARE'),
  ('coordinadora', 'EL NARANJAL (CAU)', 'EL NARANJAL', 'CAU'),
  ('coordinadora', 'EL OLIVO (C/MARCA)', 'EL OLIVO', 'C/MARCA'),
  ('coordinadora', 'EL ORATORIO (C/MARCA)', 'EL ORATORIO', 'C/MARCA'),
  ('coordinadora', 'EL PALMAR (MG/LENA)', 'EL PALMAR', 'MG/LENA'),
  ('coordinadora', 'EL PALMAR (VALLE)', 'EL PALMAR', 'VALLE'),
  ('coordinadora', 'EL PASO (CES)', 'EL PASO', 'CES'),
  ('coordinadora', 'EL PATIA (CAU)', 'EL PATIA', 'CAU'),
  ('coordinadora', 'EL PAUJIL (CAQ)', 'EL PAUJIL', 'CAQ'),
  ('coordinadora', 'EL PEPINO (P/MAYO)', 'EL PEPINO', 'P/MAYO'),
  ('coordinadora', 'EL PEÑOL (ANT)', 'EL PEÑOL', 'ANT'),
  ('coordinadora', 'EL PEÑOL (NAR)', 'EL PEÑOL', 'NAR'),
  ('coordinadora', 'EL PEÑON (STDER)', 'EL PEÑON', 'STDER'),
  ('coordinadora', 'EL PEÑÓN (C/MARCA)', 'EL PEÑÓN', 'C/MARCA'),
  ('coordinadora', 'EL PITAL (CAU)', 'EL PITAL', 'CAU'),
  ('coordinadora', 'EL PIÑAL (C/MARCA)', 'EL PIÑAL', 'C/MARCA'),
  ('coordinadora', 'EL PIÑON (MG/LENA)', 'EL PIÑON', 'MG/LENA'),
  ('coordinadora', 'EL PLACER (VALLE)', 'EL PLACER', 'VALLE'),
  ('coordinadora', 'EL PLAYON (STDER)', 'EL PLAYON', 'STDER'),
  ('coordinadora', 'EL PORTAL (C/MARCA)', 'EL PORTAL', 'C/MARCA'),
  ('coordinadora', 'EL PORVENIR (C/MARCA)', 'EL PORVENIR', 'C/MARCA'),
  ('coordinadora', 'EL QUEREMAL (VALLE)', 'EL QUEREMAL', 'VALLE'),
  ('coordinadora', 'EL REMOLINO (NAR)', 'EL REMOLINO', 'NAR'),
  ('coordinadora', 'EL REPOSO (ANT)', 'EL REPOSO', 'ANT'),
  ('coordinadora', 'EL RETEN (MG/LENA)', 'EL RETEN', 'MG/LENA'),
  ('coordinadora', 'EL ROSAL (C/MARCA)', 'EL ROSAL', 'C/MARCA'),
  ('coordinadora', 'EL ROSARIO (NAR)', 'EL ROSARIO', 'NAR'),
  ('coordinadora', 'EL SANTUARIO (ANT)', 'EL SANTUARIO', 'ANT'),
  ('coordinadora', 'EL SIETE (CHOCO)', 'EL SIETE', 'CHOCO'),
  ('coordinadora', 'EL SISGA (C/MARCA)', 'EL SISGA', 'C/MARCA'),
  ('coordinadora', 'EL TABLAZO (TOL)', 'EL TABLAZO', 'TOL'),
  ('coordinadora', 'EL TABLON DE GOMEZ (NAR)', 'EL TABLON DE GOMEZ', 'NAR'),
  ('coordinadora', 'EL TAJO (CAU)', 'EL TAJO', 'CAU'),
  ('coordinadora', 'EL TAMBO (CAU)', 'EL TAMBO', 'CAU'),
  ('coordinadora', 'EL TAMBO (NAR)', 'EL TAMBO', 'NAR'),
  ('coordinadora', 'EL TIGRE (ANT)', 'EL TIGRE', 'ANT'),
  ('coordinadora', 'EL TIGRE (P/MAYO)', 'EL TIGRE', 'P/MAYO'),
  ('coordinadora', 'EL TOTUMO (TOL)', 'EL TOTUMO', 'TOL'),
  ('coordinadora', 'EL TREBOL (CDAS)', 'EL TREBOL', 'CDAS'),
  ('coordinadora', 'EL TRES (ANT)', 'EL TRES', 'ANT'),
  ('coordinadora', 'EL TRIQUE (BOY)', 'EL TRIQUE', 'BOY'),
  ('coordinadora', 'EL TRIUNFO (C/MARCA)', 'EL TRIUNFO', 'C/MARCA'),
  ('coordinadora', 'EL VARAL (CORD)', 'EL VARAL', 'CORD'),
  ('coordinadora', 'EL VIAJANO (CORD)', 'EL VIAJANO', 'CORD'),
  ('coordinadora', 'EL ZULIA (N/STDER)', 'EL ZULIA', 'N/STDER'),
  ('coordinadora', 'ENCISO (STDER)', 'ENCISO', 'STDER'),
  ('coordinadora', 'ENTRERRIOS (ANT)', 'ENTRERRIOS', 'ANT'),
  ('coordinadora', 'ENVIGADO (ANT)', 'ENVIGADO', 'ANT'),
  ('coordinadora', 'ESPINAL (TOL)', 'ESPINAL', 'TOL'),
  ('coordinadora', 'ESPRIELLA (NAR)', 'ESPRIELLA', 'NAR'),
  ('coordinadora', 'EVITAR (BOL)', 'EVITAR', 'BOL'),
  ('coordinadora', 'FACATATIVA (C/MARCA)', 'FACATATIVA', 'C/MARCA'),
  ('coordinadora', 'FALAN (TOL)', 'FALAN', 'TOL'),
  ('coordinadora', 'FELIDIA (VALLE)', 'FELIDIA', 'VALLE'),
  ('coordinadora', 'FENICIA (VALLE)', 'FENICIA', 'VALLE'),
  ('coordinadora', 'FILADELFIA (CDAS)', 'FILADELFIA', 'CDAS'),
  ('coordinadora', 'FILANDIA (QDIO)', 'FILANDIA', 'QDIO'),
  ('coordinadora', 'FIRAVITOBA (BOY)', 'FIRAVITOBA', 'BOY'),
  ('coordinadora', 'FLANDES (TOL)', 'FLANDES', 'TOL'),
  ('coordinadora', 'FLORENCIA (CAQ)', 'FLORENCIA', 'CAQ'),
  ('coordinadora', 'FLORENCIA (CAU)', 'FLORENCIA', 'CAU'),
  ('coordinadora', 'FLORENCIA (CDAS)', 'FLORENCIA', 'CDAS'),
  ('coordinadora', 'FLORESTA (BOY)', 'FLORESTA', 'BOY'),
  ('coordinadora', 'FLORIAN (STDER)', 'FLORIAN', 'STDER'),
  ('coordinadora', 'FLORIDA (VALLE)', 'FLORIDA', 'VALLE'),
  ('coordinadora', 'FLORIDABLANCA (STDER)', 'FLORIDABLANCA', 'STDER'),
  ('coordinadora', 'FOMEQUE (C/MARCA)', 'FOMEQUE', 'C/MARCA'),
  ('coordinadora', 'FONSECA (GUAJ)', 'FONSECA', 'GUAJ'),
  ('coordinadora', 'FORTALECILLAS (HLA)', 'FORTALECILLAS', 'HLA'),
  ('coordinadora', 'FORTUL (ARAU)', 'FORTUL', 'ARAU'),
  ('coordinadora', 'FOSCA (C/MARCA)', 'FOSCA', 'C/MARCA'),
  ('coordinadora', 'FREDONIA (ANT)', 'FREDONIA', 'ANT'),
  ('coordinadora', 'FRESNO (TOL)', 'FRESNO', 'TOL'),
  ('coordinadora', 'FRIAS (TOL)', 'FRIAS', 'TOL'),
  ('coordinadora', 'FRONTINO (ANT)', 'FRONTINO', 'ANT'),
  ('coordinadora', 'FUENTE DE ORO (META)', 'FUENTE DE ORO', 'META'),
  ('coordinadora', 'FUNDACION (MG/LENA)', 'FUNDACION', 'MG/LENA'),
  ('coordinadora', 'FUNDADORES (TOL)', 'FUNDADORES', 'TOL'),
  ('coordinadora', 'FUNES (NAR)', 'FUNES', 'NAR'),
  ('coordinadora', 'FUNZA (C/MARCA)', 'FUNZA', 'C/MARCA'),
  ('coordinadora', 'FUQUENE (C/MARCA)', 'FUQUENE', 'C/MARCA'),
  ('coordinadora', 'FUSAGASUGA (C/MARCA)', 'FUSAGASUGA', 'C/MARCA'),
  ('coordinadora', 'GACHALA (C/MARCA)', 'GACHALA', 'C/MARCA');

INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'GACHANCIPA (C/MARCA)', 'GACHANCIPA', 'C/MARCA'),
  ('coordinadora', 'GACHANTIVA (BOY)', 'GACHANTIVA', 'BOY'),
  ('coordinadora', 'GACHETA (C/MARCA)', 'GACHETA', 'C/MARCA'),
  ('coordinadora', 'GAIRA (MG/LENA)', 'GAIRA', 'MG/LENA'),
  ('coordinadora', 'GAITANIA (TOL)', 'GAITANIA', 'TOL'),
  ('coordinadora', 'GALAN (STDER)', 'GALAN', 'STDER'),
  ('coordinadora', 'GALAPA (ATL)', 'GALAPA', 'ATL'),
  ('coordinadora', 'GALERAS (SUCRE)', 'GALERAS', 'SUCRE'),
  ('coordinadora', 'GALERAZAMBA (BOL)', 'GALERAZAMBA', 'BOL'),
  ('coordinadora', 'GALINDEZ (CAU)', 'GALINDEZ', 'CAU'),
  ('coordinadora', 'GAMA (C/MARCA)', 'GAMA', 'C/MARCA'),
  ('coordinadora', 'GAMARRA (CES)', 'GAMARRA', 'CES'),
  ('coordinadora', 'GAMBITA (STDER)', 'GAMBITA', 'STDER'),
  ('coordinadora', 'GAMEZA (BOY)', 'GAMEZA', 'BOY'),
  ('coordinadora', 'GARAGOA (BOY)', 'GARAGOA', 'BOY'),
  ('coordinadora', 'GARZON (HLA)', 'GARZON', 'HLA'),
  ('coordinadora', 'GATO NEGRO (VALLE)', 'GATO NEGRO', 'VALLE'),
  ('coordinadora', 'GENOVA (NAR)', 'GENOVA', 'NAR'),
  ('coordinadora', 'GENOVA (QDIO)', 'GENOVA', 'QDIO'),
  ('coordinadora', 'GENOY (NAR)', 'GENOY', 'NAR'),
  ('coordinadora', 'GIGANTE (HLA)', 'GIGANTE', 'HLA'),
  ('coordinadora', 'GINEBRA (VALLE)', 'GINEBRA', 'VALLE'),
  ('coordinadora', 'GIRALDO (ANT)', 'GIRALDO', 'ANT'),
  ('coordinadora', 'GIRARDOT (C/MARCA)', 'GIRARDOT', 'C/MARCA'),
  ('coordinadora', 'GIRARDOTA (ANT)', 'GIRARDOTA', 'ANT'),
  ('coordinadora', 'GIRON (STDER)', 'GIRON', 'STDER'),
  ('coordinadora', 'GOMEZ PLATA (ANT)', 'GOMEZ PLATA', 'ANT'),
  ('coordinadora', 'GONZALEZ (CES)', 'GONZALEZ', 'CES'),
  ('coordinadora', 'GRAMALOTE (N/STDER)', 'GRAMALOTE', 'N/STDER'),
  ('coordinadora', 'GRANADA (ANT)', 'GRANADA', 'ANT'),
  ('coordinadora', 'GRANADA (C/MARCA)', 'GRANADA', 'C/MARCA'),
  ('coordinadora', 'GRANADA (META)', 'GRANADA', 'META'),
  ('coordinadora', 'GUACA (STDER)', 'GUACA', 'STDER'),
  ('coordinadora', 'GUACAMAYAL (MG/LENA)', 'GUACAMAYAL', 'MG/LENA'),
  ('coordinadora', 'GUACAMAYAS (BOY)', 'GUACAMAYAS', 'BOY'),
  ('coordinadora', 'GUACARI (VALLE)', 'GUACARI', 'VALLE'),
  ('coordinadora', 'GUACHAVEZ SAN CRUZ (NAR)', 'GUACHAVEZ SAN CRUZ', 'NAR'),
  ('coordinadora', 'GUACHENE (CAU)', 'GUACHENE', 'CAU'),
  ('coordinadora', 'GUACHETA (C/MARCA)', 'GUACHETA', 'C/MARCA'),
  ('coordinadora', 'GUACHIPAS (C/MARCA)', 'GUACHIPAS', 'C/MARCA'),
  ('coordinadora', 'GUACHUCAL (NAR)', 'GUACHUCAL', 'NAR'),
  ('coordinadora', 'GUACIRCO (HLA)', 'GUACIRCO', 'HLA'),
  ('coordinadora', 'GUADALUPE (ANT)', 'GUADALUPE', 'ANT'),
  ('coordinadora', 'GUADALUPE (HLA)', 'GUADALUPE', 'HLA'),
  ('coordinadora', 'GUADALUPE (STDER)', 'GUADALUPE', 'STDER'),
  ('coordinadora', 'GUADUAS (C/MARCA)', 'GUADUAS', 'C/MARCA'),
  ('coordinadora', 'GUAITARILLA (NAR)', 'GUAITARILLA', 'NAR'),
  ('coordinadora', 'GUALANDAY (TOL)', 'GUALANDAY', 'TOL'),
  ('coordinadora', 'GUALMATAN (NAR)', 'GUALMATAN', 'NAR'),
  ('coordinadora', 'GUAMAL (CDAS)', 'GUAMAL', 'CDAS'),
  ('coordinadora', 'GUAMAL (META)', 'GUAMAL', 'META'),
  ('coordinadora', 'GUAMAL (MG/LENA)', 'GUAMAL', 'MG/LENA'),
  ('coordinadora', 'GUAMO (TOL)', 'GUAMO', 'TOL'),
  ('coordinadora', 'GUAPI (CAU)', 'GUAPI', 'CAU'),
  ('coordinadora', 'GUARANDA (SUCRE)', 'GUARANDA', 'SUCRE'),
  ('coordinadora', 'GUARATO (CHOCO)', 'GUARATO', 'CHOCO'),
  ('coordinadora', 'GUARINOCITO (CDAS)', 'GUARINOCITO', 'CDAS'),
  ('coordinadora', 'GUARNE (ANT)', 'GUARNE', 'ANT'),
  ('coordinadora', 'GUARUMO (ANT)', 'GUARUMO', 'ANT'),
  ('coordinadora', 'GUASCA (C/MARCA)', 'GUASCA', 'C/MARCA'),
  ('coordinadora', 'GUATACA (BOL)', 'GUATACA', 'BOL'),
  ('coordinadora', 'GUATAPE (ANT)', 'GUATAPE', 'ANT'),
  ('coordinadora', 'GUATAQUI (C/MARCA)', 'GUATAQUI', 'C/MARCA'),
  ('coordinadora', 'GUATAVITA (C/MARCA)', 'GUATAVITA', 'C/MARCA'),
  ('coordinadora', 'GUATEQUE (BOY)', 'GUATEQUE', 'BOY'),
  ('coordinadora', 'GUATICA (RS)', 'GUATICA', 'RS'),
  ('coordinadora', 'GUAVATA (STDER)', 'GUAVATA', 'STDER'),
  ('coordinadora', 'GUAYABAL (HLA)', 'GUAYABAL', 'HLA'),
  ('coordinadora', 'GUAYABAL DE SIQUIMA (C/MARCA)', 'GUAYABAL DE SIQUIMA', 'C/MARCA'),
  ('coordinadora', 'GUAYABETAL (C/MARCA)', 'GUAYABETAL', 'C/MARCA'),
  ('coordinadora', 'GUAYATA (BOY)', 'GUAYATA', 'BOY'),
  ('coordinadora', 'GUEPSA (STDER)', 'GUEPSA', 'STDER'),
  ('coordinadora', 'GUICAN (BOY)', 'GUICAN', 'BOY'),
  ('coordinadora', 'GUSTAVO A MADERO (CMX)', 'GUSTAVO A MADERO', 'CMX'),
  ('coordinadora', 'GUTIERREZ (C/MARCA)', 'GUTIERREZ', 'C/MARCA'),
  ('coordinadora', 'HATILLO DE LOBA (BOL)', 'HATILLO DE LOBA', 'BOL'),
  ('coordinadora', 'HATO COROZAL (C/NARE)', 'HATO COROZAL', 'C/NARE'),
  ('coordinadora', 'HATO DE IGLESIA (TOL)', 'HATO DE IGLESIA', 'TOL'),
  ('coordinadora', 'HATO GRANDE (C/MARCA)', 'HATO GRANDE', 'C/MARCA'),
  ('coordinadora', 'HATO NUEVO (GUAJ)', 'HATO NUEVO', 'GUAJ'),
  ('coordinadora', 'HELICONIA (ANT)', 'HELICONIA', 'ANT'),
  ('coordinadora', 'HERBEO (TOL)', 'HERBEO', 'TOL'),
  ('coordinadora', 'HERRAN (N/STDER)', 'HERRAN', 'N/STDER'),
  ('coordinadora', 'HERRERA (TOL)', 'HERRERA', 'TOL'),
  ('coordinadora', 'HIGUERONCITO (VALLE)', 'HIGUERONCITO', 'VALLE'),
  ('coordinadora', 'HISPANIA (ANT)', 'HISPANIA', 'ANT'),
  ('coordinadora', 'HOBO (HLA)', 'HOBO', 'HLA'),
  ('coordinadora', 'HOLGUIN (VALLE)', 'HOLGUIN', 'VALLE'),
  ('coordinadora', 'HONDA (TOL)', 'HONDA', 'TOL'),
  ('coordinadora', 'HUEHUETOCA (MEX)', 'HUEHUETOCA', 'MEX'),
  ('coordinadora', 'HUIXQUILUCAN (MEX)', 'HUIXQUILUCAN', 'MEX'),
  ('coordinadora', 'IBAGUE (TOL)', 'IBAGUE', 'TOL'),
  ('coordinadora', 'ICONONZO (TOL)', 'ICONONZO', 'TOL'),
  ('coordinadora', 'IGUASITOS (TOL)', 'IGUASITOS', 'TOL'),
  ('coordinadora', 'ILES (NAR)', 'ILES', 'NAR'),
  ('coordinadora', 'IMBILI (NAR)', 'IMBILI', 'NAR'),
  ('coordinadora', 'IMUES (NAR)', 'IMUES', 'NAR'),
  ('coordinadora', 'INIRIDA (GUAI)', 'INIRIDA', 'GUAI'),
  ('coordinadora', 'INZA (CAU)', 'INZA', 'CAU'),
  ('coordinadora', 'IPIALES (NAR)', 'IPIALES', 'NAR');

INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'IQUIRA (HLA)', 'IQUIRA', 'HLA'),
  ('coordinadora', 'IRRA (RS)', 'IRRA', 'RS'),
  ('coordinadora', 'ISABEL LOPEZ (ATL)', 'ISABEL LOPEZ', 'ATL'),
  ('coordinadora', 'ISTMINA (CHOCO)', 'ISTMINA', 'CHOCO'),
  ('coordinadora', 'ITAGUI (ANT)', 'ITAGUI', 'ANT'),
  ('coordinadora', 'ITUANGO (ANT)', 'ITUANGO', 'ANT'),
  ('coordinadora', 'IZA (BOY)', 'IZA', 'BOY'),
  ('coordinadora', 'IZTACALCO (CMX)', 'IZTACALCO', 'CMX'),
  ('coordinadora', 'IZTAPALAPA (CMX)', 'IZTAPALAPA', 'CMX'),
  ('coordinadora', 'JALTENCO (MEX)', 'JALTENCO', 'MEX'),
  ('coordinadora', 'JAMBALO (CAU)', 'JAMBALO', 'CAU'),
  ('coordinadora', 'JAMUNDI (VALLE)', 'JAMUNDI', 'VALLE'),
  ('coordinadora', 'JARDIN CACERES (ANT)', 'JARDIN CACERES', 'ANT'),
  ('coordinadora', 'JARDIN SUROESTE (ANT)', 'JARDIN SUROESTE', 'ANT'),
  ('coordinadora', 'JENESANO (BOY)', 'JENESANO', 'BOY'),
  ('coordinadora', 'JERICO (ANT)', 'JERICO', 'ANT'),
  ('coordinadora', 'JERICO (BOY)', 'JERICO', 'BOY'),
  ('coordinadora', 'JERUSALEN (ANT)', 'JERUSALEN', 'ANT'),
  ('coordinadora', 'JERUSALEN (C/MARCA)', 'JERUSALEN', 'C/MARCA'),
  ('coordinadora', 'JESUS MARIA (STDER)', 'JESUS MARIA', 'STDER'),
  ('coordinadora', 'JOSE MARIA HERNANDEZ (NAR)', 'JOSE MARIA HERNANDEZ', 'NAR'),
  ('coordinadora', 'JUAN ARIAS (BOL)', 'JUAN ARIAS', 'BOL'),
  ('coordinadora', 'JUAN DE ACOSTA (ATL)', 'JUAN DE ACOSTA', 'ATL'),
  ('coordinadora', 'JUAN JOSE (CORD)', 'JUAN JOSE', 'CORD'),
  ('coordinadora', 'JUAN MINA (ATL)', 'JUAN MINA', 'ATL'),
  ('coordinadora', 'JUNIN (C/MARCA)', 'JUNIN', 'C/MARCA'),
  ('coordinadora', 'JUNIN (NAR)', 'JUNIN', 'NAR'),
  ('coordinadora', 'JUNIN (TOL)', 'JUNIN', 'TOL'),
  ('coordinadora', 'JUNTAS (TOL)', 'JUNTAS', 'TOL'),
  ('coordinadora', 'JURADO (CHOCO)', 'JURADO', 'CHOCO'),
  ('coordinadora', 'KILOMETRO DOS Y MEDIO (BOY)', 'KILOMETRO DOS Y MEDIO', 'BOY'),
  ('coordinadora', 'KILOMETRO ONCE (BOY)', 'KILOMETRO ONCE', 'BOY'),
  ('coordinadora', 'KILOMETRO VENTICINCO (BOY)', 'KILOMETRO VENTICINCO', 'BOY'),
  ('coordinadora', 'LA AGUADITA (TOL)', 'LA AGUADITA', 'TOL'),
  ('coordinadora', 'LA APARTADA (CORD)', 'LA APARTADA', 'CORD'),
  ('coordinadora', 'LA ARADA (TOL)', 'LA ARADA', 'TOL'),
  ('coordinadora', 'LA AURORA (CDAS)', 'LA AURORA', 'CDAS'),
  ('coordinadora', 'LA BELLA (QDIO)', 'LA BELLA', 'QDIO'),
  ('coordinadora', 'LA BELLEZA (STDER)', 'LA BELLEZA', 'STDER'),
  ('coordinadora', 'LA BOQUILLA (BOL)', 'LA BOQUILLA', 'BOL'),
  ('coordinadora', 'LA CABAÑA (C/MARCA)', 'LA CABAÑA', 'C/MARCA'),
  ('coordinadora', 'LA CALERA (C/MARCA)', 'LA CALERA', 'C/MARCA'),
  ('coordinadora', 'LA CAPILLA (BOY)', 'LA CAPILLA', 'BOY'),
  ('coordinadora', 'LA CEJA (ANT)', 'LA CEJA', 'ANT'),
  ('coordinadora', 'LA CELIA (RS)', 'LA CELIA', 'RS'),
  ('coordinadora', 'LA CHAMBA (TOL)', 'LA CHAMBA', 'TOL'),
  ('coordinadora', 'LA CHAPARRERA (C/NARE)', 'LA CHAPARRERA', 'C/NARE'),
  ('coordinadora', 'LA COLORADA (C/MARCA)', 'LA COLORADA', 'C/MARCA'),
  ('coordinadora', 'LA CRUZ (NAR)', 'LA CRUZ', 'NAR'),
  ('coordinadora', 'LA CRUZADA (ANT)', 'LA CRUZADA', 'ANT'),
  ('coordinadora', 'LA CUMBRE (VALLE)', 'LA CUMBRE', 'VALLE'),
  ('coordinadora', 'LA DORADA (CDAS)', 'LA DORADA', 'CDAS'),
  ('coordinadora', 'LA DORADA SAN MIGUEL (P/MAYO)', 'LA DORADA SAN MIGUEL', 'P/MAYO'),
  ('coordinadora', 'LA ESMERALDA (ARAU)', 'LA ESMERALDA', 'ARAU'),
  ('coordinadora', 'LA ESMERALDA (C/MARCA)', 'LA ESMERALDA', 'C/MARCA'),
  ('coordinadora', 'LA ESPERANZA (N/STDER)', 'LA ESPERANZA', 'N/STDER'),
  ('coordinadora', 'LA ESTRELLA (ANT)', 'LA ESTRELLA', 'ANT'),
  ('coordinadora', 'LA FELISA (CDAS)', 'LA FELISA', 'CDAS'),
  ('coordinadora', 'LA FLORESTA (CDAS)', 'LA FLORESTA', 'CDAS'),
  ('coordinadora', 'LA FLORIDA (C/MARCA)', 'LA FLORIDA', 'C/MARCA'),
  ('coordinadora', 'LA FLORIDA (NAR)', 'LA FLORIDA', 'NAR'),
  ('coordinadora', 'LA FORTUNA (STDER)', 'LA FORTUNA', 'STDER'),
  ('coordinadora', 'LA GLORIA (CES)', 'LA GLORIA', 'CES'),
  ('coordinadora', 'LA GLORIA (MG/LENA)', 'LA GLORIA', 'MG/LENA'),
  ('coordinadora', 'LA GRAN VIA (C/MARCA)', 'LA GRAN VIA', 'C/MARCA'),
  ('coordinadora', 'LA GRAN VIA (MG/LENA)', 'LA GRAN VIA', 'MG/LENA'),
  ('coordinadora', 'LA GUAFILLA (C/NARE)', 'LA GUAFILLA', 'C/NARE'),
  ('coordinadora', 'LA GUAYACANA (NAR)', 'LA GUAYACANA', 'NAR'),
  ('coordinadora', 'LA HABANA (CDAS)', 'LA HABANA', 'CDAS'),
  ('coordinadora', 'LA HORMIGA - VALLE GUAMUEZ (P/MAYO)', 'LA HORMIGA - VALLE GUAMUEZ', 'P/MAYO'),
  ('coordinadora', 'LA JAGUA DE IBIRICO (CES)', 'LA JAGUA DE IBIRICO', 'CES'),
  ('coordinadora', 'LA JAGUA DEL PILAR (GUAJ)', 'LA JAGUA DEL PILAR', 'GUAJ'),
  ('coordinadora', 'LA LLANADA (NAR)', 'LA LLANADA', 'NAR'),
  ('coordinadora', 'LA LOMA (CES)', 'LA LOMA', 'CES'),
  ('coordinadora', 'LA MACARENA (META)', 'LA MACARENA', 'META'),
  ('coordinadora', 'LA MAGDALENA (C/MARCA)', 'LA MAGDALENA', 'C/MARCA'),
  ('coordinadora', 'LA MAGDALENA CONTRERAS (CMX)', 'LA MAGDALENA CONTRERAS', 'CMX'),
  ('coordinadora', 'LA MAGOLA (C/MARCA)', 'LA MAGOLA', 'C/MARCA'),
  ('coordinadora', 'LA MARINA (RS)', 'LA MARINA', 'RS'),
  ('coordinadora', 'LA MERCED (CDAS)', 'LA MERCED', 'CDAS'),
  ('coordinadora', 'LA MESA (C/MARCA)', 'LA MESA', 'C/MARCA'),
  ('coordinadora', 'LA MONTAÑITA (CAQ)', 'LA MONTAÑITA', 'CAQ'),
  ('coordinadora', 'LA NIATA (C/NARE)', 'LA NIATA', 'C/NARE'),
  ('coordinadora', 'LA PAILA (VALLE)', 'LA PAILA', 'VALLE'),
  ('coordinadora', 'LA PALMA (C/MARCA)', 'LA PALMA', 'C/MARCA'),
  ('coordinadora', 'LA PALMITA (TOL)', 'LA PALMITA', 'TOL'),
  ('coordinadora', 'LA PARROQUIA (TOL)', 'LA PARROQUIA', 'TOL'),
  ('coordinadora', 'LA PAZ (CES)', 'LA PAZ', 'CES'),
  ('coordinadora', 'LA PAZ (MEX)', 'LA PAZ', 'MEX'),
  ('coordinadora', 'LA PAZ (STDER)', 'LA PAZ', 'STDER'),
  ('coordinadora', 'LA PESQUERA (ARAU)', 'LA PESQUERA', 'ARAU'),
  ('coordinadora', 'LA PEÑA (ATL)', 'LA PEÑA', 'ATL'),
  ('coordinadora', 'LA PEÑA (C/MARCA)', 'LA PEÑA', 'C/MARCA'),
  ('coordinadora', 'LA PINTADA (ANT)', 'LA PINTADA', 'ANT'),
  ('coordinadora', 'LA PLATA (CDAS)', 'LA PLATA', 'CDAS'),
  ('coordinadora', 'LA PLATA (HLA)', 'LA PLATA', 'HLA'),
  ('coordinadora', 'LA PLAZUELA (C/MARCA)', 'LA PLAZUELA', 'C/MARCA'),
  ('coordinadora', 'LA PRADERA (CDAS)', 'LA PRADERA', 'CDAS'),
  ('coordinadora', 'LA PRIMAVERA (VICH)', 'LA PRIMAVERA', 'VICH'),
  ('coordinadora', 'LA PUERTA (C/MARCA)', 'LA PUERTA', 'C/MARCA');

INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'LA PUNTA (C/MARCA)', 'LA PUNTA', 'C/MARCA'),
  ('coordinadora', 'LA SALADA (C/MARCA)', 'LA SALADA', 'C/MARCA'),
  ('coordinadora', 'LA SIERRA (ANT)', 'LA SIERRA', 'ANT'),
  ('coordinadora', 'LA SIERRA (CAU)', 'LA SIERRA', 'CAU'),
  ('coordinadora', 'LA SIERRA (TOL)', 'LA SIERRA', 'TOL'),
  ('coordinadora', 'LA TABLAZA (ANT)', 'LA TABLAZA', 'ANT'),
  ('coordinadora', 'LA TEBAIDA (QDIO)', 'LA TEBAIDA', 'QDIO'),
  ('coordinadora', 'LA ULLOA (HLA)', 'LA ULLOA', 'HLA'),
  ('coordinadora', 'LA UNION (ANT)', 'LA UNION', 'ANT'),
  ('coordinadora', 'LA UNION (C/MARCA)', 'LA UNION', 'C/MARCA'),
  ('coordinadora', 'LA UNION (NAR)', 'LA UNION', 'NAR'),
  ('coordinadora', 'LA UNION (SUCRE)', 'LA UNION', 'SUCRE'),
  ('coordinadora', 'LA UNION (VALLE)', 'LA UNION', 'VALLE'),
  ('coordinadora', 'LA UVITA (BOY)', 'LA UVITA', 'BOY'),
  ('coordinadora', 'LA VEGA (C/MARCA)', 'LA VEGA', 'C/MARCA'),
  ('coordinadora', 'LA VEGA (CAU)', 'LA VEGA', 'CAU'),
  ('coordinadora', 'LA VICTORIA (BOY)', 'LA VICTORIA', 'BOY'),
  ('coordinadora', 'LA VICTORIA (C/MARCA)', 'LA VICTORIA', 'C/MARCA'),
  ('coordinadora', 'LA VICTORIA (VALLE)', 'LA VICTORIA', 'VALLE'),
  ('coordinadora', 'LA VIRGINIA (RS)', 'LA VIRGINIA', 'RS'),
  ('coordinadora', 'LA YE (CORD)', 'LA YE', 'CORD'),
  ('coordinadora', 'LA YOPALOSA (C/NARE)', 'LA YOPALOSA', 'C/NARE'),
  ('coordinadora', 'LABATECA (N/STDER)', 'LABATECA', 'N/STDER'),
  ('coordinadora', 'LABRANZAGRANDE (BOY)', 'LABRANZAGRANDE', 'BOY'),
  ('coordinadora', 'LANDAZURI (STDER)', 'LANDAZURI', 'STDER'),
  ('coordinadora', 'LAS CASITAS (CORD)', 'LAS CASITAS', 'CORD'),
  ('coordinadora', 'LAS GUAMAS (CORD)', 'LAS GUAMAS', 'CORD'),
  ('coordinadora', 'LAS ISLAS (C/MARCA)', 'LAS ISLAS', 'C/MARCA'),
  ('coordinadora', 'LAS LAJAS (NAR)', 'LAS LAJAS', 'NAR'),
  ('coordinadora', 'LAS PEÑAS (SUCRE)', 'LAS PEÑAS', 'SUCRE'),
  ('coordinadora', 'LEBRIJA (STDER)', 'LEBRIJA', 'STDER'),
  ('coordinadora', 'LEIVA (NAR)', 'LEIVA', 'NAR'),
  ('coordinadora', 'LEJANIAS (META)', 'LEJANIAS', 'META'),
  ('coordinadora', 'LENGUAZAQUE (C/MARCA)', 'LENGUAZAQUE', 'C/MARCA'),
  ('coordinadora', 'LERIDA (TOL)', 'LERIDA', 'TOL'),
  ('coordinadora', 'LETICIA (AMAZ)', 'LETICIA', 'AMAZ'),
  ('coordinadora', 'LIBANO (TOL)', 'LIBANO', 'TOL'),
  ('coordinadora', 'LIBORINA (ANT)', 'LIBORINA', 'ANT'),
  ('coordinadora', 'LINARES (NAR)', 'LINARES', 'NAR'),
  ('coordinadora', 'LLANADAS (ANT)', 'LLANADAS', 'ANT'),
  ('coordinadora', 'LLANOS DE CUIVA (ANT)', 'LLANOS DE CUIVA', 'ANT'),
  ('coordinadora', 'LLORENTE (NAR)', 'LLORENTE', 'NAR'),
  ('coordinadora', 'LLORO (CHOCO)', 'LLORO', 'CHOCO'),
  ('coordinadora', 'LOBO GUERRERO (VALLE)', 'LOBO GUERRERO', 'VALLE'),
  ('coordinadora', 'LOMA DE ARENA (BOL)', 'LOMA DE ARENA', 'BOL'),
  ('coordinadora', 'LOMA DE SIMON (BOL)', 'LOMA DE SIMON', 'BOL'),
  ('coordinadora', 'LOPEZ DE MICAY (CAU)', 'LOPEZ DE MICAY', 'CAU'),
  ('coordinadora', 'LORICA (CORD)', 'LORICA', 'CORD'),
  ('coordinadora', 'LOS ANDES (MG/LENA)', 'LOS ANDES', 'MG/LENA'),
  ('coordinadora', 'LOS CORDOBAS (CORD)', 'LOS CORDOBAS', 'CORD'),
  ('coordinadora', 'LOS GOMEZ (CORD)', 'LOS GOMEZ', 'CORD'),
  ('coordinadora', 'LOS PALMITOS (SUCRE)', 'LOS PALMITOS', 'SUCRE'),
  ('coordinadora', 'LOS PATIOS (N/STDER)', 'LOS PATIOS', 'N/STDER'),
  ('coordinadora', 'LOS PONDORES (GUAJ)', 'LOS PONDORES', 'GUAJ'),
  ('coordinadora', 'LOS SANTOS (STDER)', 'LOS SANTOS', 'STDER'),
  ('coordinadora', 'LOURDES (N/STDER)', 'LOURDES', 'N/STDER'),
  ('coordinadora', 'LURUACO (ATL)', 'LURUACO', 'ATL'),
  ('coordinadora', 'MACANAL (BOY)', 'MACANAL', 'BOY'),
  ('coordinadora', 'MACEO (ANT)', 'MACEO', 'ANT'),
  ('coordinadora', 'MACHETA (C/MARCA)', 'MACHETA', 'C/MARCA'),
  ('coordinadora', 'MADRID (C/MARCA)', 'MADRID', 'C/MARCA'),
  ('coordinadora', 'MAGANGUE (BOL)', 'MAGANGUE', 'BOL'),
  ('coordinadora', 'MAHATES (BOL)', 'MAHATES', 'BOL'),
  ('coordinadora', 'MAICAO (GUAJ)', 'MAICAO', 'GUAJ'),
  ('coordinadora', 'MAJAGUAL (SUCRE)', 'MAJAGUAL', 'SUCRE'),
  ('coordinadora', 'MAJO (HLA)', 'MAJO', 'HLA'),
  ('coordinadora', 'MALAGA (STDER)', 'MALAGA', 'STDER'),
  ('coordinadora', 'MALAGANA (BOL)', 'MALAGANA', 'BOL'),
  ('coordinadora', 'MALAMBO (ATL)', 'MALAMBO', 'ATL'),
  ('coordinadora', 'MANATI (ATL)', 'MANATI', 'ATL'),
  ('coordinadora', 'MANAURE (GUAJ)', 'MANAURE', 'GUAJ'),
  ('coordinadora', 'MANAURE BALCON DEL CESAR (CES)', 'MANAURE BALCON DEL CESAR', 'CES'),
  ('coordinadora', 'MANDIGUILLA (CES)', 'MANDIGUILLA', 'CES'),
  ('coordinadora', 'MANI (C/NARE)', 'MANI', 'C/NARE'),
  ('coordinadora', 'MANIZALES (CDAS)', 'MANIZALES', 'CDAS'),
  ('coordinadora', 'MANTA (C/MARCA)', 'MANTA', 'C/MARCA'),
  ('coordinadora', 'MANTAGORDAL (CORD)', 'MANTAGORDAL', 'CORD'),
  ('coordinadora', 'MANZANARES (CDAS)', 'MANZANARES', 'CDAS'),
  ('coordinadora', 'MARGARITA (BOL)', 'MARGARITA', 'BOL'),
  ('coordinadora', 'MARIA LA BAJA (BOL)', 'MARIA LA BAJA', 'BOL'),
  ('coordinadora', 'MARIANGOLA (CES)', 'MARIANGOLA', 'CES'),
  ('coordinadora', 'MARINILLA (ANT)', 'MARINILLA', 'ANT'),
  ('coordinadora', 'MARIPI (BOY)', 'MARIPI', 'BOY'),
  ('coordinadora', 'MARIQUITA (TOL)', 'MARIQUITA', 'TOL'),
  ('coordinadora', 'MARMATO (CDAS)', 'MARMATO', 'CDAS'),
  ('coordinadora', 'MARQUETALIA (CDAS)', 'MARQUETALIA', 'CDAS'),
  ('coordinadora', 'MARSELLA (RS)', 'MARSELLA', 'RS'),
  ('coordinadora', 'MARULANDA (CDAS)', 'MARULANDA', 'CDAS'),
  ('coordinadora', 'MATANZA (STDER)', 'MATANZA', 'STDER'),
  ('coordinadora', 'MAYA (C/MARCA)', 'MAYA', 'C/MARCA'),
  ('coordinadora', 'MEDELLIN (ANT)', 'MEDELLIN', 'ANT'),
  ('coordinadora', 'MEDIA LUNA (MG/LENA)', 'MEDIA LUNA', 'MG/LENA'),
  ('coordinadora', 'MEDINA (C/MARCA)', 'MEDINA', 'C/MARCA'),
  ('coordinadora', 'MELCHOR OCAMPO (MEX)', 'MELCHOR OCAMPO', 'MEX'),
  ('coordinadora', 'MELGAR (TOL)', 'MELGAR', 'TOL'),
  ('coordinadora', 'MERCADERES (CAU)', 'MERCADERES', 'CAU'),
  ('coordinadora', 'MESOPOTAMIA (ANT)', 'MESOPOTAMIA', 'ANT'),
  ('coordinadora', 'MIGUEL HIDALGO (CMX)', 'MIGUEL HIDALGO', 'CMX'),
  ('coordinadora', 'MILPA ALTA (CMX)', 'MILPA ALTA', 'CMX'),
  ('coordinadora', 'MINAS (ANT)', 'MINAS', 'ANT');

INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'MINGUEO (GUAJ)', 'MINGUEO', 'GUAJ'),
  ('coordinadora', 'MIRAFLORES (BOY)', 'MIRAFLORES', 'BOY'),
  ('coordinadora', 'MIRANDA (CAU)', 'MIRANDA', 'CAU'),
  ('coordinadora', 'MISTRATO (RS)', 'MISTRATO', 'RS'),
  ('coordinadora', 'MITU (V/PES)', 'MITU', 'V/PES'),
  ('coordinadora', 'MOCOA (P/MAYO)', 'MOCOA', 'P/MAYO'),
  ('coordinadora', 'MOCONDINO (NAR)', 'MOCONDINO', 'NAR'),
  ('coordinadora', 'MOGOTES (STDER)', 'MOGOTES', 'STDER'),
  ('coordinadora', 'MOJARRAS (CAU)', 'MOJARRAS', 'CAU'),
  ('coordinadora', 'MOLAGAVITA (STDER)', 'MOLAGAVITA', 'STDER'),
  ('coordinadora', 'MOLINEROS (ATL)', 'MOLINEROS', 'ATL'),
  ('coordinadora', 'MOMIL (CORD)', 'MOMIL', 'CORD'),
  ('coordinadora', 'MOMPOS (BOL)', 'MOMPOS', 'BOL'),
  ('coordinadora', 'MONDOMO (CAU)', 'MONDOMO', 'CAU'),
  ('coordinadora', 'MONGUA (BOY)', 'MONGUA', 'BOY'),
  ('coordinadora', 'MONGUI (BOY)', 'MONGUI', 'BOY'),
  ('coordinadora', 'MONIQUIRA (BOY)', 'MONIQUIRA', 'BOY'),
  ('coordinadora', 'MONTAÑITA (HLA)', 'MONTAÑITA', 'HLA'),
  ('coordinadora', 'MONTEBELLO (ANT)', 'MONTEBELLO', 'ANT'),
  ('coordinadora', 'MONTEBONITO (CDAS)', 'MONTEBONITO', 'CDAS'),
  ('coordinadora', 'MONTECRISTO (BOL)', 'MONTECRISTO', 'BOL'),
  ('coordinadora', 'MONTELIBANO (CORD)', 'MONTELIBANO', 'CORD'),
  ('coordinadora', 'MONTENEGRO (QDIO)', 'MONTENEGRO', 'QDIO'),
  ('coordinadora', 'MONTERIA (CORD)', 'MONTERIA', 'CORD'),
  ('coordinadora', 'MONTERRALO (C/NARE)', 'MONTERRALO', 'C/NARE'),
  ('coordinadora', 'MONTERREY (C/NARE)', 'MONTERREY', 'C/NARE'),
  ('coordinadora', 'MONTEZUMA (VALLE)', 'MONTEZUMA', 'VALLE'),
  ('coordinadora', 'MORALES (BOL)', 'MORALES', 'BOL'),
  ('coordinadora', 'MORALES (CAU)', 'MORALES', 'CAU'),
  ('coordinadora', 'MORELIA (CAQ)', 'MORELIA', 'CAQ'),
  ('coordinadora', 'MORICHAL (C/NARE)', 'MORICHAL', 'C/NARE'),
  ('coordinadora', 'MORROA (SUCRE)', 'MORROA', 'SUCRE'),
  ('coordinadora', 'MOSQUERA (C/MARCA)', 'MOSQUERA', 'C/MARCA'),
  ('coordinadora', 'MOTAVITA (BOY)', 'MOTAVITA', 'BOY'),
  ('coordinadora', 'MOÑITOS (CORD)', 'MOÑITOS', 'CORD'),
  ('coordinadora', 'MURILLO (TOL)', 'MURILLO', 'TOL'),
  ('coordinadora', 'MURINDO (ANT)', 'MURINDO', 'ANT'),
  ('coordinadora', 'MUTATA (ANT)', 'MUTATA', 'ANT'),
  ('coordinadora', 'MUTISCUA (N/STDER)', 'MUTISCUA', 'N/STDER'),
  ('coordinadora', 'MUZO (BOY)', 'MUZO', 'BOY'),
  ('coordinadora', 'NARIÑO (ANT)', 'NARIÑO', 'ANT'),
  ('coordinadora', 'NARIÑO (BOY)', 'NARIÑO', 'BOY'),
  ('coordinadora', 'NARIÑO (C/MARCA)', 'NARIÑO', 'C/MARCA'),
  ('coordinadora', 'NARIÑO (NAR)', 'NARIÑO', 'NAR'),
  ('coordinadora', 'NATAGA (HLA)', 'NATAGA', 'HLA'),
  ('coordinadora', 'NATAGAIMA (TOL)', 'NATAGAIMA', 'TOL'),
  ('coordinadora', 'NAUCALPAN DE JUAREZ (MEX)', 'NAUCALPAN DE JUAREZ', 'MEX'),
  ('coordinadora', 'NECHI (ANT)', 'NECHI', 'ANT'),
  ('coordinadora', 'NECOCLI (ANT)', 'NECOCLI', 'ANT'),
  ('coordinadora', 'NEIRA (CDAS)', 'NEIRA', 'CDAS'),
  ('coordinadora', 'NEIVA (HLA)', 'NEIVA', 'HLA'),
  ('coordinadora', 'NEMOCON (C/MARCA)', 'NEMOCON', 'C/MARCA'),
  ('coordinadora', 'NEXTLALPAN (MEX)', 'NEXTLALPAN', 'MEX'),
  ('coordinadora', 'NEZAHUALCOYOTL (MEX)', 'NEZAHUALCOYOTL', 'MEX'),
  ('coordinadora', 'NICOLAS ROMERO (MEX)', 'NICOLAS ROMERO', 'MEX'),
  ('coordinadora', 'NILO (C/MARCA)', 'NILO', 'C/MARCA'),
  ('coordinadora', 'NIMAIMA (C/MARCA)', 'NIMAIMA', 'C/MARCA'),
  ('coordinadora', 'NOBSA (BOY)', 'NOBSA', 'BOY'),
  ('coordinadora', 'NOCAIMA (C/MARCA)', 'NOCAIMA', 'C/MARCA'),
  ('coordinadora', 'NORCASIA (CDAS)', 'NORCASIA', 'CDAS'),
  ('coordinadora', 'NOROSI (BOL)', 'NOROSI', 'BOL'),
  ('coordinadora', 'NOVITA (CHOCO)', 'NOVITA', 'CHOCO'),
  ('coordinadora', 'NUEVA COLONIA (ANT)', 'NUEVA COLONIA', 'ANT'),
  ('coordinadora', 'NUEVA ESPERANZA (BOL)', 'NUEVA ESPERANZA', 'BOL'),
  ('coordinadora', 'NUEVA GRANADA (MG/LENA)', 'NUEVA GRANADA', 'MG/LENA'),
  ('coordinadora', 'NUEVO COLON (BOY)', 'NUEVO COLON', 'BOY'),
  ('coordinadora', 'NUNCHIA (C/NARE)', 'NUNCHIA', 'C/NARE'),
  ('coordinadora', 'NUQUI (CHOCO)', 'NUQUI', 'CHOCO'),
  ('coordinadora', 'OBANDO (VALLE)', 'OBANDO', 'VALLE'),
  ('coordinadora', 'OBONUCO (NAR)', 'OBONUCO', 'NAR'),
  ('coordinadora', 'OCAÑA (N/STDER)', 'OCAÑA', 'N/STDER'),
  ('coordinadora', 'OCOYOACAC (MEX)', 'OCOYOACAC', 'MEX'),
  ('coordinadora', 'OIBA (STDER)', 'OIBA', 'STDER'),
  ('coordinadora', 'OICATA (BOY)', 'OICATA', 'BOY'),
  ('coordinadora', 'OLAYA (ANT)', 'OLAYA', 'ANT'),
  ('coordinadora', 'OLAYA HERRERA (TOL)', 'OLAYA HERRERA', 'TOL'),
  ('coordinadora', 'OLIVAL (STDER)', 'OLIVAL', 'STDER'),
  ('coordinadora', 'ONZAGA (STDER)', 'ONZAGA', 'STDER'),
  ('coordinadora', 'OPORAPA (HLA)', 'OPORAPA', 'HLA'),
  ('coordinadora', 'ORIHUECA (MG/LENA)', 'ORIHUECA', 'MG/LENA'),
  ('coordinadora', 'ORITO (P/MAYO)', 'ORITO', 'P/MAYO'),
  ('coordinadora', 'OROCUE (C/NARE)', 'OROCUE', 'C/NARE'),
  ('coordinadora', 'ORTEGA (TOL)', 'ORTEGA', 'TOL'),
  ('coordinadora', 'ORTIGAL (CAU)', 'ORTIGAL', 'CAU'),
  ('coordinadora', 'OSPINA (NAR)', 'OSPINA', 'NAR'),
  ('coordinadora', 'OTANCHE (BOY)', 'OTANCHE', 'BOY'),
  ('coordinadora', 'OTRAMINA (ANT)', 'OTRAMINA', 'ANT'),
  ('coordinadora', 'OVEJAS (SUCRE)', 'OVEJAS', 'SUCRE'),
  ('coordinadora', 'PACHAQUIARO (META)', 'PACHAQUIARO', 'META'),
  ('coordinadora', 'PACHAVITA (BOY)', 'PACHAVITA', 'BOY'),
  ('coordinadora', 'PACHO (C/MARCA)', 'PACHO', 'C/MARCA'),
  ('coordinadora', 'PACORA (CDAS)', 'PACORA', 'CDAS'),
  ('coordinadora', 'PADILLA (CAU)', 'PADILLA', 'CAU'),
  ('coordinadora', 'PADUA (TOL)', 'PADUA', 'TOL'),
  ('coordinadora', 'PAEZ (BOY)', 'PAEZ', 'BOY'),
  ('coordinadora', 'PAICOL (HLA)', 'PAICOL', 'HLA'),
  ('coordinadora', 'PAILITAS (CES)', 'PAILITAS', 'CES'),
  ('coordinadora', 'PAIME (C/MARCA)', 'PAIME', 'C/MARCA'),
  ('coordinadora', 'PAIPA (BOY)', 'PAIPA', 'BOY'),
  ('coordinadora', 'PAISPAMBA SOTARA (CAU)', 'PAISPAMBA SOTARA', 'CAU');

INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'PAJARITO (BOY)', 'PAJARITO', 'BOY'),
  ('coordinadora', 'PALANGUA SEGUNDO SECTOR (BOY)', 'PALANGUA SEGUNDO SECTOR', 'BOY'),
  ('coordinadora', 'PALERMO (ANT)', 'PALERMO', 'ANT'),
  ('coordinadora', 'PALERMO (HLA)', 'PALERMO', 'HLA'),
  ('coordinadora', 'PALERMO (MG/LENA)', 'PALERMO', 'MG/LENA'),
  ('coordinadora', 'PALESTINA (CDAS)', 'PALESTINA', 'CDAS'),
  ('coordinadora', 'PALESTINA (HLA)', 'PALESTINA', 'HLA'),
  ('coordinadora', 'PALMAR DE VARELA (ATL)', 'PALMAR DE VARELA', 'ATL'),
  ('coordinadora', 'PALMIRA (VALLE)', 'PALMIRA', 'VALLE'),
  ('coordinadora', 'PALMITAS (ANT)', 'PALMITAS', 'ANT'),
  ('coordinadora', 'PALO MOCHO (CAU)', 'PALO MOCHO', 'CAU'),
  ('coordinadora', 'PALOCABILDO (TOL)', 'PALOCABILDO', 'TOL'),
  ('coordinadora', 'PALOMINO (GUAJ)', 'PALOMINO', 'GUAJ'),
  ('coordinadora', 'PAMPLONA (N/STDER)', 'PAMPLONA', 'N/STDER'),
  ('coordinadora', 'PAMPLONITA (N/STDER)', 'PAMPLONITA', 'N/STDER'),
  ('coordinadora', 'PANDI (C/MARCA)', 'PANDI', 'C/MARCA'),
  ('coordinadora', 'PANQUEBA (BOY)', 'PANQUEBA', 'BOY'),
  ('coordinadora', 'PANTANO DE VARGAS (BOY)', 'PANTANO DE VARGAS', 'BOY'),
  ('coordinadora', 'PARAMO (STDER)', 'PARAMO', 'STDER'),
  ('coordinadora', 'PARATEBUENO (C/MARCA)', 'PARATEBUENO', 'C/MARCA'),
  ('coordinadora', 'PASACABALLOS (BOL)', 'PASACABALLOS', 'BOL'),
  ('coordinadora', 'PASCA (C/MARCA)', 'PASCA', 'C/MARCA'),
  ('coordinadora', 'PASO CUSIANA CASANARE (C/NARE)', 'PASO CUSIANA CASANARE', 'C/NARE'),
  ('coordinadora', 'PASTALES NUEVO (TOL)', 'PASTALES NUEVO', 'TOL'),
  ('coordinadora', 'PASTALES VIEJO (TOL)', 'PASTALES VIEJO', 'TOL'),
  ('coordinadora', 'PASTO (NAR)', 'PASTO', 'NAR'),
  ('coordinadora', 'PATILLAL (CES)', 'PATILLAL', 'CES'),
  ('coordinadora', 'PATIO BONITO (C/MARCA)', 'PATIO BONITO', 'C/MARCA'),
  ('coordinadora', 'PAUNA (BOY)', 'PAUNA', 'BOY'),
  ('coordinadora', 'PAYANDE (TOL)', 'PAYANDE', 'TOL'),
  ('coordinadora', 'PAZ DE ARIPORO (C/NARE)', 'PAZ DE ARIPORO', 'C/NARE'),
  ('coordinadora', 'PAZ DE RIO (BOY)', 'PAZ DE RIO', 'BOY'),
  ('coordinadora', 'PELAYA (CES)', 'PELAYA', 'CES'),
  ('coordinadora', 'PENSILVANIA (CDAS)', 'PENSILVANIA', 'CDAS'),
  ('coordinadora', 'PEQUE (ANT)', 'PEQUE', 'ANT'),
  ('coordinadora', 'PEREIRA (RS)', 'PEREIRA', 'RS'),
  ('coordinadora', 'PESCA (BOY)', 'PESCA', 'BOY'),
  ('coordinadora', 'PESCADERO (STDER)', 'PESCADERO', 'STDER'),
  ('coordinadora', 'PESCADOR (CAU)', 'PESCADOR', 'CAU'),
  ('coordinadora', 'PEÑA NEGRA (C/MARCA)', 'PEÑA NEGRA', 'C/MARCA'),
  ('coordinadora', 'PEÑALISA (ANT)', 'PEÑALISA', 'ANT'),
  ('coordinadora', 'PIEDECUESTA (STDER)', 'PIEDECUESTA', 'STDER'),
  ('coordinadora', 'PIEDRAHANCHA (NAR)', 'PIEDRAHANCHA', 'NAR'),
  ('coordinadora', 'PIEDRAS (TOL)', 'PIEDRAS', 'TOL'),
  ('coordinadora', 'PIEDRASENTADA (CAU)', 'PIEDRASENTADA', 'CAU'),
  ('coordinadora', 'PIENDAMO (CAU)', 'PIENDAMO', 'CAU'),
  ('coordinadora', 'PIJAO (QDIO)', 'PIJAO', 'QDIO'),
  ('coordinadora', 'PIJIÑO DEL CARMEN (MG/LENA)', 'PIJIÑO DEL CARMEN', 'MG/LENA'),
  ('coordinadora', 'PILCUAN (NAR)', 'PILCUAN', 'NAR'),
  ('coordinadora', 'PINCHOTE (STDER)', 'PINCHOTE', 'STDER'),
  ('coordinadora', 'PINZON (NAR)', 'PINZON', 'NAR'),
  ('coordinadora', 'PIOJO (ATL)', 'PIOJO', 'ATL'),
  ('coordinadora', 'PITAL (ATL)', 'PITAL', 'ATL'),
  ('coordinadora', 'PITAL (HLA)', 'PITAL', 'HLA'),
  ('coordinadora', 'PITALITO (HLA)', 'PITALITO', 'HLA'),
  ('coordinadora', 'PIVIJAY (MG/LENA)', 'PIVIJAY', 'MG/LENA'),
  ('coordinadora', 'PLANADAS (P/MAYO)', 'PLANADAS', 'P/MAYO'),
  ('coordinadora', 'PLANADAS (TOL)', 'PLANADAS', 'TOL'),
  ('coordinadora', 'PLANETA RICA (CORD)', 'PLANETA RICA', 'CORD'),
  ('coordinadora', 'PLATO (MG/LENA)', 'PLATO', 'MG/LENA'),
  ('coordinadora', 'PLAYA MENDOZA (ATL)', 'PLAYA MENDOZA', 'ATL'),
  ('coordinadora', 'PLAYARRICA (TOL)', 'PLAYARRICA', 'TOL'),
  ('coordinadora', 'POLICARPA (NAR)', 'POLICARPA', 'NAR'),
  ('coordinadora', 'POLONIA (HLA)', 'POLONIA', 'HLA'),
  ('coordinadora', 'POLONUEVO (ATL)', 'POLONUEVO', 'ATL'),
  ('coordinadora', 'PONEDERA (ATL)', 'PONEDERA', 'ATL'),
  ('coordinadora', 'PONTEZUELA (BOL)', 'PONTEZUELA', 'BOL'),
  ('coordinadora', 'POPAYAN (CAU)', 'POPAYAN', 'CAU'),
  ('coordinadora', 'PORE (C/NARE)', 'PORE', 'C/NARE'),
  ('coordinadora', 'PORTONES (C/MARCA)', 'PORTONES', 'C/MARCA'),
  ('coordinadora', 'POTOSI (NAR)', 'POTOSI', 'NAR'),
  ('coordinadora', 'PRADERA (VALLE)', 'PRADERA', 'VALLE'),
  ('coordinadora', 'PRADO (TOL)', 'PRADO', 'TOL'),
  ('coordinadora', 'PRADO SEVILLA (MG/LENA)', 'PRADO SEVILLA', 'MG/LENA'),
  ('coordinadora', 'PRESIDENTE (VALLE)', 'PRESIDENTE', 'VALLE'),
  ('coordinadora', 'PROVIDENCIA (NAR)', 'PROVIDENCIA', 'NAR'),
  ('coordinadora', 'PROVIDENCIA (S/ANDRES)', 'PROVIDENCIA', 'S/ANDRES'),
  ('coordinadora', 'PUEBLO BELLO (CES)', 'PUEBLO BELLO', 'CES'),
  ('coordinadora', 'PUEBLO NUEVO (ARA)', 'PUEBLO NUEVO', 'ARA'),
  ('coordinadora', 'PUEBLO NUEVO (CORD)', 'PUEBLO NUEVO', 'CORD'),
  ('coordinadora', 'PUEBLO RICO (RS)', 'PUEBLO RICO', 'RS'),
  ('coordinadora', 'PUEBLONUEVO (MG/LENA)', 'PUEBLONUEVO', 'MG/LENA'),
  ('coordinadora', 'PUEBLORRICO (ANT)', 'PUEBLORRICO', 'ANT'),
  ('coordinadora', 'PUEBLOVIEJO (MG/LENA)', 'PUEBLOVIEJO', 'MG/LENA'),
  ('coordinadora', 'PUENTE BOYACA (BOY)', 'PUENTE BOYACA', 'BOY'),
  ('coordinadora', 'PUENTE DE BAGAZAL (C/MARCA)', 'PUENTE DE BAGAZAL', 'C/MARCA'),
  ('coordinadora', 'PUENTE DE PIEDRA (C/MARCA)', 'PUENTE DE PIEDRA', 'C/MARCA'),
  ('coordinadora', 'PUENTE NACIONAL (STDER)', 'PUENTE NACIONAL', 'STDER'),
  ('coordinadora', 'PUENTE QUETAME (C/MARCA)', 'PUENTE QUETAME', 'C/MARCA'),
  ('coordinadora', 'PUENTE TIERRA (VALLE)', 'PUENTE TIERRA', 'VALLE'),
  ('coordinadora', 'PUERRES (NAR)', 'PUERRES', 'NAR'),
  ('coordinadora', 'PUERTO ARANGO (CAQ)', 'PUERTO ARANGO', 'CAQ'),
  ('coordinadora', 'PUERTO ARAUJO (STDER)', 'PUERTO ARAUJO', 'STDER'),
  ('coordinadora', 'PUERTO ASIS (P/MAYO)', 'PUERTO ASIS', 'P/MAYO'),
  ('coordinadora', 'PUERTO BELGICA (ANT)', 'PUERTO BELGICA', 'ANT'),
  ('coordinadora', 'PUERTO BERRIO (ANT)', 'PUERTO BERRIO', 'ANT'),
  ('coordinadora', 'PUERTO BOGOTA (C/MARCA)', 'PUERTO BOGOTA', 'C/MARCA'),
  ('coordinadora', 'PUERTO BOYACA (BOY)', 'PUERTO BOYACA', 'BOY'),
  ('coordinadora', 'PUERTO CAICEDO (P/MAYO)', 'PUERTO CAICEDO', 'P/MAYO'),
  ('coordinadora', 'PUERTO CARREÑO (VICH)', 'PUERTO CARREÑO', 'VICH');

INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'PUERTO COLOMBIA (ATL)', 'PUERTO COLOMBIA', 'ATL'),
  ('coordinadora', 'PUERTO CONCORDIA (META)', 'PUERTO CONCORDIA', 'META'),
  ('coordinadora', 'PUERTO ESCONDIDO (CORD)', 'PUERTO ESCONDIDO', 'CORD'),
  ('coordinadora', 'PUERTO GAITAN (META)', 'PUERTO GAITAN', 'META'),
  ('coordinadora', 'PUERTO GIRALDO (ATL)', 'PUERTO GIRALDO', 'ATL'),
  ('coordinadora', 'PUERTO GUTIERREZ (BOY)', 'PUERTO GUTIERREZ', 'BOY'),
  ('coordinadora', 'PUERTO GUZMAN (P/MAYO)', 'PUERTO GUZMAN', 'P/MAYO'),
  ('coordinadora', 'PUERTO LEGUIZAMO (P/MAYO)', 'PUERTO LEGUIZAMO', 'P/MAYO'),
  ('coordinadora', 'PUERTO LIBERTADOR (CORD)', 'PUERTO LIBERTADOR', 'CORD'),
  ('coordinadora', 'PUERTO LIBRE (C/MARCA)', 'PUERTO LIBRE', 'C/MARCA'),
  ('coordinadora', 'PUERTO LLERAS (META)', 'PUERTO LLERAS', 'META'),
  ('coordinadora', 'PUERTO LOPEZ (META)', 'PUERTO LOPEZ', 'META'),
  ('coordinadora', 'PUERTO NARE (ANT)', 'PUERTO NARE', 'ANT'),
  ('coordinadora', 'PUERTO NARIÑO (ARAU)', 'PUERTO NARIÑO', 'ARAU'),
  ('coordinadora', 'PUERTO NUEVO (CORD)', 'PUERTO NUEVO', 'CORD'),
  ('coordinadora', 'PUERTO OLAYA (STDER)', 'PUERTO OLAYA', 'STDER'),
  ('coordinadora', 'PUERTO PARRA (STDER)', 'PUERTO PARRA', 'STDER'),
  ('coordinadora', 'PUERTO RICO (CAQ)', 'PUERTO RICO', 'CAQ'),
  ('coordinadora', 'PUERTO RICO (META)', 'PUERTO RICO', 'META'),
  ('coordinadora', 'PUERTO RICO TIQUISIO (BOL)', 'PUERTO RICO TIQUISIO', 'BOL'),
  ('coordinadora', 'PUERTO ROMERO (BOY)', 'PUERTO ROMERO', 'BOY'),
  ('coordinadora', 'PUERTO RONDON (ARAU)', 'PUERTO RONDON', 'ARAU'),
  ('coordinadora', 'PUERTO SALGAR (C/MARCA)', 'PUERTO SALGAR', 'C/MARCA'),
  ('coordinadora', 'PUERTO SANTANDER (N/STDER)', 'PUERTO SANTANDER', 'N/STDER'),
  ('coordinadora', 'PUERTO SERVIEZ (BOY)', 'PUERTO SERVIEZ', 'BOY'),
  ('coordinadora', 'PUERTO TEJADA (CAU)', 'PUERTO TEJADA', 'CAU'),
  ('coordinadora', 'PUERTO TRIUNFO (ANT)', 'PUERTO TRIUNFO', 'ANT'),
  ('coordinadora', 'PUERTO UMBRIA (P/MAYO)', 'PUERTO UMBRIA', 'P/MAYO'),
  ('coordinadora', 'PUERTO VALDIVIA (ANT)', 'PUERTO VALDIVIA', 'ANT'),
  ('coordinadora', 'PUERTO WILCHES (STDER)', 'PUERTO WILCHES', 'STDER'),
  ('coordinadora', 'PULI (C/MARCA)', 'PULI', 'C/MARCA'),
  ('coordinadora', 'PUPIALES (NAR)', 'PUPIALES', 'NAR'),
  ('coordinadora', 'PURACE (CAU)', 'PURACE', 'CAU'),
  ('coordinadora', 'PURIFICACION (TOL)', 'PURIFICACION', 'TOL'),
  ('coordinadora', 'PURISIMA (CORD)', 'PURISIMA', 'CORD'),
  ('coordinadora', 'QUEBRADANEGRA (C/MARCA)', 'QUEBRADANEGRA', 'C/MARCA'),
  ('coordinadora', 'QUETAME (C/MARCA)', 'QUETAME', 'C/MARCA'),
  ('coordinadora', 'QUIBDO (CHOCO)', 'QUIBDO', 'CHOCO'),
  ('coordinadora', 'QUIMBAYA (QDIO)', 'QUIMBAYA', 'QDIO'),
  ('coordinadora', 'QUINAMAYO (CAU)', 'QUINAMAYO', 'CAU'),
  ('coordinadora', 'QUINCHIA (RS)', 'QUINCHIA', 'RS'),
  ('coordinadora', 'QUIPAMA (BOY)', 'QUIPAMA', 'BOY'),
  ('coordinadora', 'QUIPILE (C/MARCA)', 'QUIPILE', 'C/MARCA'),
  ('coordinadora', 'QUITURO (HLA)', 'QUITURO', 'HLA'),
  ('coordinadora', 'RAGONVALIA (N/STDER)', 'RAGONVALIA', 'N/STDER'),
  ('coordinadora', 'RAMIRIQUI (BOY)', 'RAMIRIQUI', 'BOY'),
  ('coordinadora', 'RAQUIRA (BOY)', 'RAQUIRA', 'BOY'),
  ('coordinadora', 'REGIDOR (BOL)', 'REGIDOR', 'BOL'),
  ('coordinadora', 'REMEDIO POBRE (CORD)', 'REMEDIO POBRE', 'CORD'),
  ('coordinadora', 'REMEDIOS (ANT)', 'REMEDIOS', 'ANT'),
  ('coordinadora', 'REMOLINO (MG/LENA)', 'REMOLINO', 'MG/LENA'),
  ('coordinadora', 'REMOLINO (VALLE)', 'REMOLINO', 'VALLE'),
  ('coordinadora', 'REPELON (ATL)', 'REPELON', 'ATL'),
  ('coordinadora', 'RESTREPO (META)', 'RESTREPO', 'META'),
  ('coordinadora', 'RESTREPO (VALLE)', 'RESTREPO', 'VALLE'),
  ('coordinadora', 'RETIRO (ANT)', 'RETIRO', 'ANT'),
  ('coordinadora', 'RICAURTE (C/MARCA)', 'RICAURTE', 'C/MARCA'),
  ('coordinadora', 'RICAURTE (NAR)', 'RICAURTE', 'NAR'),
  ('coordinadora', 'RICAURTE -COLOSO (SUCRE)', 'RICAURTE -COLOSO', 'SUCRE'),
  ('coordinadora', 'RINCON HONDO (CES)', 'RINCON HONDO', 'CES'),
  ('coordinadora', 'RINCON SANTO CENTRO (TOL)', 'RINCON SANTO CENTRO', 'TOL'),
  ('coordinadora', 'RIO DE ORO (CES)', 'RIO DE ORO', 'CES'),
  ('coordinadora', 'RIO FRIO (HLA)', 'RIO FRIO', 'HLA'),
  ('coordinadora', 'RIO FRIO (VALLE)', 'RIO FRIO', 'VALLE'),
  ('coordinadora', 'RIO VIEJO (BOL)', 'RIO VIEJO', 'BOL'),
  ('coordinadora', 'RIOBLANCO (TOL)', 'RIOBLANCO', 'TOL'),
  ('coordinadora', 'RIOFRIO (MG/LENA)', 'RIOFRIO', 'MG/LENA'),
  ('coordinadora', 'RIOHACHA (GUAJ)', 'RIOHACHA', 'GUAJ'),
  ('coordinadora', 'RIONEGRO (ANT)', 'RIONEGRO', 'ANT'),
  ('coordinadora', 'RIONEGRO (CAQ)', 'RIONEGRO', 'CAQ'),
  ('coordinadora', 'RIONEGRO (STDER)', 'RIONEGRO', 'STDER'),
  ('coordinadora', 'RIOSUCIO (CDAS)', 'RIOSUCIO', 'CDAS'),
  ('coordinadora', 'RIOSUCIO (CHOCO)', 'RIOSUCIO', 'CHOCO'),
  ('coordinadora', 'RISARALDA (CDAS)', 'RISARALDA', 'CDAS'),
  ('coordinadora', 'RIVERA (HLA)', 'RIVERA', 'HLA'),
  ('coordinadora', 'ROCHA (BOL)', 'ROCHA', 'BOL'),
  ('coordinadora', 'ROLDANILLO (VALLE)', 'ROLDANILLO', 'VALLE'),
  ('coordinadora', 'RONCESVALLES (TOL)', 'RONCESVALLES', 'TOL'),
  ('coordinadora', 'RONDON (BOY)', 'RONDON', 'BOY'),
  ('coordinadora', 'ROSAS (CAU)', 'ROSAS', 'CAU'),
  ('coordinadora', 'ROTINET (ATL)', 'ROTINET', 'ATL'),
  ('coordinadora', 'ROVIRA (TOL)', 'ROVIRA', 'TOL'),
  ('coordinadora', 'ROZO (VALLE)', 'ROZO', 'VALLE'),
  ('coordinadora', 'SABANA DE TORRES (STDER)', 'SABANA DE TORRES', 'STDER'),
  ('coordinadora', 'SABANAGRANDE (ATL)', 'SABANAGRANDE', 'ATL'),
  ('coordinadora', 'SABANALARGA (ANT)', 'SABANALARGA', 'ANT'),
  ('coordinadora', 'SABANALARGA (ATL)', 'SABANALARGA', 'ATL'),
  ('coordinadora', 'SABANALARGA (C/NARE)', 'SABANALARGA', 'C/NARE'),
  ('coordinadora', 'SABANAS DE SAN ANGEL (MG/LENA)', 'SABANAS DE SAN ANGEL', 'MG/LENA'),
  ('coordinadora', 'SABANETA (ANT)', 'SABANETA', 'ANT'),
  ('coordinadora', 'SABOYA (BOY)', 'SABOYA', 'BOY'),
  ('coordinadora', 'SACHICA (BOY)', 'SACHICA', 'BOY'),
  ('coordinadora', 'SAHAGUN (CORD)', 'SAHAGUN', 'CORD'),
  ('coordinadora', 'SALADO BLANCO (HLA)', 'SALADO BLANCO', 'HLA'),
  ('coordinadora', 'SALAMINA (CDAS)', 'SALAMINA', 'CDAS'),
  ('coordinadora', 'SALAMINA (MG/LENA)', 'SALAMINA', 'MG/LENA'),
  ('coordinadora', 'SALAZAR (N/STDER)', 'SALAZAR', 'N/STDER'),
  ('coordinadora', 'SALDANA (TOL)', 'SALDANA', 'TOL'),
  ('coordinadora', 'SALENTO (QDIO)', 'SALENTO', 'QDIO'),
  ('coordinadora', 'SALGAR (ANT)', 'SALGAR', 'ANT');

INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'SALGAR (ATL)', 'SALGAR', 'ATL'),
  ('coordinadora', 'SALONICA LA MARINA (VALLE)', 'SALONICA LA MARINA', 'VALLE'),
  ('coordinadora', 'SAMACA (BOY)', 'SAMACA', 'BOY'),
  ('coordinadora', 'SAMANA (CDAS)', 'SAMANA', 'CDAS'),
  ('coordinadora', 'SAMANIEGO (NAR)', 'SAMANIEGO', 'NAR'),
  ('coordinadora', 'SAMARIA (CDAS)', 'SAMARIA', 'CDAS'),
  ('coordinadora', 'SAMPUES (SUCRE)', 'SAMPUES', 'SUCRE'),
  ('coordinadora', 'SAMUEL SILVERIO (CAU)', 'SAMUEL SILVERIO', 'CAU'),
  ('coordinadora', 'SAN ADOLFO (HLA)', 'SAN ADOLFO', 'HLA'),
  ('coordinadora', 'SAN AGUSTIN (HLA)', 'SAN AGUSTIN', 'HLA'),
  ('coordinadora', 'SAN ALBERTO (CES)', 'SAN ALBERTO', 'CES'),
  ('coordinadora', 'SAN ANDRES (STDER)', 'SAN ANDRES', 'STDER'),
  ('coordinadora', 'SAN ANDRES DE CUERQUIA (ANT)', 'SAN ANDRES DE CUERQUIA', 'ANT'),
  ('coordinadora', 'SAN ANDRES DE SOTAVENTO (CORD)', 'SAN ANDRES DE SOTAVENTO', 'CORD'),
  ('coordinadora', 'SAN ANDRES ISLA (S/ANDRES)', 'SAN ANDRES ISLA', 'S/ANDRES'),
  ('coordinadora', 'SAN ANT DE TEQUEN (C/MARCA)', 'SAN ANT DE TEQUEN', 'C/MARCA'),
  ('coordinadora', 'SAN ANTERO (CORD)', 'SAN ANTERO', 'CORD'),
  ('coordinadora', 'SAN ANTONIO (CAU)', 'SAN ANTONIO', 'CAU'),
  ('coordinadora', 'SAN ANTONIO (TOL)', 'SAN ANTONIO', 'TOL'),
  ('coordinadora', 'SAN ANTONIO (VALLE)', 'SAN ANTONIO', 'VALLE'),
  ('coordinadora', 'SAN ANTONIO DE PRADO (ANT)', 'SAN ANTONIO DE PRADO', 'ANT'),
  ('coordinadora', 'SAN BARTOLOME (CDAS)', 'SAN BARTOLOME', 'CDAS'),
  ('coordinadora', 'SAN BENITO (STDER)', 'SAN BENITO', 'STDER'),
  ('coordinadora', 'SAN BENITO ABAD (SUCRE)', 'SAN BENITO ABAD', 'SUCRE'),
  ('coordinadora', 'SAN BERNARDO (C/MARCA)', 'SAN BERNARDO', 'C/MARCA'),
  ('coordinadora', 'SAN BERNARDO (N/STDER)', 'SAN BERNARDO', 'N/STDER'),
  ('coordinadora', 'SAN BERNARDO (NAR)', 'SAN BERNARDO', 'NAR'),
  ('coordinadora', 'SAN BERNARDO DEL VIENTO (CORD)', 'SAN BERNARDO DEL VIENTO', 'CORD'),
  ('coordinadora', 'SAN CALIXTO (N/STDER)', 'SAN CALIXTO', 'N/STDER'),
  ('coordinadora', 'SAN CARLOS (ANT)', 'SAN CARLOS', 'ANT'),
  ('coordinadora', 'SAN CARLOS (CORD)', 'SAN CARLOS', 'CORD'),
  ('coordinadora', 'SAN CARLOS DE GUAROA (META)', 'SAN CARLOS DE GUAROA', 'META'),
  ('coordinadora', 'SAN CAYETANO (C/MARCA)', 'SAN CAYETANO', 'C/MARCA'),
  ('coordinadora', 'SAN CAYETANO (N/STDER)', 'SAN CAYETANO', 'N/STDER'),
  ('coordinadora', 'SAN CLEMENTE (RS)', 'SAN CLEMENTE', 'RS'),
  ('coordinadora', 'SAN DANIEL (CDAS)', 'SAN DANIEL', 'CDAS'),
  ('coordinadora', 'SAN DIEGO (CDAS)', 'SAN DIEGO', 'CDAS'),
  ('coordinadora', 'SAN DIEGO (CES)', 'SAN DIEGO', 'CES'),
  ('coordinadora', 'SAN EDUARDO (BOY)', 'SAN EDUARDO', 'BOY'),
  ('coordinadora', 'SAN ESTANISLAO (BOL)', 'SAN ESTANISLAO', 'BOL'),
  ('coordinadora', 'SAN FELIPE (TOL)', 'SAN FELIPE', 'TOL'),
  ('coordinadora', 'SAN FELIX (CDAS)', 'SAN FELIX', 'CDAS'),
  ('coordinadora', 'SAN FERNANDO (BOL)', 'SAN FERNANDO', 'BOL'),
  ('coordinadora', 'SAN FERNANDO (MG/LENA)', 'SAN FERNANDO', 'MG/LENA'),
  ('coordinadora', 'SAN FRANCISCO (ANT)', 'SAN FRANCISCO', 'ANT'),
  ('coordinadora', 'SAN FRANCISCO (C/MARCA)', 'SAN FRANCISCO', 'C/MARCA'),
  ('coordinadora', 'SAN FRANCISCO (P/MAYO)', 'SAN FRANCISCO', 'P/MAYO'),
  ('coordinadora', 'SAN GIL (STDER)', 'SAN GIL', 'STDER'),
  ('coordinadora', 'SAN JACINTO (BOL)', 'SAN JACINTO', 'BOL'),
  ('coordinadora', 'SAN JERONIMO (ANT)', 'SAN JERONIMO', 'ANT'),
  ('coordinadora', 'SAN JOAQUIN (CAU)', 'SAN JOAQUIN', 'CAU'),
  ('coordinadora', 'SAN JOAQUIN (STDER)', 'SAN JOAQUIN', 'STDER'),
  ('coordinadora', 'SAN JOSE (ANT)', 'SAN JOSE', 'ANT'),
  ('coordinadora', 'SAN JOSE (CAU)', 'SAN JOSE', 'CAU'),
  ('coordinadora', 'SAN JOSE (CDAS)', 'SAN JOSE', 'CDAS'),
  ('coordinadora', 'SAN JOSE BUBUY (C/NARE)', 'SAN JOSE BUBUY', 'C/NARE'),
  ('coordinadora', 'SAN JOSE DE ALBAN (NAR)', 'SAN JOSE DE ALBAN', 'NAR'),
  ('coordinadora', 'SAN JOSE DE ARIGUANI (MG/LENA)', 'SAN JOSE DE ARIGUANI', 'MG/LENA'),
  ('coordinadora', 'SAN JOSE DE ISNOS (HLA)', 'SAN JOSE DE ISNOS', 'HLA'),
  ('coordinadora', 'SAN JOSE DE LA MONTAÑA (ANT)', 'SAN JOSE DE LA MONTAÑA', 'ANT'),
  ('coordinadora', 'SAN JOSE DE MIRANDA (STDER)', 'SAN JOSE DE MIRANDA', 'STDER'),
  ('coordinadora', 'SAN JOSE DE PARE (BOY)', 'SAN JOSE DE PARE', 'BOY'),
  ('coordinadora', 'SAN JOSE DE URE (CORD)', 'SAN JOSE DE URE', 'CORD'),
  ('coordinadora', 'SAN JOSE DEL FRAGUA (CAQ)', 'SAN JOSE DEL FRAGUA', 'CAQ'),
  ('coordinadora', 'SAN JOSE DEL GUAVIARE (G/VIARE)', 'SAN JOSE DEL GUAVIARE', 'G/VIARE'),
  ('coordinadora', 'SAN JOSE DEL NUS (ANT)', 'SAN JOSE DEL NUS', 'ANT'),
  ('coordinadora', 'SAN JUAN DE ARAMA (META)', 'SAN JUAN DE ARAMA', 'META'),
  ('coordinadora', 'SAN JUAN DE BETULIA (SUCRE)', 'SAN JUAN DE BETULIA', 'SUCRE'),
  ('coordinadora', 'SAN JUAN DE RIOSECO (C/MARCA)', 'SAN JUAN DE RIOSECO', 'C/MARCA'),
  ('coordinadora', 'SAN JUAN DE URABA (ANT)', 'SAN JUAN DE URABA', 'ANT'),
  ('coordinadora', 'SAN JUAN DEL CESAR (GUAJ)', 'SAN JUAN DEL CESAR', 'GUAJ'),
  ('coordinadora', 'SAN JUAN NEPOMUCENO (BOL)', 'SAN JUAN NEPOMUCENO', 'BOL'),
  ('coordinadora', 'SAN LORENZO (CAU)', 'SAN LORENZO', 'CAU'),
  ('coordinadora', 'SAN LORENZO (NAR)', 'SAN LORENZO', 'NAR'),
  ('coordinadora', 'SAN LUIS (ANT)', 'SAN LUIS', 'ANT'),
  ('coordinadora', 'SAN LUIS (TOL)', 'SAN LUIS', 'TOL'),
  ('coordinadora', 'SAN LUIS DE GACENO (BOY)', 'SAN LUIS DE GACENO', 'BOY'),
  ('coordinadora', 'SAN LUIS DE PALENQUE (C/NARE)', 'SAN LUIS DE PALENQUE', 'C/NARE'),
  ('coordinadora', 'SAN MARCOS (SUCRE)', 'SAN MARCOS', 'SUCRE'),
  ('coordinadora', 'SAN MARCOS (VALLE)', 'SAN MARCOS', 'VALLE'),
  ('coordinadora', 'SAN MARTIN (CES)', 'SAN MARTIN', 'CES'),
  ('coordinadora', 'SAN MARTIN (META)', 'SAN MARTIN', 'META'),
  ('coordinadora', 'SAN MARTIN DE LOBA (BOL)', 'SAN MARTIN DE LOBA', 'BOL'),
  ('coordinadora', 'SAN MATEO (BOY)', 'SAN MATEO', 'BOY'),
  ('coordinadora', 'SAN MIGUEL (ANT)', 'SAN MIGUEL', 'ANT'),
  ('coordinadora', 'SAN MIGUEL (TOL)', 'SAN MIGUEL', 'TOL'),
  ('coordinadora', 'SAN MIGUEL DE SEMA (BOY)', 'SAN MIGUEL DE SEMA', 'BOY'),
  ('coordinadora', 'SAN ONOFRE (SUCRE)', 'SAN ONOFRE', 'SUCRE'),
  ('coordinadora', 'SAN PABLO (BOL)', 'SAN PABLO', 'BOL'),
  ('coordinadora', 'SAN PABLO (NAR)', 'SAN PABLO', 'NAR'),
  ('coordinadora', 'SAN PABLO DE BORBUR (BOY)', 'SAN PABLO DE BORBUR', 'BOY'),
  ('coordinadora', 'SAN PEDRO (SUCRE)', 'SAN PEDRO', 'SUCRE'),
  ('coordinadora', 'SAN PEDRO (VALLE)', 'SAN PEDRO', 'VALLE'),
  ('coordinadora', 'SAN PEDRO DE CARTAGO (NAR)', 'SAN PEDRO DE CARTAGO', 'NAR'),
  ('coordinadora', 'SAN PEDRO DE LOS MILAGROS (ANT)', 'SAN PEDRO DE LOS MILAGROS', 'ANT'),
  ('coordinadora', 'SAN PEDRO DE URABA (ANT)', 'SAN PEDRO DE URABA', 'ANT'),
  ('coordinadora', 'SAN PELAYO (CORD)', 'SAN PELAYO', 'CORD'),
  ('coordinadora', 'SAN RAFAEL (ANT)', 'SAN RAFAEL', 'ANT'),
  ('coordinadora', 'SAN RAFAEL (CAU)', 'SAN RAFAEL', 'CAU'),
  ('coordinadora', 'SAN RAFAEL (STDER)', 'SAN RAFAEL', 'STDER');

INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'SAN RAIMUNDO (C/MARCA)', 'SAN RAIMUNDO', 'C/MARCA'),
  ('coordinadora', 'SAN ROQUE (ANT)', 'SAN ROQUE', 'ANT'),
  ('coordinadora', 'SAN ROQUE (CES)', 'SAN ROQUE', 'CES'),
  ('coordinadora', 'SAN SEBAST DE BUENAVI (MG/LENA)', 'SAN SEBAST DE BUENAVI', 'MG/LENA'),
  ('coordinadora', 'SAN SEBASTIAN (CAU)', 'SAN SEBASTIAN', 'CAU'),
  ('coordinadora', 'SAN SEBASTIAN (CORD)', 'SAN SEBASTIAN', 'CORD'),
  ('coordinadora', 'SAN VICENTE (ANT)', 'SAN VICENTE', 'ANT'),
  ('coordinadora', 'SAN VICENTE DE CHUCURI (STDER)', 'SAN VICENTE DE CHUCURI', 'STDER'),
  ('coordinadora', 'SAN VICENTE DEL CAGUAN (CAQ)', 'SAN VICENTE DEL CAGUAN', 'CAQ'),
  ('coordinadora', 'SAN ZENON (MG/LENA)', 'SAN ZENON', 'MG/LENA'),
  ('coordinadora', 'SANDONA (NAR)', 'SANDONA', 'NAR'),
  ('coordinadora', 'SANTA ANA (BOL)', 'SANTA ANA', 'BOL'),
  ('coordinadora', 'SANTA ANA (MG/LENA)', 'SANTA ANA', 'MG/LENA'),
  ('coordinadora', 'SANTA BARBARA (ANT)', 'SANTA BARBARA', 'ANT'),
  ('coordinadora', 'SANTA BARBARA (BOY)', 'SANTA BARBARA', 'BOY'),
  ('coordinadora', 'SANTA BARBARA DE PINTO (MG/LENA)', 'SANTA BARBARA DE PINTO', 'MG/LENA'),
  ('coordinadora', 'SANTA CATALINA (BOL)', 'SANTA CATALINA', 'BOL'),
  ('coordinadora', 'SANTA CATALINA (S/ANDRES)', 'SANTA CATALINA', 'S/ANDRES'),
  ('coordinadora', 'SANTA CRUZ (ATL)', 'SANTA CRUZ', 'ATL'),
  ('coordinadora', 'SANTA ELENA (ANT)', 'SANTA ELENA', 'ANT'),
  ('coordinadora', 'SANTA ELENA (VALLE)', 'SANTA ELENA', 'VALLE'),
  ('coordinadora', 'SANTA FE DE ANTIOQUIA (ANT)', 'SANTA FE DE ANTIOQUIA', 'ANT'),
  ('coordinadora', 'SANTA HELENA DEL OPON (STDER)', 'SANTA HELENA DEL OPON', 'STDER'),
  ('coordinadora', 'SANTA ISABEL (CES)', 'SANTA ISABEL', 'CES'),
  ('coordinadora', 'SANTA ISABEL (TOL)', 'SANTA ISABEL', 'TOL'),
  ('coordinadora', 'SANTA ISABELL (ANT)', 'SANTA ISABELL', 'ANT'),
  ('coordinadora', 'SANTA LUCIA (ATL)', 'SANTA LUCIA', 'ATL'),
  ('coordinadora', 'SANTA MARIA (BOY)', 'SANTA MARIA', 'BOY'),
  ('coordinadora', 'SANTA MARIA (HLA)', 'SANTA MARIA', 'HLA'),
  ('coordinadora', 'SANTA MARTA (MG/LENA)', 'SANTA MARTA', 'MG/LENA'),
  ('coordinadora', 'SANTA RITA (VALLE)', 'SANTA RITA', 'VALLE'),
  ('coordinadora', 'SANTA ROSA (BOL)', 'SANTA ROSA', 'BOL'),
  ('coordinadora', 'SANTA ROSA DE CABAL (RS)', 'SANTA ROSA DE CABAL', 'RS'),
  ('coordinadora', 'SANTA ROSA DE OSOS (ANT)', 'SANTA ROSA DE OSOS', 'ANT'),
  ('coordinadora', 'SANTA ROSA DE VITERBO (BOY)', 'SANTA ROSA DE VITERBO', 'BOY'),
  ('coordinadora', 'SANTA ROSA DEL SUR (BOL)', 'SANTA ROSA DEL SUR', 'BOL'),
  ('coordinadora', 'SANTA ROSALIA (VICH)', 'SANTA ROSALIA', 'VICH'),
  ('coordinadora', 'SANTA ROSITA (C/MARCA)', 'SANTA ROSITA', 'C/MARCA'),
  ('coordinadora', 'SANTA SOFIA (BOY)', 'SANTA SOFIA', 'BOY'),
  ('coordinadora', 'SANTA TERESA (TOL)', 'SANTA TERESA', 'TOL'),
  ('coordinadora', 'SANTA VERONICA (ATL)', 'SANTA VERONICA', 'ATL'),
  ('coordinadora', 'SANTANA (BOY)', 'SANTANA', 'BOY'),
  ('coordinadora', 'SANTANA (P/MAYO)', 'SANTANA', 'P/MAYO'),
  ('coordinadora', 'SANTANDER DE QUILICHAO (CAU)', 'SANTANDER DE QUILICHAO', 'CAU'),
  ('coordinadora', 'SANTANDERSITO (C/MARCA)', 'SANTANDERSITO', 'C/MARCA'),
  ('coordinadora', 'SANTIAGO (ANT)', 'SANTIAGO', 'ANT'),
  ('coordinadora', 'SANTIAGO (N/STDER)', 'SANTIAGO', 'N/STDER'),
  ('coordinadora', 'SANTIAGO (P/MAYO)', 'SANTIAGO', 'P/MAYO'),
  ('coordinadora', 'SANTIAGO PEREZ (TOL)', 'SANTIAGO PEREZ', 'TOL'),
  ('coordinadora', 'SANTO DOMINGO (ANT)', 'SANTO DOMINGO', 'ANT'),
  ('coordinadora', 'SANTO TOMAS (ATL)', 'SANTO TOMAS', 'ATL'),
  ('coordinadora', 'SANTUARIO (RS)', 'SANTUARIO', 'RS'),
  ('coordinadora', 'SAPUYES (NAR)', 'SAPUYES', 'NAR'),
  ('coordinadora', 'SARAVENA (ARAU)', 'SARAVENA', 'ARAU'),
  ('coordinadora', 'SARDINATA (N/STDER)', 'SARDINATA', 'N/STDER'),
  ('coordinadora', 'SASAIMA (C/MARCA)', 'SASAIMA', 'C/MARCA'),
  ('coordinadora', 'SATIVANORTE (BOY)', 'SATIVANORTE', 'BOY'),
  ('coordinadora', 'SATIVASUR (BOY)', 'SATIVASUR', 'BOY'),
  ('coordinadora', 'SEGOVIA (ANT)', 'SEGOVIA', 'ANT'),
  ('coordinadora', 'SESQUILE (C/MARCA)', 'SESQUILE', 'C/MARCA'),
  ('coordinadora', 'SEVILLA (VALLE)', 'SEVILLA', 'VALLE'),
  ('coordinadora', 'SIACHOQUE (BOY)', 'SIACHOQUE', 'BOY'),
  ('coordinadora', 'SIBATE (C/MARCA)', 'SIBATE', 'C/MARCA'),
  ('coordinadora', 'SIBUNDOY (P/MAYO)', 'SIBUNDOY', 'P/MAYO'),
  ('coordinadora', 'SILOS (N/STDER)', 'SILOS', 'N/STDER'),
  ('coordinadora', 'SILVANIA (C/MARCA)', 'SILVANIA', 'C/MARCA'),
  ('coordinadora', 'SILVIA (CAU)', 'SILVIA', 'CAU'),
  ('coordinadora', 'SIMACOTA (STDER)', 'SIMACOTA', 'STDER'),
  ('coordinadora', 'SIMIJACA (C/MARCA)', 'SIMIJACA', 'C/MARCA'),
  ('coordinadora', 'SIMITI (BOL)', 'SIMITI', 'BOL'),
  ('coordinadora', 'SINCE (SUCRE)', 'SINCE', 'SUCRE'),
  ('coordinadora', 'SINCELEJO (SUCRE)', 'SINCELEJO', 'SUCRE'),
  ('coordinadora', 'SIPI (CHOCO)', 'SIPI', 'CHOCO'),
  ('coordinadora', 'SITIO NUEVO (MG/LENA)', 'SITIO NUEVO', 'MG/LENA'),
  ('coordinadora', 'SOACHA (C/MARCA)', 'SOACHA', 'C/MARCA'),
  ('coordinadora', 'SOATA (BOY)', 'SOATA', 'BOY'),
  ('coordinadora', 'SOCHA (BOY)', 'SOCHA', 'BOY'),
  ('coordinadora', 'SOCORRO (STDER)', 'SOCORRO', 'STDER'),
  ('coordinadora', 'SOCOTA (BOY)', 'SOCOTA', 'BOY'),
  ('coordinadora', 'SOGAMOSO (BOY)', 'SOGAMOSO', 'BOY'),
  ('coordinadora', 'SOLEDAD (ATL)', 'SOLEDAD', 'ATL'),
  ('coordinadora', 'SOLITA (CAQ)', 'SOLITA', 'CAQ'),
  ('coordinadora', 'SOMONDOCO (BOY)', 'SOMONDOCO', 'BOY'),
  ('coordinadora', 'SONSO (VALLE)', 'SONSO', 'VALLE'),
  ('coordinadora', 'SONSON (ANT)', 'SONSON', 'ANT'),
  ('coordinadora', 'SOPETRAN (ANT)', 'SOPETRAN', 'ANT'),
  ('coordinadora', 'SOPLAVIENTO (BOL)', 'SOPLAVIENTO', 'BOL'),
  ('coordinadora', 'SOPO (C/MARCA)', 'SOPO', 'C/MARCA'),
  ('coordinadora', 'SORA (BOY)', 'SORA', 'BOY'),
  ('coordinadora', 'SORACA (BOY)', 'SORACA', 'BOY'),
  ('coordinadora', 'SOTAQUIRÁ (BOY)', 'SOTAQUIRÁ', 'BOY'),
  ('coordinadora', 'SOTOMAYOR (NAR)', 'SOTOMAYOR', 'NAR'),
  ('coordinadora', 'SUAITA (STDER)', 'SUAITA', 'STDER'),
  ('coordinadora', 'SUAN (ATL)', 'SUAN', 'ATL'),
  ('coordinadora', 'SUAREZ (CAU)', 'SUAREZ', 'CAU'),
  ('coordinadora', 'SUAREZ (TOL)', 'SUAREZ', 'TOL'),
  ('coordinadora', 'SUAZA (HLA)', 'SUAZA', 'HLA'),
  ('coordinadora', 'SUBACHOQUE (C/MARCA)', 'SUBACHOQUE', 'C/MARCA'),
  ('coordinadora', 'SUBIA (C/MARCA)', 'SUBIA', 'C/MARCA'),
  ('coordinadora', 'SUCRE (STDER)', 'SUCRE', 'STDER');

INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'SUCRE (SUCRE)', 'SUCRE', 'SUCRE'),
  ('coordinadora', 'SUESCA (C/MARCA)', 'SUESCA', 'C/MARCA'),
  ('coordinadora', 'SUPATA (C/MARCA)', 'SUPATA', 'C/MARCA'),
  ('coordinadora', 'SUPIA (CDAS)', 'SUPIA', 'CDAS'),
  ('coordinadora', 'SUSA (C/MARCA)', 'SUSA', 'C/MARCA'),
  ('coordinadora', 'SUSACON (BOY)', 'SUSACON', 'BOY'),
  ('coordinadora', 'SUTAMARCHAN (BOY)', 'SUTAMARCHAN', 'BOY'),
  ('coordinadora', 'SUTATAUSA (C/MARCA)', 'SUTATAUSA', 'C/MARCA'),
  ('coordinadora', 'SUTATENZA (BOY)', 'SUTATENZA', 'BOY'),
  ('coordinadora', 'TABIO (C/MARCA)', 'TABIO', 'C/MARCA'),
  ('coordinadora', 'TACARIMENA (C/NARE)', 'TACARIMENA', 'C/NARE'),
  ('coordinadora', 'TADO (CHOCO)', 'TADO', 'CHOCO'),
  ('coordinadora', 'TAGANGA (MG/LENA)', 'TAGANGA', 'MG/LENA'),
  ('coordinadora', 'TALAIGUA NUEVO (BOL)', 'TALAIGUA NUEVO', 'BOL'),
  ('coordinadora', 'TAMALAMEQUE (CES)', 'TAMALAMEQUE', 'CES'),
  ('coordinadora', 'TAMARA (C/NARE)', 'TAMARA', 'C/NARE'),
  ('coordinadora', 'TAME (ARAU)', 'TAME', 'ARAU'),
  ('coordinadora', 'TAMESIS (ANT)', 'TAMESIS', 'ANT'),
  ('coordinadora', 'TAMINANGO (NAR)', 'TAMINANGO', 'NAR'),
  ('coordinadora', 'TANGAREAL CARRETERA (NAR)', 'TANGAREAL CARRETERA', 'NAR'),
  ('coordinadora', 'TANGAREAL DEL MIRA (NAR)', 'TANGAREAL DEL MIRA', 'NAR'),
  ('coordinadora', 'TANGUA (NAR)', 'TANGUA', 'NAR'),
  ('coordinadora', 'TARAZA (ANT)', 'TARAZA', 'ANT'),
  ('coordinadora', 'TARQUI (HLA)', 'TARQUI', 'HLA'),
  ('coordinadora', 'TARSO (ANT)', 'TARSO', 'ANT'),
  ('coordinadora', 'TASCO (BOY)', 'TASCO', 'BOY'),
  ('coordinadora', 'TAURAMENA (C/NARE)', 'TAURAMENA', 'C/NARE'),
  ('coordinadora', 'TAUSA (C/MARCA)', 'TAUSA', 'C/MARCA'),
  ('coordinadora', 'TECAMAC (MEX)', 'TECAMAC', 'MEX'),
  ('coordinadora', 'TELLO (HLA)', 'TELLO', 'HLA'),
  ('coordinadora', 'TENA (C/MARCA)', 'TENA', 'C/MARCA'),
  ('coordinadora', 'TENERIFE (MG/LENA)', 'TENERIFE', 'MG/LENA'),
  ('coordinadora', 'TENJO (C/MARCA)', 'TENJO', 'C/MARCA'),
  ('coordinadora', 'TENZA (BOY)', 'TENZA', 'BOY'),
  ('coordinadora', 'TEOLOYUCAN (MEX)', 'TEOLOYUCAN', 'MEX'),
  ('coordinadora', 'TEORAMA (N/STDER)', 'TEORAMA', 'N/STDER'),
  ('coordinadora', 'TEPOTZOTLAN (MEX)', 'TEPOTZOTLAN', 'MEX'),
  ('coordinadora', 'TERUEL (HLA)', 'TERUEL', 'HLA'),
  ('coordinadora', 'TESALIA (HLA)', 'TESALIA', 'HLA'),
  ('coordinadora', 'TEXCOCO (MEX)', 'TEXCOCO', 'MEX'),
  ('coordinadora', 'TIBACUY (C/MARCA)', 'TIBACUY', 'C/MARCA'),
  ('coordinadora', 'TIBANA (BOY)', 'TIBANA', 'BOY'),
  ('coordinadora', 'TIBASOSA (BOY)', 'TIBASOSA', 'BOY'),
  ('coordinadora', 'TIBIRITA (C/MARCA)', 'TIBIRITA', 'C/MARCA'),
  ('coordinadora', 'TIBU (N/STDER)', 'TIBU', 'N/STDER'),
  ('coordinadora', 'TIERRA ALTA (CORD)', 'TIERRA ALTA', 'CORD'),
  ('coordinadora', 'TILODIRAN (C/NARE)', 'TILODIRAN', 'C/NARE'),
  ('coordinadora', 'TIMANA (HLA)', 'TIMANA', 'HLA'),
  ('coordinadora', 'TIMBA (CAU)', 'TIMBA', 'CAU'),
  ('coordinadora', 'TIMBIO (CAU)', 'TIMBIO', 'CAU'),
  ('coordinadora', 'TIMBIQUI (CAU)', 'TIMBIQUI', 'CAU'),
  ('coordinadora', 'TINJACA (BOY)', 'TINJACA', 'BOY'),
  ('coordinadora', 'TIPACOQUE (BOY)', 'TIPACOQUE', 'BOY'),
  ('coordinadora', 'TITIRIBI (ANT)', 'TITIRIBI', 'ANT'),
  ('coordinadora', 'TLAHUAC (CMX)', 'TLAHUAC', 'CMX'),
  ('coordinadora', 'TLALNEPANTLA DE BAZ (MEX)', 'TLALNEPANTLA DE BAZ', 'MEX'),
  ('coordinadora', 'TLALPAN (CMX)', 'TLALPAN', 'CMX'),
  ('coordinadora', 'TOBIA (C/MARCA)', 'TOBIA', 'C/MARCA'),
  ('coordinadora', 'TOCA (BOY)', 'TOCA', 'BOY'),
  ('coordinadora', 'TOCAIMA (C/MARCA)', 'TOCAIMA', 'C/MARCA'),
  ('coordinadora', 'TOCANCIPA (C/MARCA)', 'TOCANCIPA', 'C/MARCA'),
  ('coordinadora', 'TOGUI (BOY)', 'TOGUI', 'BOY'),
  ('coordinadora', 'TOLEDO (ANT)', 'TOLEDO', 'ANT'),
  ('coordinadora', 'TOLEDO (N/STDER)', 'TOLEDO', 'N/STDER'),
  ('coordinadora', 'TOLU (SUCRE)', 'TOLU', 'SUCRE'),
  ('coordinadora', 'TOLU VIEJO (SUCRE)', 'TOLU VIEJO', 'SUCRE'),
  ('coordinadora', 'TOPAGA (BOY)', 'TOPAGA', 'BOY'),
  ('coordinadora', 'TOPAIPI (C/MARCA)', 'TOPAIPI', 'C/MARCA'),
  ('coordinadora', 'TORIBIO (CAU)', 'TORIBIO', 'CAU'),
  ('coordinadora', 'TORNO ROJO (CORD)', 'TORNO ROJO', 'CORD'),
  ('coordinadora', 'TORO (VALLE)', 'TORO', 'VALLE'),
  ('coordinadora', 'TOTA (BOY)', 'TOTA', 'BOY'),
  ('coordinadora', 'TOTORO (CAU)', 'TOTORO', 'CAU'),
  ('coordinadora', 'TRES ESQUINAS (TOL)', 'TRES ESQUINAS', 'TOL'),
  ('coordinadora', 'TRES ESQUINAS (VALLE)', 'TRES ESQUINAS', 'VALLE'),
  ('coordinadora', 'TRINIDAD (C/NARE)', 'TRINIDAD', 'C/NARE'),
  ('coordinadora', 'TRUJILLO (VALLE)', 'TRUJILLO', 'VALLE'),
  ('coordinadora', 'TUBARA (ATL)', 'TUBARA', 'ATL'),
  ('coordinadora', 'TUCHIN (CORD)', 'TUCHIN', 'CORD'),
  ('coordinadora', 'TUCURINCA (MG/LENA)', 'TUCURINCA', 'MG/LENA'),
  ('coordinadora', 'TUDELA (C/MARCA)', 'TUDELA', 'C/MARCA'),
  ('coordinadora', 'TULTEPEC (MEX)', 'TULTEPEC', 'MEX'),
  ('coordinadora', 'TULTITLAN (MEX)', 'TULTITLAN', 'MEX'),
  ('coordinadora', 'TULUA (VALLE)', 'TULUA', 'VALLE'),
  ('coordinadora', 'TUMACO (NAR)', 'TUMACO', 'NAR'),
  ('coordinadora', 'TUNIA (CAU)', 'TUNIA', 'CAU'),
  ('coordinadora', 'TUNJA (BOY)', 'TUNJA', 'BOY'),
  ('coordinadora', 'TUNUNGUA (BOY)', 'TUNUNGUA', 'BOY'),
  ('coordinadora', 'TUQUERRES (NAR)', 'TUQUERRES', 'NAR'),
  ('coordinadora', 'TURBACO (BOL)', 'TURBACO', 'BOL'),
  ('coordinadora', 'TURBANA (BOL)', 'TURBANA', 'BOL'),
  ('coordinadora', 'TURBO (ANT)', 'TURBO', 'ANT'),
  ('coordinadora', 'TURMEQUE (BOY)', 'TURMEQUE', 'BOY'),
  ('coordinadora', 'TUTA (BOY)', 'TUTA', 'BOY'),
  ('coordinadora', 'TUTAZA (BOY)', 'TUTAZA', 'BOY'),
  ('coordinadora', 'TUTUNENDO (CHOCO)', 'TUTUNENDO', 'CHOCO'),
  ('coordinadora', 'UBALA (C/MARCA)', 'UBALA', 'C/MARCA'),
  ('coordinadora', 'UBAQUE (C/MARCA)', 'UBAQUE', 'C/MARCA'),
  ('coordinadora', 'UBATE (C/MARCA)', 'UBATE', 'C/MARCA'),
  ('coordinadora', 'ULLOA (VALLE)', 'ULLOA', 'VALLE');

INSERT INTO carrier_coverage (carrier, city_coordinadora, city_name, department_abbrev) VALUES
  ('coordinadora', 'UMBITA (BOY)', 'UMBITA', 'BOY'),
  ('coordinadora', 'UNE (C/MARCA)', 'UNE', 'C/MARCA'),
  ('coordinadora', 'UNETE (C/NARE)', 'UNETE', 'C/NARE'),
  ('coordinadora', 'UNGUIA (CHOCO)', 'UNGUIA', 'CHOCO'),
  ('coordinadora', 'URAMITA (ANT)', 'URAMITA', 'ANT'),
  ('coordinadora', 'URIBE (META)', 'URIBE', 'META'),
  ('coordinadora', 'URIBE URIBE (VALLE)', 'URIBE URIBE', 'VALLE'),
  ('coordinadora', 'URIBIA (GUAJ)', 'URIBIA', 'GUAJ'),
  ('coordinadora', 'URRAO (ANT)', 'URRAO', 'ANT'),
  ('coordinadora', 'URUMITA (GUAJ)', 'URUMITA', 'GUAJ'),
  ('coordinadora', 'USIACURI (ATL)', 'USIACURI', 'ATL'),
  ('coordinadora', 'UTICA (C/MARCA)', 'UTICA', 'C/MARCA'),
  ('coordinadora', 'VADO REAL (STDER)', 'VADO REAL', 'STDER'),
  ('coordinadora', 'VALDIVIA (ANT)', 'VALDIVIA', 'ANT'),
  ('coordinadora', 'VALENCIA (CORD)', 'VALENCIA', 'CORD'),
  ('coordinadora', 'VALENCIA JESUS (CES)', 'VALENCIA JESUS', 'CES'),
  ('coordinadora', 'VALENCIA LA PAZ (HLA)', 'VALENCIA LA PAZ', 'HLA'),
  ('coordinadora', 'VALLE DE CHALCO SOLIDARIDAD (MEX)', 'VALLE DE CHALCO SOLIDARIDAD', 'MEX'),
  ('coordinadora', 'VALLE DE SAN JOSE (STDER)', 'VALLE DE SAN JOSE', 'STDER'),
  ('coordinadora', 'VALLE DE SAN JUAN (TOL)', 'VALLE DE SAN JUAN', 'TOL'),
  ('coordinadora', 'VALLEDUPAR (CES)', 'VALLEDUPAR', 'CES'),
  ('coordinadora', 'VALPARAISO (ANT)', 'VALPARAISO', 'ANT'),
  ('coordinadora', 'VALPARAISO (CAQ)', 'VALPARAISO', 'CAQ'),
  ('coordinadora', 'VANGUARDIA (META)', 'VANGUARDIA', 'META'),
  ('coordinadora', 'VEGACHI (ANT)', 'VEGACHI', 'ANT'),
  ('coordinadora', 'VEGALARGA (HLA)', 'VEGALARGA', 'HLA'),
  ('coordinadora', 'VELEZ (STDER)', 'VELEZ', 'STDER'),
  ('coordinadora', 'VELU (TOL)', 'VELU', 'TOL'),
  ('coordinadora', 'VENADILLO (TOL)', 'VENADILLO', 'TOL'),
  ('coordinadora', 'VENECIA (ANT)', 'VENECIA', 'ANT'),
  ('coordinadora', 'VENECIA (C/MARCA)', 'VENECIA', 'C/MARCA'),
  ('coordinadora', 'VENTAQUEMADA (BOY)', 'VENTAQUEMADA', 'BOY'),
  ('coordinadora', 'VENUSTIANO CARRANZA (CMX)', 'VENUSTIANO CARRANZA', 'CMX'),
  ('coordinadora', 'VERGARA (C/MARCA)', 'VERGARA', 'C/MARCA'),
  ('coordinadora', 'VERSALLES (ANT)', 'VERSALLES', 'ANT'),
  ('coordinadora', 'VERSALLES (VALLE)', 'VERSALLES', 'VALLE'),
  ('coordinadora', 'VIANI (C/MARCA)', 'VIANI', 'C/MARCA'),
  ('coordinadora', 'VICTORIA (CDAS)', 'VICTORIA', 'CDAS'),
  ('coordinadora', 'VIJES (VALLE)', 'VIJES', 'VALLE'),
  ('coordinadora', 'VILLA CARO (N/STDER)', 'VILLA CARO', 'N/STDER'),
  ('coordinadora', 'VILLA COLOMBIA (TOL)', 'VILLA COLOMBIA', 'TOL'),
  ('coordinadora', 'VILLA DE LEYVA (BOY)', 'VILLA DE LEYVA', 'BOY'),
  ('coordinadora', 'VILLA DEL ROSARIO (N/STDER)', 'VILLA DEL ROSARIO', 'N/STDER'),
  ('coordinadora', 'VILLA DEL SOCORRO (ANT)', 'VILLA DEL SOCORRO', 'ANT'),
  ('coordinadora', 'VILLA FATIMA (CORD)', 'VILLA FATIMA', 'CORD'),
  ('coordinadora', 'VILLA GORGONA (VALLE)', 'VILLA GORGONA', 'VALLE'),
  ('coordinadora', 'VILLA RICA (CAU)', 'VILLA RICA', 'CAU'),
  ('coordinadora', 'VILLA RICA (TOL)', 'VILLA RICA', 'TOL'),
  ('coordinadora', 'VILLA VIEJA (HLA)', 'VILLA VIEJA', 'HLA'),
  ('coordinadora', 'VILLACAROLA (C/NARE)', 'VILLACAROLA', 'C/NARE'),
  ('coordinadora', 'VILLAGARZON (P/MAYO)', 'VILLAGARZON', 'P/MAYO'),
  ('coordinadora', 'VILLAGOMEZ (C/MARCA)', 'VILLAGOMEZ', 'C/MARCA'),
  ('coordinadora', 'VILLAHERMOSA (TOL)', 'VILLAHERMOSA', 'TOL'),
  ('coordinadora', 'VILLAMARIA (CDAS)', 'VILLAMARIA', 'CDAS'),
  ('coordinadora', 'VILLANUEVA (BOL)', 'VILLANUEVA', 'BOL'),
  ('coordinadora', 'VILLANUEVA (C/NARE)', 'VILLANUEVA', 'C/NARE'),
  ('coordinadora', 'VILLANUEVA (GUAJ)', 'VILLANUEVA', 'GUAJ'),
  ('coordinadora', 'VILLANUEVA (STDER)', 'VILLANUEVA', 'STDER'),
  ('coordinadora', 'VILLAPINZON (C/MARCA)', 'VILLAPINZON', 'C/MARCA'),
  ('coordinadora', 'VILLARESTREPO (TOL)', 'VILLARESTREPO', 'TOL'),
  ('coordinadora', 'VILLAVICENCIO (META)', 'VILLAVICENCIO', 'META'),
  ('coordinadora', 'VILLETA (C/MARCA)', 'VILLETA', 'C/MARCA'),
  ('coordinadora', 'VIOTA (C/MARCA)', 'VIOTA', 'C/MARCA'),
  ('coordinadora', 'VIRACACHA (BOY)', 'VIRACACHA', 'BOY'),
  ('coordinadora', 'VISTA HERMOSA (META)', 'VISTA HERMOSA', 'META'),
  ('coordinadora', 'VITERBO (CDAS)', 'VITERBO', 'CDAS'),
  ('coordinadora', 'XOCHIMILCO (CMX)', 'XOCHIMILCO', 'CMX'),
  ('coordinadora', 'YACOPI (C/MARCA)', 'YACOPI', 'C/MARCA'),
  ('coordinadora', 'YACUANQUER (NAR)', 'YACUANQUER', 'NAR'),
  ('coordinadora', 'YAGUARA (HLA)', 'YAGUARA', 'HLA'),
  ('coordinadora', 'YALI (ANT)', 'YALI', 'ANT'),
  ('coordinadora', 'YARUMAL (ANT)', 'YARUMAL', 'ANT'),
  ('coordinadora', 'YOLOMBO (ANT)', 'YOLOMBO', 'ANT'),
  ('coordinadora', 'YONDO CASABE (ANT)', 'YONDO CASABE', 'ANT'),
  ('coordinadora', 'YOPAL (C/NARE)', 'YOPAL', 'C/NARE'),
  ('coordinadora', 'YOTOCO (VALLE)', 'YOTOCO', 'VALLE'),
  ('coordinadora', 'YUMBO (VALLE)', 'YUMBO', 'VALLE'),
  ('coordinadora', 'YUTO (CHOCO)', 'YUTO', 'CHOCO'),
  ('coordinadora', 'ZAMBRANO (BOL)', 'ZAMBRANO', 'BOL'),
  ('coordinadora', 'ZAPATOCA (STDER)', 'ZAPATOCA', 'STDER'),
  ('coordinadora', 'ZARAGOZA (ANT)', 'ZARAGOZA', 'ANT'),
  ('coordinadora', 'ZARZAL (VALLE)', 'ZARZAL', 'VALLE'),
  ('coordinadora', 'ZAWADY (MG/LENA)', 'ZAWADY', 'MG/LENA'),
  ('coordinadora', 'ZETAQUIRA (BOY)', 'ZETAQUIRA', 'BOY'),
  ('coordinadora', 'ZIPACON (C/MARCA)', 'ZIPACON', 'C/MARCA'),
  ('coordinadora', 'ZIPAQUIRA (C/MARCA)', 'ZIPAQUIRA', 'C/MARCA'),
  ('coordinadora', 'ZULUAGA (HLA)', 'ZULUAGA', 'HLA'),
  ('coordinadora', 'ZUMPANGO (MEX)', 'ZUMPANGO', 'MEX'),
  ('coordinadora', 'ZUNGO CARRETERA (ANT)', 'ZUNGO CARRETERA', 'ANT');

-- Total Coordinadora cities seeded: 1489

-- 5. Best-effort DANE municipality matching
-- Match coverage cities to DANE municipalities by normalized name
UPDATE carrier_coverage cc
SET dane_municipality_id = dm.id
FROM dane_municipalities dm
WHERE cc.city_name = dm.municipality_name_normalized
  AND cc.dane_municipality_id IS NULL;
